### ISSUE TITLE
Add `Promise#fork()` and `RxRatpack#fork()` to enable explicit, composable, parallelism 

### ISSUE THREAD

**Issue by tednaleid** [ratpack/ratpack#1012]
The parallel batch code added in 1.4 (to solve #840) do a nice job of letting you work with a list of `Promise<T>`, where all of the promises emit the same class of object.

There are additional cases where you might want to run promises that are not of homogenous types in parallel that current code doesn't solve without manual casting.

After a discussion with @alkemist on slack where I'd proposed a `parallelPromise` method that emits a `Pair` of resolved promises, he came up with a much more elegant suggestion: `Promise#fork()`.

Using it would fork the execution that the `Promise` is executed on and the value would wait to be picked up on the current thread via the promise it returns.  So if you used:

```
Promise.value(1).left(Promise.value(2).fork()).then { assert it == Pair.of(2, 1) }`
```

the `1` promise would be run on the current compute thread, but `2` would be done on the "next" compute thread (via `Execution.fork()` under the covers).  It returns a `Promise` that's given to `left` that is completed when the result is available.

An additional benefit of this is that the type of the promise is preserved so that composing promises of different types (via operations like `left`) keeps types whole without any casting.

Additionally, the `fork` method should also added to `RxRatpack` so that an `Observable` could also be run on another thread in parallel.  This would enable using explicit parallelism with RxJava with functions like zip:

```
Observable.zip(Observable.just(1), Observable.just(2).fork(), { val1, val2 -> 
    assert Pair(val1, val2) == Pair(1, 2) 
})
```

Having this method keeps Ratpack's "no implicit parallelism" ideals intact, but gives the end user an explicit way to easily mark a particular promise/observable as one that runs in parallel.

**Comment by alkemist** [comment]
@tednaleid I've added this to promise. Would you like to submit a PR for the Rx bit?

**Comment by tednaleid** [comment]
@alkemist yep, I'll get started on it tonight.  Thanks for the quick work on it!
