### ISSUE TITLE
Offer high res/vector logos/media downloads from the site

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#102]
People can use these for promoting ratpack.

**Comment by alkemist** [comment]
@robfletcher do you have these files?

**Comment by robfletcher** [comment]
I have some large PNGs (and can produce more at any size you'd like) but not vector.

**Comment by alkemist** [comment]
I'll take them. How can I get them?

**Comment by robfletcher** [comment]
![sticker](https://cloud.githubusercontent.com/assets/95210/8368567/ec15776a-1b60-11e5-8bcc-f6ba4477e48e.png)
![ratpack-huge](https://cloud.githubusercontent.com/assets/95210/8368574/00ab68e2-1b61-11e5-97ec-3283add65fca.png)

**Comment by danhyun** [comment]
:+1:
