### ISSUE TITLE
ServerConfig.address should be configurable via environment variable and system property

### ISSUE THREAD

**Issue by JonasHavers** [ratpack/ratpack#1032]
In addition to the environment variables `RATPACK_PORT`, `RATPACK_PUBLIC_ADDRESS`, `RATPACK_DEVELOPMENT` it would be helpful if we could provide the inet address to bind the ratpack server to.

For example, hosting a DYI cartridge at Openshift requires the application to bind to a specific (dynamic) IP address ($OPENSHIFT_DIY_IP). Providing a general solution to configure the inet address externally, it will be possible to deploy an unmodified fat-jar to multiple cartridges.

To stay consistent with the `ratpack.server.ServerConfig#address` naming, I suggest the environment variable name `RATPACK_ADDRESS` and the system property name `ratpack.address`. This may be added to `ratpack.server.internal.ServerEnvironment` in `ratpack-core`.

**Comment by alkemist** [comment]
Makes sense, and plan sounds good.

**Comment by alkemist** [comment]
FYI, if you enable the env var config source, you can use `«prefix»SERVER__ADDRESS` to set this with released versions.

**Comment by JonasHavers** [comment]
Thanks for your quick response, Luke. Enabling the env var config source does the job for now. For the sake of documentation it is done this way:
```
ratpack {
  serverConfig {
    env()
  }
}
```
So my starter script ("start action_hook") at Openshift looks like this now:
```
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH
export RATPACK_SERVER__ADDRESS=$OPENSHIFT_DIY_IP
export RATPACK_SERVER__PORT=$OPENSHIFT_DIY_PORT
nohup java -jar $OPENSHIFT_REPO_DIR/<MY_DIR>/<MY_JAR>.jar |& /usr/bin/logshifter -tag ratpack &
```

I will write a blog post on deploying a ratpack application to a DIY cartridge on Openshift. Before that, I will provide a pull request for this issue.
