### ISSUE TITLE
Add sugar for attaching config path to config type directly

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#1039]
```
interface ServerConfigBuilder {
  ServerConfigBuilder require(Class<?> configType)
}
```

```
@ConfigPath("/conf")
class MyConfig {
…
}
```

The pathless version of require() would look for the annotation and use its value. Will throw if the type has no annotation.

**Comment by alkemist** [comment]
This may not be the right thing to do. It does distribute the actual bindings throughout the application, whereas with the current approach they are centralized (i.e. at the current require() callsites).

**Comment by danveloper** [comment]
Personally, I like it more explicit in the `serverConfig` block. Distributing the binding declaration makes it so you have to look at multiple sources to get a handle on where properties are coming from.

**Comment by johnrengelman** [comment]
Agree. Personally I like the declarative syntax such there is a single point of authority for config.

**Comment by alkemist** [comment]
I'm leaning towards closing this as wontfix. Will keep it open a little longer to see if anyone else has opinions.

**Comment by davidmc24** [comment]
Agreed with Dan/John.  Additionally, having multiple ways to specify the path makes it more confusing for users.

**Comment by alkemist** [comment]
3 -1's. Closing as wontfix.
