### ISSUE TITLE
ratpack-pac4j: Provide a method to reject the authenticated user

### ISSUE THREAD

**Issue by JonasHavers** [ratpack/ratpack#1044]
Recently, I built a private project with GitHub and Twitter authentication using `ratpack-pac4j`. At first, I used the method `ratpack.pac4j.RatpackPac4j#requireAuth` for authentication and ended up wondering why I was authenticated in other areas of the web application that were not "secured" via `RatpackPac4j#requireAuth`. That is, the `org.pac4j.core.profile.UserProfile` was set in the current session and accessible via `RatpackPac4j.userProfile(ctx)`, even though the conditions of an `org.pac4j.core.authorization.Authorizer` I passed to `RatpackPac4j#requireAuth` were not satisfied.

I looked at the RatpackPac4J implementation and realized that the `Authorizer`s only prevent you from accessing the restricted route(s). The `UserProfile` is put into the session anyway and not explicitly removed at any point. Within the `ratpack.pac4j.internal.Pac4jAuthenticator`, the authenticated `UserProfile` (i.e. the GitHub/Twitter profile) is stored into the session through `sessionData.set(Pac4jSessionKeys.USER_PROFILE, profile)`. It is then retrieved from the session in `RatpackPac4j#userProfile(ctx, UserProfile.class)` via `ctx.get(Session.class).get(Pac4jSessionKeys.USER_PROFILE)`.

Long story short, I ended up implementing a piece of code to reject the authentication based on `Authorizers`, i.e. to "reject" the authentication by doing a logout based on an undesired profile id and what have you. This may be a use case other people have, so in my opinion it would be a great feature to have in the `ratpack-pac4j` implementation. An ideal solution may avoid the session storage of the `UserProfile` at all.

To illustrate what I ended up with using the given `RatpackPac4j` methods, this is some sample typed Groovy code:
```
static Action<Chain> authChain() {
    chain {
        all(authenticator('callback', githubClient, twitterClient))
        prefix('login') {
            path('github', authenticate(GitHubClient, githubId))
            path('twitter', authenticate(TwitterClient, twitterId))
        }
        path('logout') { Context ctx -> logout(ctx).then { ctx.redirect('/') }
        }
    }
}

static <C extends Credentials, U extends UserProfile> Handler authenticate(Class<? extends Client<C, U>> clientClass, String expectedProfileId) {
    authenticate(clientClass, { Context ctx, u ->
        ctx.redirect('/')
    }, { Context ctx, u ->
        ctx.clientError(403)
    }, { ctx, UserProfile profile ->
        profile.id == expectedProfileId
    })
}

static <C extends Credentials, U extends UserProfile> Handler authenticate(Class<? extends Client<C, U>> clientClass, Closure<?> onLogin, Closure<?> onLoginRejected, Authorizer... authorizers) {
    { Context ctx ->
        RatpackWebContext.from(ctx, false).then({ WebContext webContext ->
            login(ctx, clientClass).route({ U userProfile ->
                authorizers.every({ Authorizer a -> a == null || a.isAuthorized(webContext, userProfile) })
            }, { U userProfile -> onLogin(ctx, userProfile) }).then({ U userProfile ->
                logout(ctx).then({ onLoginRejected(ctx, userProfile) })
            })
        })
    } as Handler
}
```
There may be better solutions to solve the issue. I would like to read yours.

**Comment by alkemist** [comment]
IIUC, the issue here is that you want to be able to effectively authorize a login, and the API only supports authorizing a logged in user to perform some action. Is that right?

I wonder if we could push this down to pac4j instead of specific Ratpack support. It seems like subclassing the Client classes might be viable.

@leleuj do you have any opinions on this?

**Comment by leleuj** [comment]
Authentication and authorizations are not the same thing. You must be authenticated before checking authorizations. It doesn't mean that unsatisfied authorizations remove the authentication.

So the current behaviour in Ratpack (and pac4j) is normal.

I read a solution, but I'm not sure to see the original problem: practically, what's the issue with storing the authenticated user profile?

**Comment by JonasHavers** [comment]
If the user is authenticated using an (external) authentication provider, I would like to apply my own authorization rules based on the provided user profile. If the user is not authorized to use my application, I want the user profile to not be stored in the session. To put it another way, I want to reject the user's login and therefore I do not want the user profile to be saved to the session. Otherwise I would have to store the login status separately, even if I do not care about the unauthorized user's profile. Does that makes sense for you?

**Comment by leleuj** [comment]
"I would like to apply my own authorization rules based on the provided user profile": you mean develop your own specific `Authorizer` and use it via `requireAuth`?

**Comment by JonasHavers** [comment]
Unfortunately not. That would be a viable solution for an admin back-office or the like. If `requireAuth` would be applied to the root of the application, it would make the application unusable for guests.

Imagine a usual site that includes a login layer and provides more features for logged in users than for guests. If the user profile is set in the session, my assumption would be that the user is authenticated and authorized (i.e. logged in), otherwise the user is a guest. If I am fine with only authenticated users, I would not provide an `Authorizer` and the user should be stored into the session.

In my mind, it would make sense to be provided with two methods:
* `login(..)` -> authenticated user profile is stored into the session (i.e. user is logged in)
* `login(.., Authorizer... a)` -> authenticated user profile is checked against all Authorizers and on success stored into the session

What do you think?

**Comment by leleuj** [comment]
Indeed, if an url is accessible to both unauthenticated and authenticated user, you can't use `requireAuth`.

I still don't see the problem. First, a `RatpackPac4j.userProfile` to get or not the user profile than a manual check using Authorizer` and you'll know if your user / guest is authorized.

**Comment by JonasHavers** [comment]
If the user would not be saved into the session, I would not need to check the `Authorizer`(s) on each page request or save the login status separately, I would instead only check wether the user profile is set (= authenticated & authorized user) in the session or not (= guest) via `RatpackPac4j.userProfile`. It's about centralizing this authorization logic and applying it only at the time of the initial login process. If the issue does not make sense to you, I will of course go with the solution I posted in my initial comment. I just thought it makes sense to provide a common solution to this use case by, for example, adding an varargs `Authorizer` parameter to the `RatpackPac4j .login` method and applying the logic I described.

**Comment by JonasHavers** [comment]
For me, there a two ways of considering a user as 'logged in' at the time of the login:
* User is successfully authenticated, therefore its profile is stored.
* User is successfully authenticated AND authorized, therefore its profile is stored.

The first is what is supported by Ratpack/Pac4j now and in most cases this seems to be enough. The second is what I suggest is helpful.

**Comment by leleuj** [comment]
Maybe you could use: `requireAuth(AnonymousClient)` to always get a profile on authenticated / guest pages, it works on most pac4j implementations, but I'm not sure for Ratpack.

You can use of course for your solution, but I don't think it's a good idea to define the security model and behaviour to save a check. As I said, authentication and authorizations are two different things, I would not create artificial link between them.

**Comment by JonasHavers** [comment]
Alright, thanks @leleuj. I want to create the link in some cases, especially if I do not care about the authentication and the resulting user profile when the authorization fails. But, I also understand your concerns.

**Comment by leleuj** [comment]
You're welcome

@alkemist : we can now close this issue

**Comment by alkemist** [comment]
@JonasHavers can you please confirm that this is “resolved” for you.

**Comment by JonasHavers** [comment]
Thanks for getting back to me, @alkemist. If you agree that this feature is not "library-worthy" like `RatpackPac4j.requireAuth`, I am fine with implementing it in my application code. Thank you for the discussion anyway.

Closed.
