### ISSUE TITLE
ReadTimeoutException results in raw RuntimeException, it should be subclassed

### ISSUE THREAD

**Issue by tednaleid** [ratpack/ratpack#1046]
Currently, when a netty `ReadTimeoutException` is thrown, it [throws a raw RuntimeException](https://github.com/ratpack/ratpack/blob/62d4be299ac55397f3a6d8d781bbe5af22fab40f/ratpack-core/src/main/java/ratpack/http/client/internal/RequestActionSupport.java#L178).

This should be a subclass of `RuntimeException` that end users can look for (in my case, so that I can retry the request with a time delay).

As it is now, I need to look for a `RuntimeException` with a regex looking at the error message to determine if that was the type of exception.

**Comment by erdi** [comment]
+1

https://github.com/ratpack/ratpack/commit/62d4be299ac55397f3a6d8d781bbe5af22fab40f#commitcomment-18556245
