### ISSUE TITLE
Default HttpClient doesn't seem to notice when a chunked stream is completed

### ISSUE THREAD

**Issue by timyates** [ratpack/ratpack#1056]
When trying to upgrade to 1.4.x we're seeing problems with the default `HttpClient` which we're using as a proxy to an upstream dropwizard service.

I have an example project [over here](https://github.com/timyates/potential-ratpack-1.4-httpclient-issue) which exhibits the problem.

To reproduce, run the provided [dropwizard application](https://github.com/timyates/potential-ratpack-1.4-httpclient-issue/tree/master/upstream-dropwizard-service)

This gives you 2 endpoints:

1. [http://localhost:8080/small](http://localhost:8080/small) which returns
a small amount of json data (non-chunked)
2. [http://localhost:8080/big](http://localhost:8080/big) which
returns a larger amount. (chunked)

Then run the [ratpack 1.4.1 application](https://github.com/timyates/potential-ratpack-1.4-httpclient-issue/tree/master/ratpack-proxy)

This gives you 4 endpoints:

### New Pooled HttpClient

- [http://localhost:5050/pooled/small](http://localhost:5050/pooled/small)
- [http://localhost:5050/pooled/big](http://localhost:5050/pooled/big)

### Default HttpClient

- [http://localhost:5050/default/small](http://localhost:5050/default/small)
- [http://localhost:5050/default/big](http://localhost:5050/default/big)

You should see that `default/big` never finishes in Chrome...

**Comment by alkemist** [comment]
Thanks for the detailed report. Will get to this soon, and release a 1.4.2 with a fix.

**Comment by alkemist** [comment]
@timyates I can't reproduce this. The /default/big request works fine for me.

**Comment by timyates** [comment]
Cheers Luke :-)

Looking forward to 1.4.2

![](http://media2.giphy.com/media/33UbGsRWIZhkc/giphy.gif)
