### ISSUE TITLE
Path appending methods on HttpUrlBuilder don't preserve trailing slashes

### ISSUE THREAD

**Issue by erdi** [ratpack/ratpack#1060]
The following `HttpUrlBuilder` methods:
- path()
- encodedPath() 
- maybePath()
  don't preserve trailing slashes.

This is inconsistent with the behaviour of `HttpUrlBuilder.base(URI)` method which does preserve the trailing slash for non empty paths.

**Comment by jansyk13** [comment]
Hello,
is there a plan to fix this? cc @ldaley @erdi  IMO there is a simple fix. But it breaks the backward compatibility of the interface. It is much cleaner than handling the trailing slash in those methods and keeping track of the last segment and whether it should have trailing slash.  https://github.com/ratpack/ratpack/pull/1263
Jan

**Comment by jansyk13** [comment]
Today with colleague we came up with better solution. See the PR

**Comment by johnrengelman** [comment]
Fix in https://github.com/ratpack/ratpack/pull/1444
