### ISSUE TITLE
How to 'eat' a path element in a handler chain?

### ISSUE THREAD

**Issue by mflorence99** [ratpack/ratpack#1075]
I've been trying to figure a way to 'eat' a path element and after lots of experiments I'm drawing a complete blank:

```groovy
  handlers {

    prefix('x') {
      all {
        // do something here to remove 'x' from the path
        next()
      }
    }

    prefix('y/z') { ... }

    prefix(...) { ... }

    // and so on

  }
```

The intent is to define `/x/y/z` as equivalent to `/y/z`. I believe I can achieve this in, for example, Express. I sought to use a technique like this so that none of the downstream path mappings (including filesystem mappings) needed to change -- nor be re-tested.

The idea is to add an optional initial path that an Amazon Application ELB can map to and forward correctly and at the same time preserve all the existing paths unchanged for when the application is used outside of the ELB.

My sincere apologies if this is not the kind of issue expected here and many thanks in advance for any help.

**Comment by danveloper** [comment]
@mflorence99 -- sorry for the delay in getting to this question. This is indeed a question better suited for [the forum](https://forum.ratpack.io). Nonetheless, I'll answer here...

The correct way to do this is to create a class for the handler that will service both routes. For example, if we define a handler as such:

```groovy
package app

import ratpack.handling.*

class MyHandler implements Handler {
  @Override
  void handle(Context ctx) {
    ctx.render("hello world")
  }
}
```

Then in your chain you can attach this as:

```groovy
bindings {
  bind(MyHandler)
}
handlers {
  path("x/y/z", MyHandler)
  path("y/z", MyHandler)
}
```

Thanks and sorry again for the delay.
