### ISSUE TITLE
Proxied compressed EOF framed message never completes

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#1076]
Due to Netty 4.1.2 regression: https://github.com/netty/netty/issues/5892

**Comment by alkemist** [comment]
The underlying Netty issue has been resolved in Netty 4.1.7. We are just waiting for that release now.

**Comment by timyates** [comment]
Thanks for following this up! Will look out for 1.4.5 snapshots for testing 👍

**Comment by alkemist** [comment]
Reopening and moving to 1.5 as Netty 4.1.7 has other issues that prevents us from using it.

Netty 4.1.9 has all of the fixes that we need.

**Comment by alkemist** [comment]
Ratpack 1.5.0 uses Netty 4.1.9.
