### ISSUE TITLE
Handshake Failure when making requests to servers using SNI SSL

### ISSUE THREAD

**Issue by danthegoodman** [ratpack/ratpack#1077]
Example Workaround: https://gist.github.com/danthegoodman/2b4560e607e760d9895b2c3de10ada01

To properly communicate with a server over SSL that uses SNI, additional information needs to be provided to the SSL engine, specifying the target host a port of the destination server.  When ratpack creates the engine, it does not specify the host and port. 

https://github.com/ratpack/ratpack/blob/5cf0ef6e8417cb59ce922271c8565051dfdc1096/ratpack-core/src/main/java/ratpack/http/client/internal/RequestActionSupport.java#L259

Specifying this information is as easy as calling `createSSLEngine(host,port)` instead of `createSSLEngine()`. The question is 1) can it be applied to every request and 2) how should that information be obtained?

If (1) it can be applied to every request, the ssl handler is already being created uniquely to a uri, so (2) we could pass in the request uri to the `createSslHandler` method.

If (1) it cannot be applied to every request, then (2) we'll need to add some sort of specification to the `RequestSpec` or `HttpClientSpec`.

**Comment by carhartl** [comment]
Just ran into this while, in a service, trying to access an endpoint provided by AWS API Gateway. That seems to require SNI SSL...

**Comment by carhartl** [comment]
Trying to use that workaround I'm getting a `java.lang.VerifyError`:
```
java.lang.VerifyError: Bad access to protected data in invokevirtual
Exception Details:
  Location:
    javax/net/ssl/SniSslContextSpi.engineInit([Ljavax/net/ssl/KeyManager;[Ljavax/net/ssl/TrustManager;Ljava/security/SecureRandom;)V @7: invokevirtual
  Reason:
    Type 'javax/net/ssl/SSLContextSpi' (current frame, stack[0]) is not assignable to 'javax/net/ssl/SniSslContextSpi'
  Current Frame:
    bci: @7
    flags: { }
    locals: { 'javax/net/ssl/SniSslContextSpi', '[Ljavax/net/ssl/KeyManager;', '[Ljavax/net/ssl/TrustManager;', 'java/security/SecureRandom' }
    stack: { 'javax/net/ssl/SSLContextSpi', '[Ljavax/net/ssl/KeyManager;', '[Ljavax/net/ssl/TrustManager;', 'java/security/SecureRandom' }
  Bytecode:
    0x0000000: 2ab4 0004 2b2c 2db6 0005 b1 
```

Is there another way to implement SNI support for the built-in http client? Could I use `RequestSpec.sslContext(Factory<SSLContext> factory)`?

**Comment by carhartl** [comment]
I went a different path and now have built my own `HttpClient` along with a subclassed `ContentAggregatingRequestAction` that does this:

```java
private SslHandler createSslHandler() throws NoSuchAlgorithmException {
    SSLEngine sslEngine;
    if (requestConfig.sslContext != null) {
        sslEngine = requestConfig.sslContext.createSSLEngine(this.requestConfig.uri.getHost(), this.requestConfig.uri.getPort());
    } else {
        sslEngine = SSLContext.getDefault().createSSLEngine(this.requestConfig.uri.getHost(), this.requestConfig.uri.getPort());
    }
    sslEngine.setUseClientMode(true);
    return new SslHandler(sslEngine);
}
```

Thanks to the registry this is possible without too much effort. Thanks, that's a really beautiful concept 👍 ❤️ 

I'm eager to get SNI support for the http client into Ratpack, would that be a possible way going forward with a PR?
