### ISSUE TITLE
Can ratpack be a websocket server?

### ISSUE THREAD

**Issue by paulhsu201605** [ratpack/ratpack#1078]
Hi everyone, 

Can ratpack be a websocket server?

I saw ratpack.websocket in ratpack-core. But it seems to be used as a websocket client, am I right?

And I saw node.js can work with socket.io perfectly, can I use ratpack in that way?

**Comment by danveloper** [comment]
hi @paulhsu201605 -- this is a question best suited for [the Ratpack forum](https://forum.ratpack.io), but the answer is yes. See the [WebSockets](https://ratpack.io/manual/current/api/ratpack/websocket/WebSockets.html) class documentation. I also have a [demonstration on my Github](https://github.com/danveloper/ratpack-rx-websockets/blob/master/src/main/java/app/Main.java) of websocket streaming with RxJava.

**Comment by paulhsu201605** [comment]
hi @danveloper I already know how to use it , thanks
