### ISSUE TITLE
Invalid percent-encoding sequences in paths when binding to path tokens throw IllegalArgumentException

### ISSUE THREAD

**Issue by pocockn** [ratpack/ratpack#1079]
Sending requests to paths like `networking%party` which obviously contain bad percent-encoding sequences is a client error and should most probably result in a 400 response. Currently `IllegalArgumentException` is thrown from within `TokenPathBiding.decodeURIComponent(String)` which is very hard to be handled by the application if it would like to send a 400 response in such situation.

Possible solutions:
- Ratpack should respond with 400 in such situations without any action necessary from the application developer
- Wrap the `IllegalArgumentException` in a more specific exception that can then be tested for in `ServerErrorHandler` implementation and handled appropriately

A failing test case to follow.

**Comment by danveloper** [comment]
I'm in favor of the 2nd option. Would you be willing to put together a PR for this?

**Comment by alkemist** [comment]
Dan, what's the basis of your preference? 

I can see that it's moe extensible in that user's could deal with it how they wish. On the flipside, hardly anyone is going to think to or remember to put in specific handling for this exception type and issue a 400.

I think the solution has to involve Ratpack issuing a 400, unless the app has specifically declared it wants to intervene here.

**Comment by erdi** [comment]
How would the app declare that it wants to intervene? Would this be implemented by introducing a new interface similar to `ServerErrorHandler` with a default impl raising a 400 client error and users being able to provide their impl that does something different?

**Comment by alkemist** [comment]
Probably something like that, yes. That would probably be best, and the default can just `ctx.clientError(400)`.

**Comment by danveloper** [comment]
@alkemist I'm not hard-lined on my thoughts on this, but my basis is that a `400` seems to me like a response code that should come from user code. If we wrap the exception, then apps can easily translate it into a `400` on their side. But since it's technically not a valid request in the first place, I can see it both ways... I don't really know.

**Comment by alkemist** [comment]
> but my basis is that a 400 seems to me like a response code that should come from user code

I get that spirit, but I don't think it will work in practice. Most people aren't going to think of this until it bites them.

The default behaviour should be that there is an indication to the client that they did something wrong. The only way to do this would be to issue a 4xx.

We need to see what other frameworks and HTTP servers do when they receive malformed request paths.
