### ISSUE TITLE
Add Promise.nextOpIf(Predicate<? super T> predicate, Function<? super T,? extends Operation> function)

### ISSUE THREAD

**Issue by brucenunk** [ratpack/ratpack#1084]
This would be useful to conditionally execute an Operation. It can be implemented currently using the following but it is very noisy.

```
promise
.flatMapIf({ condition }) { value ->
    operation.map { value }
}
```

**Comment by alkemist** [comment]
Sounds good. Are you up for adding it?

**Comment by brucenunk** [comment]
Yeah sure. I implemented it locally last night but will create a pull request today.

**Comment by brucenunk** [comment]
@alkemist I've submitted a PR for this, https://github.com/ratpack/ratpack/pull/1086

Broke the javadoc tests initially, then screwed up the JavaDoc by running "reformat code" in IntelliJ but it's turned out OK in the end ... I think :)
