### ISSUE TITLE
Provide if/else constructs on Promise and Chain

### ISSUE THREAD

**Issue by etiennestuder** [ratpack/ratpack#1089]
- Promise.mapIfOrElse(Predicate<? super T> predicate, Function<? super T, ? extends T> ifTansformer,  Function<? super T, ? extends T> elseTransformer)
- Promise.flatMapIfOrElse(...)
- Chain.when(boolean test, Class<? extends Action<? super Chain>> ifAction, Class<? extends Action<? super Chain>> elseAction)
- same for the overloaded Chain.when(....) APIs

**Comment by felipefzdz** [comment]
Happy to work on this issue.
