### ISSUE TITLE
FileRenderer only works with GET requests

### ISSUE THREAD

**Issue by kevinmreynolds** [ratpack/ratpack#1091]
The following code appears in ratpack.file.internal.FileRenderer.sendFile
```
    if (!context.getRequest().getMethod().isGet()) {
      context.clientError(405);
      return;
    }
```

Please consider removing this check.  While it may not be a typical use case to send a file as a response to, e.g., a POST, the HTTP spec does not prevent this.  It seems a little too 'opinionated' for a framework with Ratpack's goals to enforce something like this.

**Comment by alkemist** [comment]
That's a straight up bug. Fixed for 1.5.

Thanks for the report.
