### ISSUE TITLE
ratpack.dependency("jackson") requires non-existent dependency

### ISSUE THREAD

**Issue by mattes3** [ratpack/ratpack#1101]
When I put this into build.gradle:

dependency {
  compile ratpack.dependency("jackson")
}

I get an error message saying that ratpack-jackson:1.3.3 is required. However, there is no such version in the repositories. The latest version in MVN is ratpack-jackson:0.9.17.

**Comment by rhart** [comment]
Jackson is now included within Core, so there is no need to add a dependency to ratpack-jackson

**Comment by mattes3** [comment]
Well, then at least this web page needs to be updated:
https://ratpack.io/manual/current/gradle.html

Because when I do what it says there, I get the error message that I was talking about, above.
