### ISSUE TITLE
HttpClient leaks ByteBufs specified using RequestBody.Spec#buffer when connect fails

### ISSUE THREAD

**Issue by brucenunk** [ratpack/ratpack#1102]
I've added a gist to demonstrate this: https://gist.github.com/brucenunk/8a7c5b0e6191f7b83461aab9645bc813

I think the issue is RequestActionSupport creates the RequestConfig in it's constructor but never releases the "body" on connect failure?

I'm happy to pick this up if you would like me to have a look into it more.

**Comment by alkemist** [comment]
I'm not entirely certain how to solve this yet. Generally speaking, we need to detect if the HTTP connection error'd before the Netty infrastructure released the byte buf. I'd like to do this in a more methodical way than looking for certain types of extensions.

**Comment by brucenunk** [comment]
I absolutely agree with that. It would be nice to defer execution of the RequestSpec till the connection was established then the buffer wouldn't be created but that's not possible because it's needed for setting up the pipeline and setting up timeouts.

When you say "more methodical" are you talking at a wider level that just the HttpClient?

**Comment by alkemist** [comment]
> It would be nice to defer execution of the RequestSpec till the connection was established

I think this would create an awkward API for the common case, where users don't really think about it as connect-and-then-send.

We can certainly improve the `RequestSpec` API by allowing to specify factories for the body instead of literals. This would allow deferring the work of generating the body until it's really necessary. We could do this in a backwards compatible way.

> When you say "more methodical" are you talking at a wider level that just the HttpClient?

Not necessarily. The fix can be just for the http client for now.

**Comment by brucenunk** [comment]
> We can certainly improve the RequestSpec API by allowing to specify factories for the body instead of literals.

That's what I've done with my memcache client and it seems to work quite nicely - https://github.com/brucenunk/ratpack-memcache/blob/master/src/main/java/jamesl/Memcache.java#L23. I still need to do a pull request for this but need to do it from my employers github account as it was mostly developed on their time?

What are you thinking, switching out `RequestSpec.Body#buffer(ByteBuf)` for `RequestSpec.Body#buffer(Function<ByteBufAllocator, ByteBuf>)`?
