### ISSUE TITLE
Handlers chain does not support handlers with the same name, but different http method

### ISSUE THREAD

**Issue by jurna** [ratpack/ratpack#1108]
When handlers chain is created with the same name, but different http methods, only the first handler is invoked. The second returns 405.
Here is the unit test:
https://gist.github.com/jurna/4364cc6330c8a9adf924b3bd4e072cd5

**Comment by niwinz** [comment]
This is something expected I think, if you want it you should use the `byMethod` method of Context: https://ratpack.io/manual/current/api/ratpack/handling/Context.html#byMethod-ratpack.func.Action-

**Comment by jurna** [comment]
Ok, missed that. Thanks.
