### ISSUE TITLE
Flexibility for autoCloseable in Promise and Operation

### ISSUE THREAD

**Issue by donaldquixote** [ratpack/ratpack#1113]
On my current project, I found myself wanting both an Operation.close(AutoCloseable) and a Promise/Operation.blockingClose(AutoCloseable).

For now, I have a workaround for my need with the following:

`Operation.blockingNext(() -> { 
            Blocking.on(Promise.value(null).close(autoCloseable)); 
        });`

These requests seem easy enough to add, but I can't get to it right now, and I wasn't sure if there was any Ratpack architecture philosophy or paradigm that this would be working against.

**Comment by donaldquixote** [comment]
...and... I now see why that won't work (doesn't put close call in error/complete handlers). Anyway, I'll see if I can put something together, but in the mean time if anyone else wants to take a stab, then please do.

**Comment by danveloper** [comment]
So what you're looking for is something like a `flatClose`? That would allow you to return a `Promise` from a resource's `close` method?

It might be sufficient to just create a new `Blocking` operation and subscribe to it within the `close` method. You will stay within the same `Execution`.

```groovy
Promise.async { d ->
  ... some async work ...
}.close {
  Blocking.get {
    ... do some blocking work ...
  }.operation().then()
}
```

**Comment by donaldquixote** [comment]
While the suggestion will likely suffice in my case, it's worth pointing out that this will not achieve the same order of execution as you would get without needing to subscribe to the new Blocking op, and I can see that being problematic given that AutoCloseable is often used to define scope for various types of special behavior. This would be especially bad if you are handing a promise off that other code is then free to extend or consume as it wishes - you lose all control over the lifetime of your auto-scope:

```
public class PromisePlayground {
    
static class Foo implements AutoCloseable {

        public void close() throws Exception {
            System.out.println("non-blocking close");
        }
        
    }
    
    static class BlockingFoo implements AutoCloseable {

        public void close() throws Exception {
            Blocking.op(() -> {
                System.out.println("blocking close");
            }).then(); 
        }
        
    }
    
    static public void main(String... args) {
        DefaultExecController controller = new DefaultExecController(1);
        
        Foo foo = new Foo();
        BlockingFoo blockingFoo = new BlockingFoo();
        
        controller.fork().start(exec -> {
            Promise.sync(() -> {
                System.out.println("first");
                return 0;
            }).close(blockingFoo)
            .close(foo)
            .then(x -> {
                System.out.println("last");
            });
        });
    }
}
```

The above yields:
```
first
non-blocking close
last
blocking close
```

**Comment by donaldquixote** [comment]
Am I correct in asserting that Promise#replace can be used as a "synchronization boundary" of sorts to achieve the desired ordering? This would only be acceptable if you're using the promise chain more for flow control than for value generation (i.e. you would otherwise be using Operation if you had the choice).

```
controller.fork().start(exec -> {
            Promise.sync(() -> {
                System.out.println("first");
                return 0;
            }).close(blockingFoo)
            .replace(Promise.value(0)) //this forces blocking close to happen first
            .close(foo)
            .then(x -> {
                System.out.println("last");
            });
        });
```

The above yields:

```
first
blocking close
non-blocking close
last
```

**Comment by alkemist** [comment]
1.5 has close(Operation).
