### ISSUE TITLE
HttpClient read timeouts are not propagated correctly from streamed responses.

### ISSUE THREAD

**Issue by brucenunk** [ratpack/ratpack#1116]
It appears that read timeouts (HttpClientReadTimeoutException) are not propagated to user code when using HttpClient#requestStream. From what I can see the exception is handled in the redirect handler but is discarded because the promise has already been completed (StreamedResponse promise completes when the http response header is received).

I've created a gist that shows this in action, the promise just never completes:
https://gist.github.com/brucenunk/97c98045f6493fe6116ffb13e16df760

**Comment by brucenunk** [comment]
I can look at picking this up if you like?

**Comment by danveloper** [comment]
You're saying you'd expect that if the server does not stream any data within the `readTimeout` window that a `HttpClientReadTimeoutException` will be thrown?

**Comment by brucenunk** [comment]
Hi @danveloper, my issue (in the test case) is that `StreamedResponse#getBody().reduce` never completes. I'm actually using `StreamedResponse#getBody().streamMap()` in my production application and sometimes the downstream service doesn't respond quickly enough in which case I expect an error but it never arrives.

From what I can see the read timeout applies to latency between response chunks as it sits between codec and response handler. Ideally I would like to specify a "maximum response time" but at the very least I need the response to complete.
