### ISSUE TITLE
Migrate CI from Snap to Semaphore

### ISSUE THREAD

**Issue by johnrengelman** [ratpack/ratpack#1132]
- [x] Setup build job
- [x] Connect CodeCov
- [x] Configure artifactory publishing for master branch
- [x] Trigger EXAMPLE_PROJECTS build in Snap
- [x] Connect Slack notifications (built in notifications for Semaphore)
- [x] Deploy Heroku site
- [x] Update CI badge in README.md

**Comment by alkemist** [comment]
I'll work on the artifactory and heroku bits tomorrow.

**Comment by alkemist** [comment]
All done. I've rage deleted the snap build.
