### ISSUE TITLE
Are there any solutions to mark a partial path as path token?

### ISSUE THREAD

**Issue by luoruici** [ratpack/ratpack#1133]
I want to serve the path: sitemap1.xml, sitemap2.xml, ..., sitemapN.xml

I've tried /sitemap:page:\\d+\\.xml, but it can't work.

just use /:path:sitemap\\d+\\.xml I can get {path: sitemap1.xml} as PathTokens

Can I get the page number(e.g. N in sitemapN.xml) directly?

**Comment by danveloper** [comment]
Hi @luoruici! This is a great question for [the forum](https://forum.ratpack.io).

Nonetheless, I'll answer here. What you're looking for is the regex path binding. Here is an example application to demonstrate:

```groovy
@Grab('io.ratpack:ratpack-groovy:1.4.4')

import static ratpack.groovy.Groovy.ratpack
import static ratpack.jackson.Jackson.json
import ratpack.path.PathBinding

ratpack {
  handlers {
    get('::sitemap\\d\\.xml') {
      def pathBinding = get(PathBinding)
      def pageNum = pathBinding.boundTo.replaceAll(~/(^sitemap|\.xml$)/, '')
      render pageNum
    }
  }
}
```
