### ISSUE TITLE
Groovy GString values are ignored by props() in ServerConfigImposition

### ISSUE THREAD

**Issue by jterhune** [ratpack/ratpack#1135]
Using `props()` with a GString value causes it to be ignored silently. I discovered this when trying to use a ServerConfigImposition in my tests. I can understand prohibiting a CharSequence keys, but it seems like a CharSequence value should be allowed. If nothing else, it would be nice to get a descriptive error.

Failing test here:
https://github.com/jterhune/ratpack/commit/8efdb1b2366734de90779933c4e46f180e47cef9

Root cause is `stringPropertyNames()` here: https://github.com/ratpack/ratpack/blob/7764db99c255d292e20e494accf1249e74bc9347/ratpack-core/src/main/java/ratpack/config/internal/source/AbstractPropertiesConfigSource.java#L45

Here's a solution that filters using CharSequence, but there may be a better fix:
```
    Stream<Pair<String, String>> pairs = properties.entrySet().stream()
      .filter(entry -> entry.getKey() instanceof String && entry.getValue() instanceof CharSequence)
      .map(entry -> Pair.of(entry.getKey().toString(), entry.getValue().toString()));
```

**Comment by alkemist** [comment]
Thanks @jterhune
