### ISSUE TITLE
HTTPS client certificate access

### ISSUE THREAD

**Issue by godspeed20** [ratpack/ratpack#1145]
Having setup a ratpack server with ssl, we've been trying to read the certificate that the client authenticates to us with. In Jetty there's a LoginHandler that returns the DN of the client certificate which you can then parse through should you wish to, and we were hoping Ratpack would do something similar or make it available on the context but we couldn't find it anywhere. 

One thing we did try which worked (but is ugly/hacky as hell) is, using the DefaultRatpackServer, override the buildchannel method verbatim but on line 241 we injected our own SSLEngine which we held onto. From that we can access the certificate. But we couldn't find any other way to get to it.

For background, we use certificates for client authent so need to access details of the https certificate to be able to figure out who is using our server.

Does Ratpack expose the client certificate anywhere? Maybe we've missed something obvious so wanted to raise it here. If not, is there a chance of exposing it via the context at all? Thanks

**Comment by shaw500** [comment]
I have the same issue. Setting up SSL seems to be fine, I can authenticate with a server and client certificate. But I have no way of getting the client certificate to find out who ratpack authenticated.

Authenticating someone, then not declaring who they are seems a bit odd :)

**Comment by godspeed20** [comment]
Thank you!
