### ISSUE TITLE
About How to upload image to remote server

### ISSUE THREAD

**Issue by caozhenhuamail** [ratpack/ratpack#1147]
public <T> Observable<JSONObject> executeSinglerUploadMediaRequest(Parameter<JSONObject> parameter, final HttpMethod method) {
        Preconditions.checkArgument(parameter != null, "parameter should not be null or empty");
        Preconditions.checkNotNull(method);

        return Observable.from(Collections.singleton(parameter))
                .flatMap(param -> RxRatpack.observe(httpClient.request(parseURI(param), requestSpec -> {
                    String BOUNDARY = "----WebKitFormBoundaryiDGnV9zdZA1eM1yL"; // 定义数据分隔线
                    requestSpec.getHeaders().add("connection", "Keep-Alive");
                    requestSpec.getHeaders().add("user-agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36");
                    requestSpec.getHeaders().add("Charsert", "UTF-8");
                    requestSpec.getHeaders().add("Content-Type", "multipart/form-data; boundary=" + BOUNDARY);
                    requestSpec.method(method).body(body-> body.bytes(param.getByteBody()));
                })))
                .retry(RETRY_COUNT)
                .retryWhen(attempts -> attempts.zipWith(Observable.range(1, 3), (n, i) -> i).flatMap(i -> Observable.timer(i, TimeUnit.SECONDS)))
                .map(item->handleResponse(parameter,item))
                .first();
    }

the ByteBody method is:
 public static byte[] getFileByteByPath(String path) {
        ByteArrayOutputStream baos = null;
        try {
            baos = new ByteArrayOutputStream();
            String contentType = new MimetypesFileTypeMap().getContentType(new File(path));

            String boundary = "----WebKitFormBoundaryiDGnV9zdZA1eM1yL"; 
            int index = path.lastIndexOf("/");
            String fileName = path.substring(index + 1);
            String fileExt = Utils.getFileExt(contentType);

            baos.write(("--" + boundary + "\r\n").getBytes());
            baos.write(String.format("Content-Disposition: form-data; name=\"media\"; filename=\"file1%s\"\r\n", fileName + fileExt).getBytes());
            baos.write(String.format("Content-Type: %s\r\n\r\n", contentType).getBytes());

            BufferedImage image = ImageIO.read(new URL(path));
            String ext =  getFileExt(contentType).replace(".","");
            ImageIO.write(image, ext, baos);

            baos.write(("\r\n--" + boundary + "--\r\n").getBytes());
            baos.flush();
            return baos.toByteArray();
        } catch (Exception ex) {
            throw new RuntimeException("get path file is error:"+path, ex);
        } finally {
            if (baos != null) {
                try {
                    baos.close();
                } catch (IOException ex) {
                    throw new RuntimeException("get path file is error:"+path, ex);
                }
            }
        }
    }

**Comment by danveloper** [comment]
Looks like this is a question better suited for the [forum](https://forum.ratpack.io/).

**Comment by bitsnaps** [comment]
> Looks like this is a question better suited for the [forum](https://forum.ratpack.io/).

The forum is no longer available! can you provide an example?
