### ISSUE TITLE
Continuous build mode does not reload Log4j configuration

### ISSUE THREAD

**Issue by mkobit** [ratpack/ratpack#1154]
## Reproducible case

I can make a fully reproducible case later today, but here is a summary:

1. Using `id 'io.ratpack.ratpack-java' version '1.4.4'` in `plugins` block
1. Create a main-type class that launches a server
1. Update `build.gradle` to set `mainClassName`
1. Add dependencies on Log4j

        runtime group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: '2.8'
        runtime group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.8'
        runtime group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.8'

1. Add a `log4j2.xml` file to `src/main/resources`, for example:

        <?xml version="1.0" encoding="UTF-8"?>
        <Configuration status="ERROR">
          <Appenders>
            <Console name="Console" target="SYSTEM_OUT">
              <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
            </Console>
          </Appenders>
          <Loggers>
            <Root level="ERROR">
              <AppenderRef ref="Console"/>
            </Root>
          </Loggers>
        </Configuration>

1. Run Gradle in continuous mode (using `3.4-rc-1` in this example) - `./gradlew run -t`
1. Change the `log4j2.xml` file. For example, change `<Root level="ERROR">` to `<Root level="INFO">`

### Expected behavior

Log4j configuration is reloaded with the new configuration data.

### Actual behavior

Log behavior retains that of whatever it was first started with.

**Comment by johnrengelman** [comment]
When you edit the file, do you see Gradle pick up the change and start executing tasks?

**Comment by mkobit** [comment]
@johnrengelman yeah it detects the file change and then executes again:

```
Waiting for changes to input files of tasks... (ctrl-d to exit)
new file: /Users/mkobit/Workspace/mkobit-ratpack-project/src/main/resources/log4j2.xml
deleted: /Users/mkobit/Workspace/mkobit-ratpack-project/src/main/resources/log4j2-BACKUP.xml
Change detected, executing build...

:compileKotlin UP-TO-DATE
:compileJava NO-SOURCE
:copyMainKotlinClasses UP-TO-DATE
:processResources
:classes
:configureRun
:run

BUILD SUCCESSFUL

Total time: 1.218 secs

Waiting for changes to input files of tasks... (ctrl-d to exit)
modified: /Users/mkobit/Workspace/mkobit-ratpack-project/src/main/resources/log4j2.xml
Change detected, executing build...

:compileKotlin UP-TO-DATE
:compileJava NO-SOURCE
:copyMainKotlinClasses UP-TO-DATE
:processResources
:classes
:configureRun
:run
```

**Comment by erdi** [comment]
This is because `log4j2.xml` resource is loaded by Log4j using the same class loader which is used to load Log4j classes and that class loader [is reused and not reloaded when a change is detected in continuous mode](https://github.com/ratpack/ratpack/blob/3e18b5b359b60e38a1ba66fd30204e2aedc28695/ratpack-gradle/src/main/groovy/ratpack/gradle/continuous/RatpackContinuousRun.groovy#L197).

To enable reloading of all classes, even those deemed not changing, you can add the following to your build file:
```
if (gradle.startParameter.continuous) {
    run {
        flattenClassloaders = true
    }
}
````
