### ISSUE TITLE
StartupFailureException is not logged

### ISSUE THREAD

**Issue by jterhune** [ratpack/ratpack#1157]
I observed a situation where one of my services threw an exception in a deployed environment, where java was invoked by [upstart](http://upstart.ubuntu.com/). The exception triggered a `StartupFailureException`. However, the only message in the logback logs was "Stopping services". The exception only appeared in the logs at /var/log/upstart/, which caused some head scratching.

Looking at the code, when a `StartupFailureException` occurs, it is thrown from `ServiceGraph.start()`. I don't see any of the callers catch the exception, so my proposed solution is to add `LOGGER.error()` right before stop is called.

**Comment by jterhune** [comment]
Created PR #1158

**Comment by beckje01** [comment]
Fixed in #1160
