### ISSUE TITLE
Leak with streamedResponse.forwardTo(context.getResponse())

### ISSUE THREAD

**Issue by jeff-blaisdell** [ratpack/ratpack#1163]
Recently, we were putting one of our Ratpack applications through a pre-release load test and discovered an issue with Ratpack's StreamResponse.  This application is essentially a proxy service used to aggregate calls from many underlying micro-services.

Test Case:
We chose ~9 endpoints we expected to incur higher levels of load in production to test.  5 of these endpoints were direct proxies using the StreamedResponse API and the other 4 were aggregation calls using HttpClient's standard CRUD methods.  

Behavior Observed:
* Very low load / functional tests
    * Everything passes green.  No problem observed.
* Low load (~644 requests / second)
    * Periodic HTTP 502 and 504 errors were thrown from our AWS ELB.  Looking at the ELB logs showed ELB was having difficulty obtaining a valid response from AWS instances running the Ratpack application.  These errors were registered seemingly at random across all exposed Ratpack endpoints being observed.  No errors reported by application logs or dropwizard metrics.  Removing API calls being tested one at a time, we observed problem could be resolved by not including the 1 API call that was returning a 204 No Content response.  Running test with the one 204 call commented out resulted in test passing with no errors.

With the above information I went about testing various aspects of the StreamResponse API to try and narrow it down to a specific method, and changing our StreamResponse renderer to look like the following consistently resolved all instances of 504/502 errors:

```
if (streamedResponse.getStatusCode() == HttpStatus.SC_NO_CONTENT) {
    context.getResponse().status(HttpStatus.SC_NO_CONTENT);
    context.getResponse().send();
} else {
    streamedResponse.forwardTo(context.getResponse());
}
```

Here's a Gatling response of a "bad" run:
<img width="752" alt="before" src="https://cloud.githubusercontent.com/assets/992868/22936903/7bfd42c2-f29c-11e6-95ed-84449bc14972.png">

Here's a Gatling response of a "good" run after above renderer was introduced:
<img width="749" alt="after" src="https://cloud.githubusercontent.com/assets/992868/22936927/8f59ba4e-f29c-11e6-8a68-cf16f20c8b6c.png">

Toggling the above renderer code could consistently cause / resolve the observed errors.

**Comment by alkemist** [comment]
Thanks for the very detailed and useful report. Looking into  it.

**Comment by alkemist** [comment]
@jeff-blaisdell I can't reproduce this on master. Is there any chance you could try again with a build based on the current master branch?

**Comment by jeff-blaisdell** [comment]
Sorry, it's been a bit crazy here lately.  Yes, I'll definitely try and get around to re-testing and posting results back here.

**Comment by alkemist** [comment]
@jeff-blaisdell I found it. Please verify at some point with 1.5.0.
