### ISSUE TITLE
HttpClient connections not released from the pool when channel goes inactive

### ISSUE THREAD

**Issue by ashwin1985** [ratpack/ratpack#1187]
The issue is Ratpack(1.4.6) http client connections are not released from the pool when channel goes inactive. When channel goes inactive while trying to render response from a remote server, http client throws PrematureConnectionCloseException. I do understand throwing exception to downstream is the right way to alert downstream that something went wrong but what confuses me is why is the inactive channel not being observed and the connection not getting released from the pool. The connection never gets released and channel stays active causing subsequent request to fail once the max connection pooling size is reached.

Steps to reproduce:

- Create two web services such that service 1, with Httpclient pooling set to 1, makes a call to service 2 and renders the output. Make sure service 2 completely drops while responding back.
- Make request to service 1 endpoint.
- Service 1 will return 500 and logs PrematureConnectionCloseException.
- Bring back service 2. Again, make http request to service 1 endpoint and you would notice that request won’t even reach service 2.

Exception :
`io.netty.handler.codec.PrematureChannelClosureException: Server 'xxxxx' closed the connection prematurely\n\tat ratpack.http.client.internal.RequestActionSupport$1.channelInactive(RequestActionSupport.java:218)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:256)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:235)\n\tat io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)\n\tat io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:257)`

**Comment by alkemist** [comment]
Thanks for the report. Fixed for 1.5.0.

**Comment by myverdict** [comment]
Thanks
