### ISSUE TITLE
Wrong CLASSPATH in shell scripts (trivial)

### ISSUE THREAD

**Issue by katoquro** [ratpack/ratpack#1203]
Classpath generated by application plugin contains path for `${project.name}.jar` but ratpack dist doesn't include it (it uses `$APP_HOME/app`). So libraries which scan classpath fail with `java.io.FileNotFoundException` in runtime (like flyway)

**Comment by katoquro** [comment]
workaround is using of piece of fix in your build.gradle:
```
CreateStartScripts startScripts = project.startScripts
startScripts.with {
    doLast {
        unixScript.text = unixScript.text
                .replace(":\$APP_HOME/lib/${project.name}.jar",'')
        windowsScript.text = windowsScript.text
                .replace(":%APP_HOME%/lib/${project.name}.jar",'')
    }
}
```

**Comment by timic** [comment]
Provided fix is incomplete. Jar file name may include project version and also can be configured in `build.gradle`:

```groovy
jar {
    archiveName = 'custom-jar-name.jar'
}
```

Possible solution is:

```groovy
String jarName = project.tasks.jar.archiveName
script.text.replace(":\$APP_HOME/lib/$jarName", '')
```

**Comment by katoquro** [comment]
@timic 
Yep, you are right. Fixed in https://github.com/ratpack/ratpack/pull/1213

**Comment by katoquro** [comment]
@alkemist 
Please reopen or check RP with fix
