### ISSUE TITLE
Ratpack Retrofit unable to execute outside of main execution flow

### ISSUE THREAD

**Issue by AndrewReitz** [ratpack/ratpack#1232]
When attempting to use a service built but the ratpack retrofit client outside of normal execute flow (handler) a `ratpack.registry.NotInRegistryException: No object for type 'ratpack.handling.Context' in registry` occurs.

Here is some code to demonstrate the issue.

```groovy
ratpack {
  bindings {
    bindInstance(ExampleService, RatpackRetrofit.client('http://example.com').build(ExampleService))
    bindInstance(Service.startup('start') { e ->
      RxRatpack.initialize()

      def httpClient = e.registry.get(HttpClient)
      def exampleService = e.registry.get(ExampleService)

      // works fine
      Observable.interval(5, TimeUnit.SECONDS, RxRatpack.scheduler())
              .flatMap { Promise.value("Hello $it").observe() }
              .subscribe { println it }

      // works fine
      Observable.interval(5, TimeUnit.SECONDS, RxRatpack.scheduler())
              .flatMap { httpClient.get(URI.create('http://example.com/'))
                  .map { it.getBody().text }
                  .observe()
              }
              .subscribe { println it }

      // does not work
      Observable.interval(5, TimeUnit.SECONDS, RxRatpack.scheduler())
              .flatMap { exampleService.exampleHtml.observe() } // causes exception
              .subscribe { println it}
    })
  }
}
```
here is the interface or `ExampleService`

```groovy
interface ExampleService {
  @GET('index.html') Promise<String> getExampleHtml()
}
```

and the full stacktrace.

> [ratpack-compute-27-6] ERROR ratpack.exec.Execution - Uncaught execution exception
> ratpack.registry.NotInRegistryException: No object for type 'ratpack.handling.Context' in registry
>         at ratpack.registry.Registry.get(Registry.java:136)
>         at ratpack.registry.Registry.get(Registry.java:120)
>         at ratpack.retrofit.internal.RatpackCallFactory$RatpackCall.promise(RatpackCallFactory.java:83)
>         at ratpack.retrofit.internal.RatpackCallFactory$RatpackCall.enqueue(RatpackCallFactory.java:70)
>         at retrofit2.OkHttpCall.enqueue(OkHttpCall.java:101)
>         at ratpack.retrofit.internal.RatpackCallAdapterFactory$SimpleCallAdapter.lambda$adapt$0(RatpackCallAdapterFactory.java:135)
>         at ratpack.exec.internal.DefaultExecution.lambda$null$1(DefaultExecution.java:119)
>         at ratpack.exec.internal.DefaultExecution$SingleEventExecStream.exec(DefaultExecution.java:423)
>         at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:225)
>         at ratpack.exec.internal.DefaultExecution.intercept(DefaultExecution.java:218)
>         at ratpack.exec.internal.DefaultExecution.drain(DefaultExecution.java:198)
>         at ratpack.exec.internal.DefaultExecution.<init>(DefaultExecution.java:94)
>         at ratpack.exec.internal.DefaultExecController$1.lambda$start$0(DefaultExecController.java:195)
>         at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
>         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
>         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
>         at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExecController.java:136)
>         at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
>         at java.lang.Thread.run(Thread.java:748)

**Comment by johnrengelman** [comment]
This is because the Ratpack <-> Retrofit adapter is _always_ looking for a `Context` object to get a handle on the underlying `HttpClient` instance (https://github.com/ratpack/ratpack/blob/master/ratpack-retrofit2/src/main/java/ratpack/retrofit/internal/RatpackCallFactory.java#L81-L86)

This code should probably look in the the `execution` for a `HttpClient` directly first, then fallback to getting the `Context`. This would allow a developer to add a `HttpClient` instance to the execution registry.

Would also be good to add some sugar to`RatpackRetrofit` to create a retrofit client with a provided `HttpClient` implementation backing it.

**Comment by johnrengelman** [comment]
This was addressed in https://github.com/ratpack/ratpack/commit/3a5c45737d6318a27ab9db18bf8037d11788abb2 which allows `RatpackRetrofit` to get it's `HttpClient` from the current `Execution`

**Comment by johnrengelman** [comment]
This will be in the 1.6 release.
