### ISSUE TITLE
function inside Promise.replace() is invoked even when upstream promise fails.

### ISSUE THREAD

**Issue by ankur4u007** [ratpack/ratpack#1236]
Which library : `` ratpack-core-1.4.6.jar``
What : According to the documentation of replace method in Promise `` This is simply a more convenient form of {@link #flatMap(Function)}, where the given promise is returned....If the upstream promise fails, its error will propagate downstream and the given promise will never be subscribed to. ``
Functions inside Promise.replace() are invoked even when the upstream promise fails. 
How to replicate ?  
Language : `` kotlin ``
``` 
import ratpack.exec.Promise

fun main(args: Array<String>) {
    var pr = Promise.error<String>(RuntimeException())
    pr.flatMap { (oneWhoShouldNotBeCalled("flatmap")) }
    pr.replace(oneWhoShouldNotBeCalled("replace"))
}

fun oneWhoShouldNotBeCalled(caller: String) : Promise<Unit> {
    print("The dark lord was summoned by " + caller)
    return Promise.value(null)
}
```
This prints : 
```
The dark lord was summoned by replace
Process finished with exit code 0
```

Observation: 
The flatMap behaves as expected and does not call the function ``oneWhoShouldNotBeCalled`` when called on an error promise, However replace ends up calling the function and prints the output. As per documentation i believe this is a bug, let me know otherwise, Thanks!

**Comment by rhart** [comment]
I don't believe there is any issue here.  The function that supplies the promise is invoked, yes, but the given promise is never subscribed to.  Which is what the documentation states.

Try changing `oneWhoShouldNotBeCalled` to

```
fun oneWhoShouldNotBeCalled(caller: String) : Promise<Unit> {
    return Promise.value(null).onYield { print("The dark lord was summoned by " + caller) }
}
```

**Comment by ldaley** [comment]
`replace()` isn't calling the function, it's called inline and its return is the promise. If you really need to defer the outer function, you can nest it with:

```
pr.replace(Promise.flatten { oneWhoShouldNotBeCalled("replace") })
```
