### ISSUE TITLE
Expose HttpClient Metrics

### ISSUE THREAD

**Issue by jeff-blaisdell** [ratpack/ratpack#1244]
### Problem
When using Ratpack's HttClient with sufficient traffic the cost of creating new connections becomes too expensive, and requires a switch to connection pooling mechanisms.  Connection pooling helps alleviate the connection creation cost, but requires monitoring / tuning.  Currently, Ratpack's HttpClient doesn't expose any hooks for a developer to instrument, or gain insight into the state of the underlying Netty ChannelPool.

### Request
At a minimum to be able to provide some insight into current ChannelPool usage.
* Max connection pool size
* Connections Used

### Reference Netty Http Client Metrics
* async-http-client
    * Basically implemented their own ChannelPools that keep track / expose some basic information regarding pool state.
    * [PR that added metric support](https://github.com/AsyncHttpClient/async-http-client/pull/1255)
* vert.x 
    * They built their own Metric abstraction classes, which they use heavily throughout the framework including the HttpClient code, and expose to developer.
       * Metric example in [Http2Pool.java](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/Http2Pool.java)
       * Metric example in [HttpClientImpl](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/HttpClientImpl.java#L63)
   * Supported [Http Client Metrics](http://vertx.io/docs/vertx-dropwizard-metrics/java/#_http_client_metrics)
   * Supported [Pool Metrics](http://vertx.io/docs/vertx-dropwizard-metrics/java/#_pool_metrics).  Not positive if this encompasses the HttpClient connection pools or not.

**Comment by jeff-blaisdell** [comment]
Was looking into what might be possible with current HttpClient implementation.  A simple approach might be to find a way to expose the [ChannelPoolHandler's](https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/main/java/ratpack/http/client/internal/DefaultHttpClient.java#L50).  That would provide a hook for a developer to create a metric instrumented variant.

Tradeoff is it's a more one-off mechanism for metrics, and it exposes Netty's internals to Ratpack developer.

**Comment by rhart** [comment]
We don't need to expose Netty internals, we could just expose what you want to know i.e. Max connection pool size and Connections Used.  And make available on HttpClient like async-http-client does with `getClientStats`.  This would seem the best way forward to get something available soon.

Going down the vert.x route with our own metrics abstraction in core is something @ldaley would need to weigh in on.  If we do, rather than rolling our own maybe using http://micrometer.io/ would  be something to look in to.

**Comment by jeff-blaisdell** [comment]
Sounds good.  I'll see about putting something together following the async-http-client paradigm.

**Comment by rhart** [comment]
Awesome, thanks @jeff-blaisdell

**Comment by jeff-blaisdell** [comment]
Here's a first pass:
https://github.com/ratpack/ratpack/pull/1249

**Comment by jeff-blaisdell** [comment]
Finally got a green build.  Done making changes until review.

**Comment by ctoestreich** [comment]
I have spent so much time in codahale I dream in histograms and timers.  That said, supporting the dimensional metrics and tagging, http://micrometer.io would be the prudent metrics library to transition to IMHO.

**Comment by beckje01** [comment]
@cstoestreich as the metrics right now are isolated to a module we should be able to look at doing one for micrometer. I have been hoping to spike one out but haven't had the time

**Comment by johnrengelman** [comment]
Closing this as HTTP metrics were added to the public API in 1.6.0-rc-1
