### ISSUE TITLE
Translate documentation to Groovy language

### ISSUE THREAD

**Issue by mavortius** [ratpack/ratpack#1250]
Is it possible translate all Ratpack online documentation to Groovy? I'm thinking of migrating some of the projects of the company where I work for this platform and the team is in the process of migrating the codes from some projects to Groovy language. This would make it much easier for the team to adopt Ratpack if the documentation is on Groovy language.

**Comment by ldaley** [comment]
Hi @mavortius,

This isn't something we are going to do. If we had greater resources/time, we'd provide both Java and Groovy, but providing Groovy only would alienate the larger body of Java programmers.

**Comment by mavortius** [comment]
Thank you for the answer.
