### ISSUE TITLE
How to add headers to Json renderer

### ISSUE THREAD

**Issue by nerro** [ratpack/ratpack#1255]
Hi,

I'm currently trying to build REST API for my project with ratpack and have a small question. If I render with `ctx::render` an json object, then I have no header except `content-type` and `transfer-enconding`. My handler looks so:

```java
public class UserEndpoints implements Action<Chain> {
  ...
  @Override
  public void execute(Chain chain) throws Exception {
    chain
    ...
      .path(":id", ctx -> {
        final Long userId = Long.parseLong(ctx.getPathTokens().get("id"));
        ctx.byMethod(methodSpec ->
          methodSpec
            .get(() -> {
              UserCache userCache = ctx.get(UserCache.class);
              Promise<User> user = userCache.getIfPresent(userId);
              user.onNull(() -> ctx.clientError(404))
                  .map(Jackson::json).then(ctx::render);
            }));
      });
  }
}
```

I read and found some articles (e.g. https://blog.couchbase.com/crud-rest-api-couchbase-rxjava-ratpack) Do I understand correctly that I need custom renderer that add missing headers?

Thanks for advice.

**Comment by rhart** [comment]
You can add response headers anywhere before you make a call to `render` e.g. `ctx.getResponse().getHeaders().add("foo", "bar")`

**Comment by nerro** [comment]
it's true, but I hope that I don't have to calculate e.g. `content-length` or `connection` headers.

p.s. thanks for quick answer. perhaps there is another way with renderer too?

**Comment by rhart** [comment]
These kind of headers are added for you by Ratpack.  If you're expecting a content-length header and only seeing transfer-encoding then this is likely because the client is sending an accept-encoding header of gzip.

**Comment by nerro** [comment]
@rhart, thanks for pointing me to `accept-encoding` header. If I set it to `br` or `identity`, then it works.

p.s. from my side the issue is closed.
p.p.s. my question was really fast answered :+1:

**Comment by nerro** [comment]
@rhart, I found today another solution too. I added a new handler before all handlers and call `ctx.getResponse().noCompress()`. After that `content-length` will be added always. I guess that no compressing will be applied and all headers will be added?

```java
public class CommonHeaders implements Handler {

  @Override
  public void handle(Context ctx) throws Exception {
    ctx.getResponse().noCompress();
    ctx.getResponse().getHeaders()
       .add("Server", "Customizer")
    ctx.next();
  }
}

// this code is in main class where all handlers defined
...
.handlers(chain -> chain
  .all(new CommonHeaders())
...
```

**Comment by rhart** [comment]
Yes, I believe that works.

Out of interest, why are you trying to avoid compression?

**Comment by nerro** [comment]
Take part in the competition (https://highloadcup.ru, build an highload application :smiley:) and think that ratpack suits perfect for it.

The parser on their side checks for certain headers: `content-length`, `content-type` and `server`.

p.s. results will be anounced on 1. September. If you want I can publish my results. It's kind of like a real benchmark.

**Comment by rhart** [comment]
Cool :)

Well, if their client doesn't send an accept-encoding the it will not get a compressed response. But in this case, never sending a compressed response seems fine.

Please let us know how you get on.  You should join the slack channel http://slack-signup.ratpack.io/
