### ISSUE TITLE
Shutting down via Runtime.shutdownHook

### ISSUE THREAD

**Issue by pawel-kaminski-krk** [ratpack/ratpack#1268]
can you add configuration for ratpack.server.internal.DefaultRatpackServer so start method is not adding shutdown hook. It could be just a system property with current behavior as default.

I need have better control over starting and stopping the server. Right now server is shutting down itself before other services close. Or maybe there is something I can use?

**Comment by ldaley** [comment]
@pawel-kaminski-krk what do you mean by “other services” here? `ratpack.service.Service` or something else?

**Comment by pawel-kaminski-krk** [comment]
I have environment where multiple threads are talking via clients to ratpack's server. and when main process shuts down ratpack closes itself without any control over that processes and I get lots of exceptions from clients that they cannot reach server :/ 

anyway I think that adding configuration to such behavior cannot harm.

**Comment by ldaley** [comment]
The change you're asking for isn't going to help you. Once the JVM starts shutdown it is practically unusable. 

The way to coordinate startup/shutdown in Ratpack is via `Service` implementations in the application registry. Ratpack will not start serving requests until all services have started, and it will shutdown all services when it is shutting down (including on process termination). 

So, you need to work out how to signal to your clients that the system is going down, do that from a service shutdown callback, and possibly consider waiting on all active requests to finish before returning from the shutdown callback.

**Comment by pawel-kaminski-krk** [comment]
but all this communication is within same JVM, so I have full control what is going on except ratpack as it shuts down itself. 

Or I dont understand what do you mean by 

> The change you're asking for isn't going to help you. Once the JVM starts shutdown it is practically unusable.

when my app is starting I am registering ```Runtime.getRuntime().addShutdownHook(my-app-hook)``` and ratpack is registering its. I have all references to my clients and to ratpack so I can shut clients down first and then ratpack the same way you are doing - I don't see any problem here.

right now there is a race condition between my-shut-down-hook (SDH) and your-SDH. Am I missing something here?

**Comment by pawel-kaminski-krk** [comment]
to make it clear - my problem is that there is a race condition between my shutdown logic and ratpack's.

**Comment by ldaley** [comment]
I did not pick up that your “clients” were in the same process.

What else does your shutdown logic have to do? A solution that would work today is just moving that logic to a Ratpack `Service`.

**Comment by pawel-kaminski-krk** [comment]
:] oook. No, this is not a workaround. They need to stay independent. The workaround is to let user to decide whether ratpack should shutdown itself or not. This is not much work - I did quikck investigation, so I could be wrong.

I can make a pull request with the fix If you promise to include it and release it :D .. I think current behavior should be default and I would add new field to ```ServerConfig.builder()``` and then read the value in ```ratpack.server.internal.DefaultRatpackServer.start()```. As this is the only implementation of RatpackServer interface - TestSertver has no logic.

**Comment by pawel-kaminski-krk** [comment]
If I am allowed to make PR

**Comment by ldaley** [comment]
Making it part of the server config is reasonable. If you submit a PR with that change, I will almost certainly merge it. There's no schedule release date for 1.6 at this time. It's likely to be at least a month or two away.

FWIW, your definition of “workaround” isn't conventional. A workaround is a way to negate a defect or deficiency in a system without changing that system.

**Comment by pawel-kaminski-krk** [comment]
yeah I know :) but this will bring more trouble to the system I am building. 

Great. I will implement and test my change and use forked version till new release - I just don't want situation where I have to fork each new release.

**Comment by ldaley** [comment]
Great, looking forward to it. Thanks.

**Comment by pawel-kaminski-krk** [comment]
I need help, I cannot find it in your README files. I cannot push to my own branch - no permissions. How should I create a pull request. should I push to existing branch???

**Comment by ldaley** [comment]
Typically you would fork the project an push to a branch on your fork.

**Comment by pawel-kaminski-krk** [comment]
https://github.com/ratpack/ratpack/pull/1269 hope it makes any sense :) anyway it works in my app as expected.

**Comment by pawel-kaminski-krk** [comment]
@ldaley any news on merging my PR? :-)

**Comment by ldaley** [comment]
Merged. Thank you for your patience.
