### ISSUE TITLE
1.5.0 version java.lang.NoClassDefFoundError: ratpack/func/Function

### ISSUE THREAD

**Issue by fleaLi** [ratpack/ratpack#1272]
Caught: java.lang.NoClassDefFoundError: ratpack/func/Function
java.lang.NoClassDefFoundError: ratpack/func/Function

**Comment by johnrengelman** [comment]
@fleaLi we are going to need more information than just this. How are you building your application? What's the code that is erroring?

**Comment by ldaley** [comment]
This class was moved into the `ratpack-base` module I believe (which core depends on). For whatever reason, this JAR isn't on your classpath.
