### ISSUE TITLE
Question for HttpReadTimeOutException handling.

### ISSUE THREAD

**Issue by Vincent-bin** [ratpack/ratpack#1276]
`   
 @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
      cause = decorateException(cause);

      if (write == null) {
        error(downstream, cause);
      } else {
        write.error(cause);
      }

      forceDispose(ctx.pipeline());
    }
`
When use httpClient.requestStream(), if ReadTimeOutException occurs  during response streaming instead of before the first chunk of response come back. 

because "writer!=null", then "write.error(cause)" will be executed.

`      
@Override
public void onError(Throwable t) {
        if (t == null) {
          throw new NullPointerException("error is null");
        }
        LOGGER.warn("Exception thrown transmitting stream", t);
        if (done.compareAndSet(false, true)) {
          channel.closeFuture().removeListener(cancelOnCloseListener);
          post(responseStatus);
        }
      }
`
the responseStatus is "200 OK", is this expected?

**Comment by ldaley** [comment]
Hi @Vincent-bin ,

Yes this expected. If the timeout occurs before the server sends headers, then the promise for the `StreamedResponse` will fail with the timeout. If the timeout occurs after headers are sent, the timeout propagates through the body reading stream.
