### ISSUE TITLE
Promote HttpClientMetrics into public API

### ISSUE THREAD

**Issue by johnrengelman** [ratpack/ratpack#1312]
Promote the API added in https://github.com/ratpack/ratpack/pull/1249 to public facing and incorporate any changes necessary from real production usage.

/cc @jeff-blaisdell

**Comment by michaelschlies** [comment]
@johnrengelman understanding the changes needed for this issue may be two-fold, do I understand the intent to be:

1. move ratpack.dropwizard.metrics.internal.HttpClientMetrics to ratpack.dropwizard.metrics

1. Validate and coordinate with @jeff-blaisdell to see if any production use changes came out of it and ensure these changes are incorporated (along with any required test changes).

Thanks

**Comment by johnrengelman** [comment]
I believe this was all address here: https://github.com/ratpack/ratpack/commit/48a6294e3b9bc6067b6f530d1d9b060e467b33e6
