### ISSUE TITLE
Check for null content-type on on Retrofit request

### ISSUE THREAD

**Issue by johnrengelman** [ratpack/ratpack#1316]
When Retrofit uses an empty body (i.e. a POST with no body), then the `request` is non-null, but `contentType()` returns a `null`.

Need to pre-emptively check for the existence of the contentType before trying to pass it on to the Ratpack HttpClient.

https://github.com/ratpack/ratpack/blob/master/ratpack-retrofit2/src/main/java/ratpack/retrofit/internal/RatpackCallFactory.java#L112

**Comment by beckje01** [comment]
Merged in #1338
