### ISSUE TITLE
Upgrade to Thymeleaf3

### ISSUE THREAD

**Issue by minebreaker-tf** [ratpack/ratpack#1318]
I want to use Ratpack with Thymeleaf version 3.

`IFragmentSpec` is removed, so this would be binary-incompatible change.
Thus I think it's better to create another 'ratpack-thymeleaf3' module.

I created the implementation on my own fork.
[https://github.com/minebreaker-tf/ratpack/tree/thymeleaf3](https://github.com/minebreaker-tf/ratpack/tree/thymeleaf3)

If you want, I'd love to send pull request.

(I'm not a good English speaker, I'm sorry if you had any inconvenience.)

**Comment by beckje01** [comment]
That looks like a good plan are you still interested in opening a PR? Otherwise I can pull in your module.

**Comment by minebreaker-tf** [comment]
I created the PR but it seems failing... #1341 

The ratpack-manual task which requires all child modules seems failing the build with a dependency conflict between thymeleaf 2 and 3.

Looks like it is necessary to drop support for old thymeleaf, or completely change the build process.

Feel free to close my PR if you don't think that is a good idea.

**Comment by johnrengelman** [comment]
The PR for adding the Rx2 module fixes the dependency issue by moving the JavaScript tests into their respective modules instead of pulling everything into the ratpack-manual project.

**Comment by johnrengelman** [comment]
@beckje01 after merging that, we’ll just need to add a copy of JavaScript test spec that needs to be in every module to this.

**Comment by beckje01** [comment]
@johnrengelman yeah I added a few tests to rx2 I'll merge that and take on rebasing this new pr

**Comment by beckje01** [comment]
This is in 1.6 now.
