### ISSUE TITLE
Websockets support

### ISSUE THREAD

**Issue by tomaslin** [ratpack/ratpack#133]
It would be nice to be able to enable websockets within ratpack. 

This could probably be done by specifying a flag within the launchConfig of the application. 

There is a fairly good example of a SimpleChannelInboundHandler that is websocket aware within netty src - 

https://github.com/netty/netty/blob/master/example/src/main/java/io/netty/example/http/websocketx/server/WebSocketServerHandler.java 

Enabling websocket ping and close requests would would be a matter of changing the NettyHandlerAdapter within ratpack core to allow both FullHttpRequest and WebSocketFrame. 

The main question here would be how would handler syntax and the ratpack context be different with web sockets.

**Comment by niwibe** [comment]
It seems already merged some time ago, maybe this issue should be closed.

**Comment by alkemist** [comment]
You're right. There's some stuff there, but it's not very good.

We should close this though and open specific tickets for improved support.
