### ISSUE TITLE
Installation (offline) for ratpack and usage

### ISSUE THREAD

**Issue by lchunleo** [ratpack/ratpack#1345]
hi,
 am new to ratpack. Is it possible to run ratpack without internet connectivity?

 i had installed Java and Groovy and tested running ok and had download the ratpack 1.5.4. I had obtained a simple hello world file and run groovy app.groovy, however errors such as "java.io.FileNotfound exception" is raised. Is it true that ratpack need gradle and internet connectivity to install? i am working with an offline machine. thanks

**Comment by lchunleo** [comment]
Do I need to have @Grab (io.ratpack:ratpack-groovy:1.5.4') ?Where does it look for the dependencies? Am confused pls advise. Unable to get a simple hello world to work

**Comment by johnrengelman** [comment]
Yes. Internet is required the first time you run a groovy script that uses ‘@Grab’. That annotation is what manages the dependency downloads and adds them to the classoath of the groovy shell to execute. 
See here - http://docs.groovy-lang.org/latest/html/documentation/grape.html

Once you’ve done this, the dependencies should be in groovy’s cache.

**Comment by johnrengelman** [comment]
I believe what you are looking for is in this section - http://docs.groovy-lang.org/latest/html/documentation/grape.html#Grape-Advancedconfiguration where you can specify the download directory. You could do this in a machine that has connectivity and then copy the resulting directory to the offline machine.

**Comment by johnrengelman** [comment]
I’m going to close this issue as this is not the appropriate forum (this is the bug tracker for the project itself). I suggest searching stackoverflow for posts related to offline groovy shell (there is nothing special about Ratpack in this respect, it’s just a dependency).
