### ISSUE TITLE
only one of multiple cookie headers is read

### ISSUE THREAD

**Issue by Jimmy-Shi** [ratpack/ratpack#1349]
https://github.com/ratpack/ratpack/blob/9db5696f96ce695f00d9a6b5d4812a2f152ae173/ratpack-core/src/main/java/ratpack/http/internal/DefaultRequest.java#L207

As documented in https://tools.ietf.org/html/rfc2616#section-4.2, multiple headers with name "cookie" should be supported

> Multiple message-header fields with the same field-name MAY be
   present in a message if and only if the entire field-value for that
   header field is defined as a comma-separated list [i.e., #(values)].
   It MUST be possible to combine the multiple header fields into one
   "field-name: field-value" pair, without changing the semantics of the
   message, by appending each subsequent field-value to the first, each
   separated by a comma.

**Comment by jansyk13** [comment]
@Jimmy-Shi According to RFC 6265 this is implemented correctly.

```
When the user agent generates an HTTP request, the user agent MUST 
NOT attach more than one Cookie header field.
```

https://tools.ietf.org/html/rfc6265#section-5.4

**Comment by johnrengelman** [comment]
@beckje01 I believe this one can be closed as no issue per RFC625 above
