### ISSUE TITLE
Caching promise do not works when flatmapping promise chain

### ISSUE THREAD

**Issue by pankajagrawal16** [ratpack/ratpack#1363]
I dont seem to understand if its a expected behaviour or a known issue or if found a issue now.

So i have a sample code like this :

 ```
Promise<Account> samplePromise = mapper.promise1(data, data1)
                    .flatMap(data -> promise2(data)
                            .map(data -> mapResult(data))
                            .cacheResultIf(shouldCache())
                            .wiretap(invalidateIfThingsFail()));
````
When i write things like this, it seems `cacheResultIf`do not works and donot caches the promise as i can see that promise 2 evaluates every-time for each request.. but as soon as I move it to be the last thing in the chain .. it seems it caches things
so this works

```
Promise<Account> samplePromise = mapper.promise1(data, data1)
                    .flatMap(data -> promise2(data)
                            .map(data -> mapResult(data))
                           .wiretap(invalidateIfThingsFail()))
                           .cacheResultIf(shouldCache());
```

Also an observation is that if there is no flat mapping going on in promise chain and if its a simple single promise chain, then the order of `cacheResultIf` donot matters and it works .. (edited)
Also note that this observation is not specific to `cacheResultIf`, but is in general all all caching api on promise . Anything we know about it already?

**Comment by ldaley** [comment]
This is expected behaviour. Caching only caches the computations that precede it. If you have anything after it, it will be executed each time.
