### ISSUE TITLE
Missing method when reference private method inside Blocking.get

### ISSUE THREAD

**Issue by eric1989** [ratpack/ratpack#1370]
The code below throws a Missing method getTotal exception. If I use public, it works fine. 
Any ideas? thank you

`class OrderService {
    @Override
    Promise<A> getOrder(String locationId, String id, String status,
                                                Timestamp start = new Timestamp(0),
                                                Timestamp end = new Timestamp(clock.millis())) {
        Blocking.get {
            List<Order> orderResult = ordersRepo.
                    findStoreOrders(locationId, id, status, start, end)
            if (orders == null || orders.size() == 0) {
                throw new ResourceNotFoundException("Cannot find orders")
            }
            def orderResult = []
            def result = new A()
            result.orders = orderResult
            result.totalQuantity = getTotal(storeOrders)
            result
        }
    }
     private int getTotal(List<Order> orders) {
        orders.stream().mapToInt { x -> x.quantity }.sum()
    }
}`

**Comment by johnrengelman** [comment]
This is an issue in groovy that is documented in a number of places - https://gangmax.me/blog/2014/12/26/groovy-closure-gets-missingmethodexception-when-accessing-private-methods-in-super-class/
