### ISSUE TITLE
Interaction with CompletableFuture

### ISSUE THREAD

**Issue by anvar3** [ratpack/ratpack#1390]
Hi,

This is more a question than a bug so apologies if this doesn't belong here. I have tried to look in the code and elsewhere but I could not find a definitive answer on how to convert a `ratpack.Promise` to a Java `CompletableFuture` and back. The main reason for asking is that we're using a library that is async and returns `CompletableFuture` and I would like to tie it in with the Ratpack execution model.

Many thanks!

**Comment by beckje01** [comment]
Converting to the promise you can use https://ratpack.io/manual/current/api/ratpack/exec/Downstream.html#accept-java.util.concurrent.CompletionStage- 

```java
return Promise.of(downstream -> {
  CompletableFuture completableFuture = externalLib.doAsyncThing(); //Do the call to get the future
  downstream.accept(completableFuture);
});
```

What is the flow where you want to convert back?

**Comment by johnrengelman** [comment]
Added here - https://github.com/ratpack/ratpack/pull/1399
