### ISSUE TITLE
ratpack-pac4j: possible to refresh user profile?

### ISSUE THREAD

**Issue by glasser** [ratpack/ratpack#1391]
I'm looking to port a Ratpack app with a hand-rolled GitHub OAuth login implementation to use ratpack-pac4j so that we can more easily add other identity providers.

In our current app, we care about making sure that the user profile we pull from GitHub is up to date, so we re-ping the GitHub user API (in the server) if it's staler than 30 minutes.

This is the equivalent of calling pac4j's `client.getUserProfile()`.

I'm trying to understand how to do the equivalent with ratpack-pac4j. While I can get the `Client` from the Ratpack context and call `client.getUserProfile()` manually, I'm not super clear on what I should do next — manually call `sessionData.set(Pac4jSessionKeys.USER_PROFILE, profile)` and also insert it into the current Context?

I think what I really want is a hook to get `RatpackPac4j.login` (and things that call it like `requireAuth`) to check the UserProfile they found, and re-create it (using the access token stored in the profile itself) if it's too old.

(a) Is there a mechanism already in the code that would let me do this that I'm missing?
(b) Would this project take a PR that adds such a mechanism as a generic maybe-refresh-user-profile hook?
(c) Or more specifically for a "expiration timeout" on UserProfiles?

**Comment by glasser** [comment]
BTW, while the pac4j CommonProfile class does has a method `isExpired`, this isn't super relevant for two reasons:

(1) That method is only used by the pac4j ProfileManager class, which is only used by the DefaultCallbackLogic/DefaultSecurityLogic/DefaultLogoutLogic pac4j classes, which ratpack-pac4j appears to avoid using.  (This is actually probably a bug which means that the OpenID Connect "expireSessionWithToken" preference isn't supported by ratpack-pac4j.)

(2) Even in the Default*Logic classes, this doesn't quite implement what I want. It just fully logs out the client when the profile expires, rather than trying to refresh the profile in the background.

**Comment by beckje01** [comment]
Sorry it seems you are trying to dig pretty deep into the github pac4j  it might make sense to ask the question over on the pac4j side they have a much better understanding of the integration.

**Comment by glasser** [comment]
Yeah, but there isn't actually any logic changes in the updated version, just some changed names due to upgrade.

**Comment by glasser** [comment]
Asked over at https://groups.google.com/forum/?fromgroups#!topic/pac4j-users/F9WJTlDmp3g

**Comment by michaelschlies** [comment]
@beckje01 @johnrengelman I believe we can close this issue as we have deprecated our module. If the issue still exists @glasser could reopen in pac4j/pac4j-ratpack
