### ISSUE TITLE
Add method to ParallelBatch for executing code in each forked execution before work has been done.

### ISSUE THREAD

**Issue by tsaude** [ratpack/ratpack#1432]
### Problem
When ParallelBatch forks executions, the new executions lose information that the parent execution had.  Most of these problems can be solved using the execInit method (e.g. adding the Context onto the Execution).  However, for setup that needs to be run inside the forked Execution (e.g. [copying over MDC logging values](https://github.com/ratpack/ratpack/blob/05c20b1976a6e8cc4557dc2b101aa28d41690dcf/ratpack-core/src/main/java/ratpack/logging/MDCInterceptor.java#L97-L99)), no clean solution exists (`execInit` runs in parent Execution).

### Proposal
Add a new method to ParallelBatch called `onExecStart` that behaves similarly to `execInit`, but instead runs a code block at the start of each Promise running in it's own forked execution.

```java
  /**
   * Specifies a block of code that will be executed in each forked execution before any work has been done.
   * <p>
   * This can be used to copy over values to the forked execution (e.g. the MDC logging context).
   *
   * @param onExecStart the function to execute
   * @return a new batch, configured to use the given onExecStart block
   */
  ParallelBatch<T> onExecStart(Block onExecStart);
```

**Comment by beckje01** [comment]
There is [ExecInitializer](https://ratpack.io/manual/current/api/index.html?ratpack/exec/ExecInitializer.html) that can be used to setup executions. 

Outside of MDC do you have other problem cases?

**Comment by Tsaude** [comment]
Not that I can think of / have ran into - but since that is the documented way to solve the MDC issues, having a nice way to hook into that in ParallelBatch would be useful.

Otherwise, the solutions I could think of were pretty heavy-handed - essentially re-buildling a ParallelBatch or mucking with your list of Promises to the code before they get executed.  Totally open to suggestions for solving this problem with the existing codebase however.

**Comment by drmaas** [comment]
@beckje01 @Tsaude I think it is useful to be able to run initialization code both `before` the child execution starts (parent execution is the currently running execution) and `after` the  child execution starts (child execution is the currently running execution). I think naming the method and documenting is important in making this distinction clear.

**Comment by ldaley** [comment]
I'm reluctant to grow the API for this use case. I think the general case of wanting to propagate MDC deserves special consideration.

If you want to do this now, you can just prefix each of the batch promises with `onYield()`.

**Comment by johnrengelman** [comment]
This has been sitting out there for a while, but isn't this proposal this same as `onYield(Runnable)` as Luke stated? Can we close this out?

**Comment by durkpolish** [comment]
Hi this very helpful setting in which get secure you network and give your data secure so here is apk files for you [zanti apk download](https://www.myapklab.com/zanti-apk/)

**Comment by tsaude** [comment]
Makes sense to me - if there's already a way to handle it using the current API, then sweet. Closing.
