### ISSUE TITLE
Getting from and setting a client side session in the same request duplicates last access cookie

### ISSUE THREAD

**Issue by timyates** [ratpack/ratpack#1434]
Hi all,

When getting and setting from the session in the same request, we end up with duplicate `lat` cookies set in the response.

Here's a working example (obviously in the real world the get and set are further apart in code) 😉

```
import ratpack.groovy.template.MarkupTemplateModule
import ratpack.session.Session
import ratpack.session.SessionModule
import ratpack.session.clientside.ClientSideSessionModule
import static ratpack.groovy.Groovy.groovyMarkupTemplate
import static ratpack.groovy.Groovy.ratpack

ratpack {
  bindings {
    module MarkupTemplateModule
 		module SessionModule
    module(ClientSideSessionModule) { config ->
      config.sessionCookieName = "test_session"
    }
  }

  handlers {
    get { Session session ->
      // get an item out of the session
      session.get('test').flatMap {
        // Then later, set it to something else
        session.set('test', System.currentTimeMillis()).promise()
      }.then {
        render groovyMarkupTemplate("index.gtpl", title: "My Ratpack App")
      }
    }

    files { dir "public" }
  }
}
```

Going to localhost:5050 results in the page as expected, but the response headers have two last access time cookies being set

```
HTTP/1.1 200 OK
content-type: text/html;charset=UTF-8
set-cookie: test_session_0=rO0ABXNyADZyYXRwYWNrLnNlc3Npb24uaW50ZXJuYWwuRGVmYXVsdFNlc3Npb24kU2VyaWFsaXplZEZvcm0AAAAAAAAAAgwAAHhwd3IAAQABAQAEdGVzdAEADmphdmEubGFuZy5Mb25nAAAAUqztAAVzcgAOamF2YS5sYW5nLkxvbmc7i+SQzI8j3wIAAUoABXZhbHVleHIAEGphdmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAABaFzy3Vx4:L2qgaaDHAgyIkn3c+cUqeFT5E4Q=; Path=/; HTTPOnly
set-cookie: ratpack_lat_0=AAABaFzy3Vk=:M95oByToxVjsZeFvWfiu05rOEEQ=; Path=/; HTTPOnly
set-cookie: ratpack_lat_0=AAABaFzy3hM=:h8wzo8Zu5Mz8jKye42Kb3BiwO9I=; Path=/; HTTPOnly
content-encoding: gzip
transfer-encoding: chunked
```

This isn't an issue in itself, but the RFC for cookies is vague about how browsers are meant to handle this, and it gets flagged up as an issue by web-security tools.

**Comment by johnrengelman** [comment]
This happens because of this line: https://github.com/ratpack/ratpack/blob/master/ratpack-session/src/main/java/ratpack/session/clientside/internal/ClientSideSessionStore.java#L327 which adds a new cookie to the set of cookies on the response. The set evaluates the cookie using the name, path, and domain in the comparison. In this cause, adding the new cookie on this line doesn't match the existing cookie that has the path set, so it's added and then has its path modified.
