### ISSUE TITLE
Link to Documentation on https://ratpack.io/ is broken

### ISSUE THREAD

**Issue by swartzrock** [ratpack/ratpack#1468]
**Steps**

1. Head to https://ratpack.io/ 
2. Click the big Documentation link

**Results** Page Not Found.

**Comment by johnrengelman** [comment]
This appears to be an issue with Heroku rejecting our setting of `1.8` for the Java version (which was working 5 days ago). I've opened a support ticket with them.

**Comment by johnrengelman** [comment]
This is now fixed and the link is now working.
