### ISSUE TITLE
HTTPS setup for Ratpack API 

### ISSUE THREAD

**Issue by mallikannasagaram** [ratpack/ratpack#1480]
I have an Ratpack API running in VM servicing http requests. I would like to convert it to server https requests. I am not using Tomcat or Spring. It is a pure Ratpack application. Could you please let me know the way of converting this APP to accept HTTPs requests? 
Thanks

**Comment by michaelschlies** [comment]
I'm not sure if you are using Java or Groovy, but long story short, there is an ssl method on `ServerConfigBuilder` that takes a Netty `SSLContext` and that's it. 
https://ratpack.io/manual/current/api/ratpack/server/ServerConfigBuilder.html#ssl-io.netty.handler.ssl.SslContext-

**Comment by michaelschlies** [comment]
@mallikannasagaram Let me know if you're having any issues with this, but https://netty.io/4.0/api/io/netty/handler/ssl/SslContextBuilder.html should help creating the `SslContext` object

**Comment by johnrengelman** [comment]
Closing this user question as the answer has been provided and there has been no additional followup.
