### ISSUE TITLE
Update Gradle plugin to use new configurations

### ISSUE THREAD

**Issue by lptr** [ratpack/ratpack#1488]
Ratpack's Gradle plugin uses configuration names like `compile` and `testRuntime` that have now been deprecated. It should use the new configuration names like `implementation` and `testRuntimeOnly` etc. instead.

**Comment by lptr** [comment]
IIUC the only change needed is to update these names:

https://github.com/ratpack/ratpack/blob/d18284540db57a6acd4c1aade0ead7dcd48ca30f/ratpack-gradle/src/main/groovy/ratpack/gradle/RatpackPlugin.groovy#L64-L67

That said, Ratpack's own build could be upgraded to use the new configurations, which is a bigger undertaking.

**Comment by ljacomet** [comment]
There is a matching RatpackGroovyPlugin.groovy that needs a similar update.
