### ISSUE TITLE
Provide way to pass cookies in TestHttpClient

### ISSUE THREAD

**Issue by urielsalis** [ratpack/ratpack#1519]
Provide way to pass cookies in TestHttpClient

For some of our tests we need to pass authentication cookies instead of headers, but trying to set a cookie with the header does not work as TestHttpClient overrides it with a empty cookie header when doing the request

**Comment by jsalinaspolo** [comment]
Could you provide some code because might be an issue in the implementation you might be doing

There is an example here
```
 ReceivedResponse response = httpClient
       .requestSpec(requestSpec -> requestSpec
         .getHeaders()
         .set("Cookie", "username=hbogart1"))
       .get();
```

https://ratpack.io/manual/current/all.html#1.6.7%20Cookies%20from%20an%20inbound%20request
