### ISSUE TITLE
Supporting JDK 15

### ISSUE THREAD

**Issue by tmarble** [ratpack/ratpack#1574]
For my Ratpack application I would like to use JDK 15, but there is a dependency on Guice 4.1.0
* https://ratpack.io/manual/current/guice.html#google_guice_integration

but Guice only begins to support JDK 15 in 5.0.0-BETA-1
* https://github.com/google/guice/wiki/Guice500

While it may be possible to "force" a newer version on the classpath I suspect this would not work properly.

I realize that dependency updates are currently planned for 2.0.0
* https://ratpack.io/versions/2.0.0
* https://github.com/ratpack/ratpack/pull/1558

Wondering if anyone has considered pulling the dependency updates into 1.8.1?
* https://ratpack.io/versions/1.8.1

I will note that achieving JDK 15 compatibility is distinct from deprecating older versions, as in  https://github.com/ratpack/ratpack/issues/1387

For reference there may transitive dependency issues with other components (these versions should support JDK 15)
* groovy 3.0.7 http://groovy-lang.org/releasenotes/groovy-3.0.html
* gradle 6.7.1 https://docs.gradle.org/6.7.1/release-notes.html
* lombok 1.18.16 https://github.com/rzwitserloot/lombok/releases
* gradle-lombok v4.0.0 https://github.com/franzbecker/gradle-lombok/releases
* spock 2.0-M4-groovy-3.0 (requires groovy 3) http://spockframework.org/spock/docs/2.0-M4/release_notes.html
* guava 30.1-jre https://github.com/google/guava/releases

Thoughts?

**Comment by ldaley** [comment]
@tmarble we'd have to assess the extent of the incompatible changes in those upgrades. I'm also reluctant to ship a dependency on a beta version. 

I suggest trying by upgrading your dependencies for your application first. If Ratpack's usage of those libs remains compatible (of which there are no guarantees) it should work.
