### ISSUE TITLE
Can't access current manual via main web page

### ISSUE THREAD

**Issue by pivovarit** [ratpack/ratpack#1580]
Clicking on:

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/2182533/106104118-49deb500-6142-11eb-86be-926c7ac01556.png">

and:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/2182533/106104139-519e5980-6142-11eb-861f-1a4098e3b5e6.png">

Leads to nowhere - https://ratpack.io/manual/current

<img width="396" alt="image" src="https://user-images.githubusercontent.com/2182533/106104186-61b63900-6142-11eb-9c2f-c1d06b1da594.png">

**Comment by johnrengelman** [comment]
Thanks. We missed publishing the latest manual to the site. This is now fixed.
