### ISSUE TITLE
Support for Server Name Indication (TLS) on the server

### ISSUE THREAD

**Issue by schaefec** [ratpack/ratpack#1627]
I saw that SNI on the client is supported:

"
Ratpack's HTTP client now supports SSL connections leveraging SNI. No extra config is required.
"

Is there a way to configure the server side to support SNI so that the ServerHello returns different certificates based on ClientHello's hostname set as SNI?

**Comment by johnrengelman** [comment]
Hi @schaefec - the Ratpack server doesn't currently support multiple SSL certificates via SNI as it only allows passing a single SslContext (https://ratpack.io/manual/current/api/ratpack/server/ServerConfigBuilder.html#ssl(io.netty.handler.ssl.SslContext))

Netty does have a handle to support SNI (https://netty.io/4.1/api/io/netty/handler/ssl/SniHandler.html) and I'll mark this to take a look at adding the support in a future version. The biggest effort is how to expose this via configuration.

**Comment by schaefec** [comment]
Thanks a lot for looking into this for a future version
