### ISSUE TITLE
Add support for HTTP Proxy Authentication

### ISSUE THREAD

**Issue by jthurne** [ratpack/ratpack#1652]
Ratpack has support for HTTP proxies, but not for HTTP proxies which require authentication. Netty has support for proxy authentication, so this should be as easy as adding username and password properties to ProxySpec and passing them to Netty's HttpProxyHandler if they are present.

Basic authentication is the primary method of authentication used by HTTP proxies (and this is what Netty supports). Other forms of authentication do not need to be supported.

**Comment by jthurne** [comment]
Pull request: #1653

**Comment by davidmc24** [comment]
Added via #1653
