### ISSUE TITLE
1.x docs are not discoverable on the docs site

### ISSUE THREAD

**Issue by jonatan-ivanov** [ratpack/ratpack#1657]
The only version that you can find by navigating through links is the latest 2.x (`2.0.0-rc-1` as of today). The latest stable version (1.9.0) is not discoverable (I'm not sure if this is intentional though, see below).

People might be able to find older docs by guessing the url (https://ratpack.io/manual/1.9.0/all.html) or using web.archive.org but finding them this way is sub-optimal.

It is also unclear which version is recommended (in production). It seems that the current stable/GA release (`1.9.0`) depends on a very old version of Spring Boot (https://github.com/ratpack/ratpack/issues/1655) so that I would not use it in prod and the version that depends on a newer version of Boot (`2.0.0-rc-1` which is somewhat outdated too (https://github.com/ratpack/ratpack/issues/1656)) is not stable/GA yet.

**Comment by johnrengelman** [comment]
On the main site, click "Releases" which lands you on a page with all versions and on each of those pages is a link to the associated documentation and manual.

**Comment by jonatan-ivanov** [comment]
Got it, thank you!
I still think this is very hard to discover for the users who are new to the project and do not know where to find these links (like me). Maybe it is just me though, I did not think to look for the User Guide in the release notes in the first place and I think it is not easy to find it on a page that is somewhat big ([like this](https://ratpack.io/versions/2.0.0-rc-1)).
