### ISSUE TITLE
Multiple HTTP verbs with same url

### ISSUE THREAD

**Issue by ruXlab** [ratpack/ratpack#197]
Seems broken. It's handle only first declared verb and produces 405 error "Method Not Allowed" on others

```
  post('boo') { response.send "booo posted"  }
  delete('boo') { response.send "booo deleted"  }
  get('boo') { response.send "booo getted"  }
```

And test it using curl

**POST**

```
✗ curl -i -X POST http://localhost:5050/boo
HTTP/1.1 200 OK
Content-Type: text/plain;charset=UTF-8
Content-Length: 11
Connection: keep-alive

booo posted%
```

**DELETE**

```
✗ curl -i -X DELETE http://localhost:5050/boo
HTTP/1.1 405 Method Not Allowed
Content-Type: text/html;charset=UTF-8
Content-Length: 1050
Connection: keep-alive

<!DOCTYPE html>
<html>
<head>
    <title>Method Not Allowed</title>
    <style type="text/css">
...
```

and even **GET**

```
✗ curl -i -X GET http://localhost:5050/boo
HTTP/1.1 405 Method Not Allowed
Content-Type: text/html;charset=UTF-8
Content-Length: 1047
Connection: keep-alive

<!DOCTYPE html>
<html>
<head>
    <title>Method Not Allowed</title>
    <style type="text/css">
....
```

**Comment by wholenewstrain** [comment]
I did the following and seems to be working ok ...
Is there something I should avoid?

    ratpack {
        handlers {
            get("") {
                render Paths.get("index.html")
            }
            path("production") {
                byMethod {
                    get {
                        byContent {
                            json {
                                render Production.renderJsonCollection(productionData.values())
                            }
                            xml {
                                render Production.renderXmlCollection(productionData.values())
                            }
                        }
                    }
                    post {
                        byContent {
                            json {
                                parse(ratpack.jackson.Jackson.jsonNode()).then { p ->
                                    ...
                                }
                            }
                            xml {
                                request.body.then{ b ->
                                    ..
                                    new XmlSlurper().parseText(b.getText())
                                    ..
                                }
                            }
                        }
                    }
                }
            }
        }
    }
