### ISSUE TITLE
Improved external configuration

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#212]
Add a new module, ratpack-jackson-config.  This module will provide a robust approach to configuring Ratpack applications via an external configuration file bound to a user-provided configuration class.  This mechanism is inspired by the approach used by DropWizard.

High-Level Goals:
1. Primary oriented around configuration by external files
2. Supports YAML as primary file format
3. The module binds the configuration to the user's provided configuration objects (unless they need a non-default binding, the user shouldn't need to do anything special for this to work)
4. Validation of the configuration objects is supported
5. No special handling in ratpack-core; the mechanism used to allow this configuration approach should also be usable by other approaches to configuration
6. Also supports configuration by environment variables (to support [12 factor apps](http://12factor.net/)) and system properties

Implementation Plan:
* Modify ratpack-core to support another module taking control of creating the LaunchConfig.
  * A `ConfigurationProvider` interface loaded via `ServiceLoader` might work (the current `LaunchConfigs.createFromGlobalProperties` approach could be extracted into an implementation).
  * We might want to have the command-line arguments allow specifying what configuration file to load
* Allow the user to specify their root configuration class type
  * TODO: how?  Dropwizard has a parameterized Application class that takes the configuration class as a parameter.  We could do that, but that would seem to cause problems with other modules that want to control the startup, such as GroovyRatpackMain.
* Acquires configuration values from the following sources (from highest priority to lowest)
  * System properties (a prefix is used to differentiate properties that should be bound to configuration from other system properties; can probably re-use the existing "ratpack." convention from `LaunchConfigs`)
  * Environment variables
  * The configuration file
  * An optional configuration file on the classpath (intended for defaults that an extenal configuration can overlay on top of)
  * Default values of configuration object fields
* Use Jackson to parse the configuration file and bind it to the configuration objects
  * Provide some mechanism for polymorphic configuration, similar to DropWizard's support for `Discoverable`
* If a Bean Validation provider is available, use it to validate the object model, and fail startup if the configuration is invalid.
  * Add a ratpack-hibernate-validator module to make it easy to load Hibernate Validator, along with possible related utility classes/tweaks/etc.

Design Notes:
* Why Jackson?  It's a mature, capable library, and it seems to work well enough for Dropwizard for this purpose.
* Why Hibernate Validator?  I haven't found anything better.  It not only implements the latest Bean Validation spec, but it's the reference implementation.  It's actively developed, commonly used, and I couldn't find any compelling competitors.  The only knock against it is that it might have more dependencies than we'd like.
  * [Apache BVal](http://bval.apache.org/) doesn't support the latest spec and doesn't seem to be getting much activity.
  * [OVal](http://oval.sourceforge.net/) doesn't actually implement Bean Validation 1.0 (it has a translation layer that provides partial compatibility) and doesn't seem actively developed.
* Modes/environments/profile support was omitted, as these concepts are complicated and often promote bad practices.  Instead, easily switching between external configuration files with optional support for overlaying is preferred.

**Comment by davidmc24** [comment]
This has changed quite a bit from when it was first started.

In `ratpack-core`, `ServerConfigBuilder` has support for loading from properties and environment variables.

There is now a module, `ratpack-config`, which can optionally be used to load multiple configuration sources and bind them to arbitrary config objects.  This module depends on Jackson for JSON/YAML support and object binding.

Example using new config support:

```java
ConfigurationData configData = Configurations.config().yaml("config.yaml").json("config.json").props("config.properties").env().sysProps().build();
RatpackServer server = RatpackServer.of(spec -> spec
    .config(configData.get("/server", ServerConfig.class))
    .registry(r -> r
        .add(MyAppConfig.class, configData.get("/app", MyAppConfig.class))
    )
    .build(registry ->
        (ctx) -> ctx.render("Hi, my name is " + ctx.get(MyAppConfig.class).getName())
    ));
server.start();
```

**Comment by alkemist** [comment]
This is a big one to close.

Great job @davidmc24
