### ISSUE TITLE
Improve security of file system handling to prevent directory traversal attacks

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#214]

**Comment by alkemist** [comment]
I'm not sure what the current state of this is. We've done some work, and I don't really know what's necessary in order to say that we are 100% safe. We need a little more research I think.

**Comment by davydotcom** [comment]
Your code appears to normalize the path and remove backwards traversal aspects such as `..` . This is very similar to what the Asset-Pipeline does so you should be good

**Comment by alkemist** [comment]
Calling it done.
