### ISSUE TITLE
Startup action mechanism

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#220]
There needs to be a way to flexible and powerful way to run actions on startup.

Use cases:

1. Performing DB migrations
1. Precompiling templates
1. Performing asset compilation (arguably a build time approach would be better)
1. Any kind of pre-fetching

Requirements:

1. Actions can be designated as blocking (must complete before accepting requests)
1. Actions can be designated as background (requests may be accepted before the action finishes)
1. An action implementation may be used as blocking or background (i.e. different contexts may call for blocking or background)
1. Blocking actions can contribute to the handler chain (like HandlerDecoratingModule)

API:

?

Implementation:

?

**Comment by davidmc24** [comment]
This has been handled by way of introducing support for the concept of a "ratpack service" (see [Service](https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/main/java/ratpack/server/Service.java)).
