### ISSUE TITLE
Add support for monitoring/tracing with New Relic

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#261]

**Comment by alkemist** [comment]
Will create a new ticket when New Relic land their async support.

**Comment by johnrengelman** [comment]
Do we need something beyond this? https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/java-agent-3220
I totally forgot about this ticket and how old it was!

**Comment by alkemist** [comment]
Yeah, that doesn't get it done. I've been in contact with New Relic about this, and they assure that what we need is coming.

**Comment by jfernandez** [comment]
It's been over a year, any update on this?
