### ISSUE TITLE
Metrics module: Expose SharedMetricRegistries instead of MetricRegistry

### ISSUE THREAD

**Issue by spinscale** [ratpack/ratpack#404]
Hi,

in order to have own metric registries and also own (web socket) reporters (the current one is not reusable) it makes sense to expose the `SharedMetricRegistries` class with a default MetricRegistry instead via Guice. Note: Not the default SharedMetricRegistries, as it is static, but something along those lines.

I might try for a PR in the next days, if you think this is a useful idea...

**Comment by alkemist** [comment]
@rhart what do we need to do here?

**Comment by rhart** [comment]
I'm not totally convinced we need to support multiple metric registries.  I think it adds complexity in deciding which registry to use for internal metrics i.e. do we allow configuration of which internal metric gets reported to which metric registry, getting hold of the metric registry you want, different reporter configurations for different registries......

I think we can achieve what is required by allowing multiple reporters of the same type (for certain types).  That way you can just apply the different filter options you require on different reporters.
