### ISSUE TITLE
Add a request log

### ISSUE THREAD

**Issue by kyleboon** [ratpack/ratpack#430]
It would be handy if all requests were logged using the common log format (http://en.wikipedia.org/wiki/Common_Log_Format)

It seems like it would be possible to do this in the ```NettyHandlerAdapter```

**Comment by alkemist** [comment]
Reworked the impl… hopefully improved it.

We can't quite close this off yet because we aren't using the canonical log format. And we're missing docs on bindAndLog().

https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/main/java/ratpack/handling/RequestId.java#L103

**Comment by johnrengelman** [comment]
I updated the request log to look like this:
```
[ratpack-compute-7-4] INFO ratpack.handling.RequestLog - 127.0.0.1 - - [15/Jun/2015:11:12:21 -0500] "GET /foo HTTP/1.1" 200 36 id=10bbebb5-838b-02a0-9cff-60a14da60d8d
[ratpack-compute-7-5] INFO ratpack.handling.RequestLog - 127.0.0.1 - - [15/Jun/2015:11:12:21 -0500] "POST /bar HTTP/1.1" 200 36 id=f7ce6594-1e69-6240-b0c2-d054abf2d8bc
```

There are still a couple missing pieces, like `userId` which needs to somehow be integrated (need to look into how to access that if it's configured) and we might want to do some testing with use this with websockets and those kinds of things.

I tacked the `requestId` onto the end, but I'm not totally happy with that. There isn't really anyway to extends the NCSA Common log format though. I'm thinking this would be fine along with some documentation describing it. Alternatively we could use Extended Log format, but that's more complex and not as common.

**Comment by johnrengelman** [comment]
Closing this off since https://github.com/ratpack/ratpack/commit/64b7a35893cf499bb2cbb0b7a898e06c0ab301e4 added the userId in the correct place. 

Any further improvements to this logging can be a new ticket. However, we've added sufficient hooks that a user can now customize this as they see fit.
