### ISSUE TITLE
Dependency cycle between modules

### ISSUE THREAD

**Issue by dsyer** [ratpack/ratpack#446]
I think that `gradle/javaModule.gradle` might be hiding an ugly cycle

```
ratpack-core -> ratpack-test-internal -> ratpack-groovy-test -> ratpack-groovy -> ratpack-core
```

Gradle still manages to build everything (amazingly). It might be only in test dependencies, but it seems like a bad idea, and for Eclipse users all modules are broken because `ratpack-core` is needed by everything else.

**Comment by dsyer** [comment]
I'd love to contribute some code to Ratpack, but unless I can get it to work with Eclipse it's probably a non-starter (I'm not going to learn IDEA just for this project). Can anyone offer any insight into how to resolve the cycle?

**Comment by alkemist** [comment]
Can you try changing this?

![preferences](https://cloud.githubusercontent.com/assets/17825/6158017/7561e2d6-b29a-11e4-8c2a-498aece69340.png)

I tried this, but it still wouldn't build because the Eclipse compiler complains that certain constructs are illegal, that are perfectly legal.

**Comment by dsyer** [comment]
I already had that flag set. There's another problem (maybe this one is easier for you to fix):

> Cannot nest 'ratpack-test-internal/shared-resources' inside 'ratpack-test-internal'. To enable the nesting exclude 'shared-resources/' from 'ratpack-test-internal'

I tried excluding the shared resources like it said, but that just sent me down a rabbit hole of dependent errors (since the stuff in that folder is presumably actually needed elsewhere).

**Comment by alkemist** [comment]
Ok, I'll shuffle things around and duplicate that file.

**Comment by alkemist** [comment]
@dsyer sorry for the delay. I've changed things so that Eclipse is happier.

It's complaining about some Java code that works just fine with `javac`. I'd rather not change it just to appease `ecj` unless you need them fixed.

**Comment by alkemist** [comment]
I'm going to close this, but I'm happy to reopen if it's still not usable for you.

**Comment by dsyer** [comment]
Can you re-open (or I can start a new issue)? It's not just "complaining" it's not even compiling. Unless I know how to switch off those errors I still can't use Eclipse.

**Comment by alkemist** [comment]
Let's open a new issue.
