### ISSUE TITLE
Improve session support to be more friendly to persistent and expensive stores.

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#447]
What is currently `SessionStorage` should become:

```
public interface SessionStorage {

  // Returned object is not live, is a copy of the data at read time
  <T extends Serializable> Promise<Optional<T>> get(TypeToken<T> type);

  <T extends Serializable> Promise<Boolean> put(TypeToken<T> type, T t);

  <T extends Serializable> Promise<Integer> remove(TypeToken<T> type);

  Promise<Optional<String>> get(String key);

  Promise<Boolean> set(String key, String value);

  Promise<Integer> remove(String key);

  Promise<Integer> clear();
  
}
```

1. Reads from the session always return value objects (i.e. changes to the objects are not automatically written back to the session)
2. Type based storage is based on equality, not assignability

**Comment by beckje01** [comment]
For a first cut I landed on the following:
```
public interface SessionStorage  {

  <T> Promise<Optional<T>> get(String key, Class<T> type);

  Promise<Boolean> set(String key, Object value);

  Promise<Set<String>> getKeys();

  Promise<Integer> remove(String key);

  Promise<Integer> clear();
}
```

This will allow expensive stores but didn't get into the Type based storage.

**Comment by wmacgyver** [comment]
shouldn't invalid/timeout be part of the interface too?

**Comment by alkemist** [comment]
@wmacgyver can you elaborate?

**Comment by beckje01** [comment]
Invalidate and timeout are part of the session itself not the storage inside a session. We currently have these split. So you can invalidate and time out sessions without ever using a session storage.

**Comment by wmacgyver** [comment]
@alkemist @beckje01 my bad, I didn't realize it's split this way.

**Comment by beckje01** [comment]
@wmacgyver Its confusing look for some docs soon...

**Comment by alkemist** [comment]
It's also not set in stone. We may in fact merge these two things.

**Comment by gschrader** [comment]
This is a bit of a breaking change and it wasn't obvious at first why.  The promise needs to be acted on for the SessionStorage methods to do anything.

this code:
```
        get("logout") { SessionStorage sessionStorage ->
            sessionStorage.clear()
            redirect("/")
        }
```

now needs to be:
```
        get("logout") { SessionStorage sessionStorage ->
            sessionStorage.clear().then({})
            redirect("/")
        }
```

I'm not sure if there is a cleaner way to handle this.

**Comment by alkemist** [comment]
It actually needs to be:

```
        get("logout") { SessionStorage sessionStorage ->
            sessionStorage.clear().then { redirect "/" }
        }
```

Otherwise, you are issuing the redirect and then clearing the session.

Re not subscribing to the session, we are working on some diagnostics that would have helped to point this out.

**Comment by gschrader** [comment]
Ah cool yes that makes sense now, thanks!
