### ISSUE TITLE
Implement Connection Pooling/KeepAlive in the DefaultHttpClient

### ISSUE THREAD

**Issue by dannwebster** [ratpack/ratpack#465]
Ratpack's DefaultHttpClient for managing outbound HTTP requests currently builds up and tears down every HTTP. This issue addresses this by correctly managing HTTP 1.1 KeepAlive connections, and providing a pooling mechanism for accessing those connections.

**Comment by chbatey** [comment]
Was any work done on this @beckje01 @dannwebster ?

**Comment by tednaleid** [comment]
With the addition of [`ChannelPool`](http://netty.io/news/2015/05/07/4-0-28-Final.html) in netty 4 which we've now got in RP 1.2 that seems like potentially a good way to implement this.

**Comment by alkemist** [comment]
I didn’t know this had landed. Excellent!

Thanks for the pointer.
