### ISSUE TITLE
Context registry should encompass request registry

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#485]
Using context.get() (and other registry methods) should implicitly look in the request registry first. This would just be like any other hierarchical registry, with the request registry being the parent (i.e. checked first).

The change would need to happen in DefaultContext. We'd effectively have to create a hierarchical registry on demand, so that we don't wrap each context registry with the request registry. To do this, we'd probably need to create an internal variant of HierarchicalRegistry, where the child is given as a Supplier<Registry>. In DefaultContext we'd create such a Registry with the supplier supplying the context registry only.

When we do this, we can update InjectionHandler to just pull from the Context registry.

**Comment by danhyun** [comment]
Registry is now LIFO so in this case the `Request` should be the child in the `HierarchicalRegistry`.
Wouldn't it be enough to implement lookups in `DefaultContext` to call `getRegistry().join(this.requestContstants.request)` before invoking `get`, `maybeGet` `getAll` and `first`?

`DefaultContext.java`
```
private Registry getRegistry() {
  return requestConstants.indexes.peek().registry.join(requestConstants.request);
}
```

Just to verify, is this what we're expecting?

```
import ratpack.registry.Registry;
import ratpack.test.embed.EmbeddedApp;

import static org.junit.Assert.assertEquals;

public class Example {

  public static void main(String[] args) throws Exception {
    EmbeddedApp
      .of(server -> server
        .registryOf(r -> r.add("1"))
        .handlers(c -> c
          .get("foo", ctx -> ctx.render(ctx.get(String.class)))
          .all(ctx -> {
            ctx.getRequest().add("request");
            ctx.next();
          })
          .all(ctx -> {
            ctx.next(Registry.registry(r -> r.add("2")));
          })
          .get("bar", ctx -> ctx.render(ctx.get(String.class)))
        )
      ).test(testHttpClient -> {
      assertEquals("1", testHttpClient.getText("foo"));
      assertEquals("request", testHttpClient.getText("bar"));
    });
  }
}
```

**Comment by alkemist** [comment]
I've been holding off on this one because I'm not quite sure what to do about the request registry. During request processing, we have 3 different registries in play…

1. The `Execution` registry
2. The `Request` registry
3. The `Context` registry

Registries 1 and 2 serve exactly the same function, which doesn't feel good. We need the `Execution` registry, because not everything is about request processing. OTOH, casual users don't really know that `Execution` exists.

The context registry serves a different purpose and should stay regardless.

Before moving forward on this issue at hand, I wanted to try and sort this out.

Thinking about this now, what we could do is have the `Request` registry be literally the same as the `Execution` registry. Then we are back to two registries, but keep the “sugar” for adding to this registry. In implementation terms, the `Registry` methods on `Request` would just delegate to the `Execution.

So given that…

I'd implement this issue slightly differently to how you propose, in order to reduce object churn. I'd add an abstract `DelegatingRegistry` with an abstract `getDelegate()` method. In `Context` I'd create an instance scoped inner class implementation of this where `getDelegate()` always returns `requestConstants.indexes.peek().registry`. Then, the registry returned by `getRegistry()` would be a join of this registry and the context registry. This avoids having to create a new hierarchical registry every time `getRegistry()` is called.

**Comment by danhyun** [comment]
It's a currently a bit awkward to set the `Execution` as a delegate on `Request` as we are still in Netty land when we create the `DefaultRequest`. The current suggestion is to use an interceptor for the execution to wait until execution starts to set the delegate on the `Request` and also take the opportunity to register the `Request` on the `Execution`.

**Comment by danhyun** [comment]
Taking another look and having `DefaultContext#getRegistry()` be modified doesn't help us. It creates a weird looking object graph where children are their own grandparents.

We really want to provide a way for all the retrieval methods to get the effectively joined `Registry`. Given this, we can still collapse `Request` and `Execution` to be the same `MutableRegistry`.

**Comment by danhyun** [comment]
@alkemist mind taking a look at ^?
