### ISSUE TITLE
Simple way to unit test classes whose collaborators return promises

### ISSUE THREAD

**Issue by tomdcc** [ratpack/ratpack#491]
Handlers calling collaborator classes who return promises need those promises to have been created using the same `ExecController` that the handler is run with. This is a bit of a pain when running with `UnitTest.handle`.

FWIW for my purposes it was enough to write a utility method to grab it from the stored threadlocal:

    static <T> Promise<T> instaPromise(T val) {
        ExecController.current().get().control.promise { f -> f.success(val) }
    }

**Comment by alkemist** [comment]
This was effectively solved by the new `ExecController.execController()` method which lazily binds to the exec controller.

So, you can now do `ExecController.execController().promiseOf(val)`. I think we can sweeten this even more by some static methods on `Promise`, but that can be a separate thing.
