### ISSUE TITLE
Add a cookie based session store

### ISSUE THREAD

**Issue by danhyun** [ratpack/ratpack#504]
`ratpack-session` currently supports a memory based session store, we should provide a `CookieBasedSessionStore` and `CookieBasedSessionStorage` as an alternative to MapBasedSession implementations.

**Comment by danhyun** [comment]
2 has been addressed. Still need to discuss 4.

wrt4: Doesn't make sense/is not practical to serialize object graphs, is `toString()` too simplistic? I'm not aware of any middle ground. Does it make sense to throw `IllegalArgumentException` if you don't explicitly pass a string as both key and value?

**Comment by alkemist** [comment]
`toString()` is not round-trippable. That is, you can't recreate the object from the string. 

It's certainly an option to only support strings when using client side storage. We can at least start there. Have to make sure this limitation is prominently documented.

**Comment by danhyun** [comment]
We could offer to serialize/deserialize to JSON, I would rather not introduce Jackson as a dependency to sessions but it would be nice to treat the client session store as a true multi level map.

**Comment by alkemist** [comment]
We wouldn't implicitly convert to JSON. The user would either need to tell us to do this (by way of a bi directional converter) or do it before giving us the value (i.e. store the JSON representation directly)

**Comment by alkemist** [comment]
We should have a look at the new Spring Session API for inspiration.

**Comment by ylemoigne** [comment]
Note : the serialization problem made ClientSideSessionsModule not compatible with pac4j at this time.
(as the store return the "toString" of registered UserProfile, it end with ClassCastException in Pac4jProfileHandler.java:50)

**Comment by danhyun** [comment]
Thanks to @zedar for addressing a bulk of the remaining issues as well as implementing really nice features. I'm going to close this ticket to mark that we have a solid basic client side session store but I'm going to open a new ticket to address serialization and pac4j here #664.

**Comment by alkemist** [comment]
Docs need review.
