### ISSUE TITLE
Add Asset Pipeline for asset management

### ISSUE THREAD

**Issue by davydotcom** [ratpack/ratpack#506]
The bertramdev/asset-pipeline-core project is now released as 2.0.7 on maven central. This provides libraries for bundling, minification, transpiling. There is both a development mode and a production mode (production mode stays out of the way). Would like to look into implementing this for ratpack so we can serve assets with proper cache digest names, headers, and for easy compiling of assets and live reloading during development.

**Comment by davydotcom** [comment]
Id call this done

**Comment by alkemist** [comment]
Set label as won't fix, because we've “decided” not to do this in core. 

(but it's available as a separate lib)
