### ISSUE TITLE
Support consuming SSE streams via the HTTP client

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#518]
This would be nice, if for no other reason than using in our tests and docs.

**Comment by rhart** [comment]
I've been doing some work on this.  We will need to deal with SSE streams both with and without a `transfer-encoding` of `chunked`.

With Netty, when `chunked` each `bytebuf` will be a server sent event.  However, when not `chunked` each `bytebuf` may contain multiple events depending on how close together they are received.

I think this means we will need to map a bytebuf to a collection of server sent events and use `Streams#fanout`

**Comment by rhart** [comment]
According to the Netty documentation, when dealing with stream based transport "there is no guarantee that what you read is exactly what your remote peer wrote" and so received data needs to be "framed" http://netty.io/wiki/user-guide-for-4.x.html#wiki-h4-14

But am I right in thinking that `HttpObjectDecoder` takes care of this for us?  Based on what is descibed here http://netty.io/wiki/user-guide-for-4.x.html#wiki-h4-14  

So by the time we receive a `HttpContent` object in our http client pipeline it's already framed?

**Comment by alkemist** [comment]
That's my understanding.

**Comment by rhart** [comment]
I think I've broken the back of this now.  I have a decoder which dispatches events as it comes across them in a ByteBuf that may contain 1 or more events.  It's used by a `StreamMapPublisher` like this
```
  public ServerSentEventPublisher(Publisher<ByteBuf> upstream, ByteBufAllocator bufferAllocator) {
    super(upstream, sseWriteStream -> new WriteStream<ByteBuf>() {
      @Override
      public void item(ByteBuf item) {
        try {
          ServerSentEventDecoder.INSTANCE.decode(item, bufferAllocator, sseWriteStream::item);
          complete();
        } catch (Exception e) {
          error(e);
        }
      }

      @Override
      public void error(Throwable throwable) {
        sseWriteStream.error(throwable);
      }

      @Override
      public void complete() {
        sseWriteStream.complete();
      }
    });
  }
```
I think this is better than what I was thinking before.

It needs some more sugar but can then be used like
```
      get { HttpClient httpClient ->
        httpClient.requestStream(otherAppUrl("foo")) {
        } then { StreamedResponse responseStream ->
          ByteBufAllocator byteBufAllocator = get(ByteBufAllocator)
          render stringChunks(
            new ServerSentEventPublisher(responseStream.body, byteBufAllocator).map { Event<?> e ->
              e.data
            })
        }
      }
```
Will hopefully have something to publish soon.

**Comment by alkemist** [comment]
Sounds very promising :)

**Comment by rhart** [comment]
I'm not sure the best way to sugar this up.  I'm thinking I could either add a new method on `StreamedResponse` like `TransformablePublisher<Event> getSse();` so the use would be like
```
httpClient.requestStream(otherAppUrl("foo")) {
} then { StreamedResponse responseStream ->
  responseStream.sse.map { Event e ->
    println e.data
  }
}
```

Or create an `SseClient` which internally uses `HttpClient` and the use would be like
```
sseClient.requestStream(otherAppUrl("foo")) {
} then { TransformablePublisher<Event>  sseStream ->
  sseStream.map { Event e ->
    println e.data
  }
}
```

Any thoughts??  I think I'm leaning towards the latter.

**Comment by alkemist** [comment]
@rhart do you think we should close this?

**Comment by rhart** [comment]
As long as you're happy with the `ServerSentEventStreamClient` approach as opposed to adding to `HttpClient`.

Usage is
```
sseStreamClient.request(otherAppUrl("foo")).then { TransformablePublisher<Event<?>> eventStream ->
    .........
    .........          
}
```

There is of course manual content to be added.  That's the reason it's still open.  Unless there's more urgent tasks than the docs maybe leave open and I'll tackle the docs after #621?
