### ISSUE TITLE
Build leaves a lot of temporary files or directories

### ISSUE THREAD

**Issue by melix** [ratpack/ratpack#532]
The Ratpack build leaves a lot of temporary files or directories in the system temporary directory. While this is not a problem for desktop computers, it is a bit annoying for a CI server. Here's an example list of things that I noticed, there may be more:

```
  cd /tmp
  rm -Rf testHandler*
  rm -Rf ratpack*
```

I have deleted much more temporary files, but I can't make sure they are generated by Ratpack so better not ring a bell :)

**Comment by alkemist** [comment]
Found them.

There were being generated by BaseDirBuilder. Fixed here: https://github.com/ratpack/ratpack/commit/42538b79f23fe102084e1b93716bb2a7f96b2c74#diff-b1bfc23184acd71155b991ba0bbc966eR83
