### ISSUE TITLE
Improved configurability of asset handler

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#537]
Our asset handling is too simplistic. I'd like to change things around to make the asset handling more configurable, by introducing a builder for asset handlers.

We should introduce…

```
package ratpack.file

interface AssetHandlerSpec {
  AssetHandlerSpec compressionMinSize(int bytes)
  AssetHandlerSpec indexFiles(String... indexFiles)
  AssetHandlerSpec noCompress(String mimeTypes)
}
```

The asset handler method on `Handlers` and corresponding `Chain` method will change to…

```
Handler assets(LaunchConfig launchConfig, String path, Action<? super AssetHandlerSpec> config)
```

We can then remove the related items from launch config.

This will also require some reworking of the file serving internals to support more decisions being made about how to render the file at the handler level instead of the internal transmitter.

**Comment by alkemist** [comment]
Great :)

I think it's ready to start on.

I'd start with just…

```
interface AssetHandlerSpec {
  AssetHandlerSpec indexFiles(String... indexFiles)
}
```

Because supporting the compression settings etc. requires some non trivial rejigging of some deep stuff that may slow you down. We can easily add it as a second round.

Don't hesitate to ask for clarification/help on anything.

**Comment by davydotcom** [comment]
Are you going to compress files on the fly? Might be better to quit create gz versions when packaging up so you don't have the load on servers from gripping

**Comment by davydotcom** [comment]
gzipping*

**Comment by alkemist** [comment]
At the moment it compresses on the fly. We could support pre-compression, but not as part of this ticket.

**Comment by scottescue** [comment]
Sounds good.  I should be able to start digging in tomorrow evening.

**Comment by davydotcom** [comment]
Perhaps it would be better to simply have this look for the file with a gz extension. And serve that instead of implementing embedded compression. There are cases where some people prefer actually using different compression levels, even different compression libraries to create their gz content. Adding this into ratpack itself may just add more overhead thats not needed. Just throwing that out there, I have received multiple requests for supporting other gzip compression libraries

**Comment by alkemist** [comment]
Supporting alternative compression strategies is well outside the scope of this ticket.
