### ISSUE TITLE
ratpack-pac4j authentication handler does not properly handle ajax requests.

### ISSUE THREAD

**Issue by jeff-blaisdell** [ratpack/ratpack#538]
While requesting a path that requires authentication the Pac4jAuthenticationHandler passes a hard coded 'false' to the client's redirection method for the ajaxRequest argument.  This causes ajax requests to be sent redirects rather than the expected 401 response.

The problem method:
```
  private void initiateAuthentication(final Context context) {
    final Request request = context.getRequest();
    request.get(SessionStorage.class).put(SAVED_URI, request.getUri());
    final Clients clients = request.get(Clients.class);
    final RatpackWebContext webContext = new RatpackWebContext(context);
    context.blocking(() -> {
      clients.findClient(name).redirect(webContext, true, false);
      return null;
    }).onError(ex -> {
      if (ex instanceof RequiresHttpAction) {
        webContext.sendResponse((RequiresHttpAction) ex);
      } else {
        throw new TechnicalException("Failed to redirect", ex);
      }
    }).then(ignored -> webContext.sendResponse());
  }
```

The specific line is:
```
      clients.findClient(name).redirect(webContext, true, false);
```

**Comment by davidmc24** [comment]
Good point.  Given that context, hard-coding `false` clearly isn't the right thing to do.  Do you have any suggestions on how this should be handled?  That is, how should we determine whether to pass `true` vs. `false`?  Perhaps a new method on `Authorizer`, `boolean isAjaxRequest(Context)`, with a default of `false`?

**Comment by jeff-blaisdell** [comment]
Above is the PR I started on.

Sniffing for a X-Requested-With header set to XMLHttpRequest I think is a fairly common pattern.  I believe it was started with jQuery.  I could also see the benefit of making something a little fancier than I did in my PR - something like you said - another method on authorizer would work as well.  

I personally have never had a reason to do anything other then the X-Requested-With sniffing, but I'm sure someone could come up with a case.

**Comment by davidmc24** [comment]
Thanks for the pull request!  I like the approach of using the `X-Requested-With` header better than a default of always `false`.  I think you're right that it will probably handle most cases, but I'm not quite comfortable with hardcoding that behavior either.

What do you think about making it a function in Pac4jAuthenticationHandler, with a setter in case someone wants to override it?  It's an internal class, but I think that's a reasonable compromise for now. 

Maybe something like
`private Function<Context, Boolean> ajaxDeterminer = (Context ctx) -> "XMLHttpRequest".equalsIgnoreCase(ctx.getResponse().getHeaders().get(HttpHeaderConstants. X_REQUESTED_WITH));`
