### ISSUE TITLE
Upgrade pac4j dependency to latest 1.6.0 version.

### ISSUE THREAD

**Issue by jeff-blaisdell** [ratpack/ratpack#540]
Pac4J is now at version 1.6.0 - update Ratpack dependency to latest.
https://github.com/pac4j/pac4j/releases

**Comment by johnrengelman** [comment]
Closed by the above PR.
Also had to update the `pac4j-http` dependency here: https://github.com/ratpack/example-books/blob/latest/build.gradle#L38

**Comment by alkemist** [comment]
@davidmc24 @rhart is that pac4j-http dependency something we should be bringing in via ratpack-pac4j?

**Comment by davidmc24** [comment]
My opinion is no.  There's nothing particularly special about `pac4j-http`, it's just one of the many integrations between pac4j and other authentication approaches.  If we pull that in, by the same token we'd want to pull in pac4j-oauth, pac4j-cas, pac4j-saml, etc.  Other than adding a dependency on the submodules, any ideas on how to let users declare "I need this pac4j module at the same version as the version that ratpack is pulling in?"  I'd probably use a Gradle dependency resolve rule, but I'm not sure that's a technique we want to be recommending here.

**Comment by alkemist** [comment]
Sound reasoning.
