### ISSUE TITLE
NoClassDefFoundException for HttpHeaderNames and HttpHeaderUtil

### ISSUE THREAD

**Issue by dsyer** [ratpack/ratpack#545]
These classes appear to be in netty master, but are not in any published snapshots that I could find. Ratpack 0.9.12 depdends on netty 4.1.0.Beta4-SNAPSHOT and this does not contain those classes.

Stack trace:

```
java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpHeaderUtil
	at ratpack.server.internal.DefaultResponseTransmitter.<init>(DefaultResponseTransmitter.java:83)
	at ratpack.server.internal.NettyHandlerAdapter.channelRead0(NettyHandlerAdapter.java:150)
	at ratpack.server.internal.NettyHandlerAdapter.channelRead0(NettyHandlerAdapter.java:74)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at ratpack.server.internal.NettyHandlerAdapter.channelRead(NettyHandlerAdapter.java:127)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
```

**Comment by davidmc24** [comment]
Are you looking at http://clinker.netty.io/nexus/content/repositories/snapshots?

It looks to me like the JARs in here have it.  http://clinker.netty.io/nexus/content/repositories/snapshots/io/netty/netty-codec-http/4.1.0.Beta4-SNAPSHOT/

**Comment by dsyer** [comment]
I was using https://oss.sonatype.org/content/repositories/snapshots. Your repo works. It might be a good idea to document this somewhere (e.g. in build.gradle).

**Comment by alkemist** [comment]
This has been resolved for me.

**Comment by dsyer** [comment]
Works for me with the clinker repo. It would be nice if someone (from netty I guess) could update the sonatype repository as well (since they have set a precedent for deploying snapshots there and haven't updated since October), but I don't have high hopes of that.

**Comment by trustin** [comment]
Hmm, we can do that obviously. Let me try to figure out how to configure our Jenkins instance.

**Comment by dsyer** [comment]
That would be awesome.

**Comment by alkemist** [comment]
@trustin much appreciated, thank you.

**Comment by trustin** [comment]
Wish fulfilled. Enjoy!

**Comment by alkemist** [comment]
@trustin unfortunately, the latest snapshot doesn't work for us: https://github.com/netty/netty/issues/3324

Would it be possible to publish another once that is resolved?
