### ISSUE TITLE
Gradle plugin produces improper start scripts

### ISSUE THREAD

**Issue by danveloper** [ratpack/ratpack#546]
0.9.13-SNAPSHOT

There are a few things that need sorting out here... To start: https://github.com/ratpack/ratpack/blob/master/ratpack-gradle/src/main/groovy/ratpack/gradle/RatpackPlugin.groovy#L72 ... We probably want a user to explicitly specify this through some plugin convention mapping. Maybe the application plugin convention is still ok for this?

We're no longer requiring a `src/ratpack` dir, so we probably also need to update:
  * https://github.com/ratpack/ratpack/blob/master/ratpack-gradle/src/main/groovy/ratpack/gradle/RatpackPlugin.groovy#L85-L87
  * https://github.com/ratpack/ratpack/blob/master/ratpack-gradle/src/main/groovy/ratpack/gradle/RatpackPlugin.groovy#L93-99

**Comment by alkemist** [comment]
Yeah, main class will be set by the convention.

We still require a base dir as much as we ever did, so the only change will be to remove the default main class.

**Comment by johnrengelman** [comment]
Removed in https://github.com/ratpack/ratpack/commit/3783503539ace611b16ff1a3d7ad0d5a64ac6e4b
