### ISSUE TITLE
Manual Docs; build.gradle file cite should have netty-handler:4.1.0.Beta4-SNAPSHOT repository.

### ISSUE THREAD

**Issue by tbrophy** [ratpack/ratpack#549]
Manual Docs; build.gradle file cite should have netty-handler:4.1.0.Beta4-SNAPSHOT repository.

Related issue(s); https://github.com/ratpack/ratpack/issues/545

Location; http://www.ratpack.io/manual/current/setup.html#using_the_gradle_plugins

Discovered; While running gradle idea --stacktrace

Issue; netty-handler:4.1.0.Beta4-SNAPSHOT is not accessible via jcenter as of Wed Jan 14 08:12:54 PST 2015

Possible fix; Section 2.1.2 "Using the Gradle Groovy plugin" lists an example build.gradle file where the 2nd repositories section should be updated to include...

    maven {
        url "http://clinker.netty.io/nexus/content/repositories/snapshots"
    }

 ...for example...

 buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath "io.ratpack:ratpack-gradle:0.9.12"
  }
}

apply plugin: "io.ratpack.ratpack-groovy"
apply plugin: "idea"

repositories {
    jcenter()
    maven {
        url "http://clinker.netty.io/nexus/content/repositories/snapshots"
    }
}

dependencies {
  runtime "org.slf4j:slf4j-simple:1.7.5"
}

**Comment by alkemist** [comment]
Many thanks for the report.

We'll get this fixed for the next release. We won't have the snapshot dependency for .13 and won't need the extra repo.

**Comment by davidmc24** [comment]
Unfortunately, Netty 4.1.0.Beta4 still hasn't been released.  Ratpack 0.9.13 will still have a dependency on 4.1.0.Beta4-SNAPSHOT.  Hopefully it will be out in time for Ratpack 0.9.14.
