### ISSUE TITLE
Sensibly handle Set-cookie header in redirects in RequestActionSupport

### ISSUE THREAD

**Issue by danhyun** [ratpack/ratpack#561]
[This spec](https://github.com/ratpack/ratpack-talks/commit/a2f05aa7d3c7c7cbda9f02a19d2e38b8f5a5198d#diff-1469272ef59ddc20f3e3aa3cff5224bdR31) is currently failing because cookies are not handled in RequestActionSupport upon redirect.

The TestHttpClient should respond to and process each response from a redirect via RequestActionSupport.

**Comment by alkemist** [comment]
@danhyun what's the status on this?

**Comment by alkemist** [comment]
@danhyun ping.

**Comment by danhyun** [comment]
After some discussion with @beckje01 we've decided to let only the `TestHttpClient` set redirects to 0 and to set cookie values then request the new location.

**Comment by danhyun** [comment]
The latest commit fixes the failing spec.

**Comment by alkemist** [comment]
@danhyun can you point me to the change for this please.

**Comment by danhyun** [comment]
They were in my local stash, I thought they were already in. Running tests locally then will push up.
