### ISSUE TITLE
When using ratpack-codahale-metrics, enabling a reporter should enable metrics

### ISSUE THREAD

**Issue by davidmc24** [ratpack/ratpack#570]
When calling any of the methods on the configuration objects within `CodaHaleMetricsModule` that depend on metrics collection, it should implicitly enable metrics collection.  This includes:

* `Config.jvmMetrics(true)`
* `Jmx.enable(true)`
* `Console.enable(true)`
* `Csv.enable(true)`

Also update the javadoc examples/tests that leverage this functionality to remove the now redundant `Config.enable(true)` call.

**Comment by rhart** [comment]
I wouldnt mind taking this one.

**Comment by davidmc24** [comment]
Now that we've extracted our health check support into a separate module (#578), perhaps it would make sense just to remove the concept of metrics being enabled/disabled altogether.  That is, if you've added the `CodahaleMetricsModule`, metrics is enabled (though individual reporters are still enabled/disabled individually).

**Comment by rhart** [comment]
Yeah that's what I'm looking at doing now.
Also, removing `enabled` from the sub configs too.  So if you set one then it is implicitly enabled.
