### ISSUE TITLE
Better review processes

### ISSUE THREAD

**Issue by davidmc24** [ratpack/ratpack#572]
We currently have a review process oriented around a Barkeep instance on [review.ratpack.io](http://review.ratpack.io/).  However, we aren't following through on it all that consistently.  Also, Barkeep doesn't yet have an alternative authentication mechanism to Google OpenID, which will be shut down in April 2015 (see https://github.com/ooyala/barkeep/issues/494 and https://developers.google.com/accounts/docs/OpenID).

It has been suggested that introducing [Codebrag](http://codebrag.com/) instead to Barkeep might help.

As the process is updated, `RELEASING.md` should also be updated to indicate the appropriate tie-ins with the release process.

**Comment by alkemist** [comment]
Given we've now ramped up activity, we should probably make this a priority.

I'd like to consider JetBrain's new review tool as well. AFAIK, they don't offer a hosted version.

**Comment by davidmc24** [comment]
https://www.jetbrains.com/upsource/

**Comment by danhyun** [comment]
I've submitted a request for Upsource with Jetbrains.
