### ISSUE TITLE
Enhance release process to include publishing Gradle plugins to portal

### ISSUE THREAD

**Issue by davidmc24** [ratpack/ratpack#574]
It looks like 0.9.12 and 0.9.13 aren't in http://plugins.gradle.org/ yet.  This is likely due to missing steps in `RELEASING.md`.

**Comment by danhyun** [comment]
Just capturing steps here, will transcribe to `RELEASING` later.

Navigate to https://bintray.com/ratpack/gradle-plugins-meta/ratpack-java/new/version
Enter version being release.

Navigate to https://bintray.com/ratpack/gradle-plugins-meta/ratpack-java/<version>/edit?tab=general
Add new Attribute:
key: `gradle-plugin`, value: `io.ratpack.ratpack-java:io.ratpack:ratpack-gradle`

Navigate to https://bintray.com/ratpack/gradle-plugins-meta/ratpack-java/<version>/upload
Create a dummy file called `ratpack-java-<version>.txt` and upload.
A UI element will be displayed prompting you to publish, click the link to publish.

Repeat steps for the `ratpack-groovy` and substitute `java` for `groovy` where applicable.

**Comment by alkemist** [comment]
It would be really nice to automate this.

**Comment by ylemoigne** [comment]
The 0.9.15 is not published

**Comment by danhyun** [comment]
Hi @ylemoigne I've just updated bintray, please allow for some time to be synced with the Gradle plugin portal.

**Comment by danhyun** [comment]
Gradle plugin portal is no longer pulling directly from bintray

**Comment by davidmc24** [comment]
Looks like the new instructions are here: https://plugins.gradle.org/docs/submit

**Comment by danhyun** [comment]
We're nearly there, waiting on Gradle to allow upload of signed jars https://issues.gradle.org/browse/GRADLE-3285

**Comment by danhyun** [comment]
And to allow for organizational permissions to upload to plugin portal.
