### ISSUE TITLE
Better ability to compose against the Guice registry

### ISSUE THREAD

**Issue by davidmc24** [ratpack/ratpack#576]
One example of where this would be useful: being able to resolve from the base registry when initially building modules with Guice.  For example, I want to use `ConfigData` in the initialization of components that I'm binding with Guice.  Currently, to do this, I need to bind it in both the base registry and the Guice bindings.

In general, we need better support for composing Guice registries.

**Comment by alkemist** [comment]
@davidmc24 I'm not sure this is an issue anymore.
