### ISSUE TITLE
If URL does not end with '/' path token is treated as null instead of empty

### ISSUE THREAD

**Issue by AlexCzar** [ratpack/ratpack#580]
I don't actually know if this is a bug or an intended behaviour. If it's intended just close this issue and document it somewhere.

```groovy

ratpack {

    handlers {
        get('foo/:tkn?') {
            def start = context.getPathTokens().get('tkn')
            println "Token: $tkn"
            render "bar"
        }
    }
}
```
* for `curl http://localhost:5050/foo` I get `Token: null` logged to the console.
* for `curl http://localhost:5050/foo/` I get `Token: ` as expected.

**Comment by alkemist** [comment]
Hi @AlexCzar I think you made a mistake in your post because both URLs are the same.

Would you mind updating it?

**Comment by davidmc24** [comment]
@AlexCzar Assuming you meant for the second URL to be `http://localhost:5050/foo/`, then I think this is working as intended.

Associated test coverage here:
https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/test/groovy/ratpack/path/internal/TokenPathBinderSpec.groovy#L69

@alkemist Is there somewhere that would be appropriate for documenting the behavior of the default `PathBinder` implementation?

**Comment by AlexCzar** [comment]
@alkemist yes, I've updated it.
@davidmc24 got it, I'll use the test you linked as a reference in the future.

**Comment by alkemist** [comment]
This is an interesting one. I can see how you would want the behaviour of binding whether the / is there or not. 

We could support…`get('foo/?:tkn?')`

**Comment by alkemist** [comment]
@davidmc24 This is an interesting one to try and document. I think it's probably best to document this as a section on the class level doc on `Chain`

**Comment by davidmc24** [comment]
Is the syntax `get('foo/?:tkn?')` intended to represent that the slash is optional?  In this case, I don't think the intention was to match `foobar` with bar as the `:tkn` binding.

**Comment by alkemist** [comment]
It means it would match `foo`, `foo/` and `foo/bar`. Not `/foobar`.

BTW, you can achieve this desired behaviour today by using a regex instead of our custom language here.

**Comment by davidmc24** [comment]
@alkemist I can't figure out a way to achieve this behavior with our current regex support.  Could you provide an example?

**Comment by alkemist** [comment]
I'm assuming we can do it. What did you try?

**Comment by davidmc24** [comment]
I've tried:

* `foo/:tkn:.*`
* `foo/:tkn?:.*`
* `foo:tkn:.*`
* `foo:tkn?:.*`

**Comment by davidmc24** [comment]
I think the new docs probably cover this adequately.
