### ISSUE TITLE
Chain with multiple methods, same path

### ISSUE THREAD

**Issue by asaf** [ratpack/ratpack#584]
Hey,

First, Ratpack seems very lightweight and promising, I started to [blog](http://asaf.github.io/blog/2015/02/15/ratpack_hello_world/) about it and hopefully will put more entries during learning,

Regarding this issue,
I'd like to have multiple handlers for the same path,
Here's a simple example of get / post, same path.

```java
RatpackServer server = RatpackServer.of(b -> b
                        .serverConfig(ServerConfig.embedded()) //default config
                        .registryOf(r -> r.add(String.class, "world"))
                        .handlers(chain -> chain                   
                                        .get("hello", ctx -> ctx.render(ctx.get(String.class) + " !"))
                                        .post("hello", ctx -> ctx.render(ctx.get(String.class) + " !!!"))
                        )
        );
```

Only the first is served, so
GET to /hello works
POST to /hello causes status code 405

Am I missing something in the concept of chains or this is a bug? if it's not, what would be the way to serve multiple methods ?

Thanks.

**Comment by alkemist** [comment]
What you want is…

```

**Comment by asaf** [comment]
(I see empty line)

**Comment by alkemist** [comment]
What you want is…

```
    RatpackServer.start(b -> b
        .serverConfig(ServerConfig.embedded()) //default config
        .registryOf(r -> r.add(String.class, "world"))
        .handlers(chain -> chain
            .handler("hello", ctx -> ctx 
              .byMethod(s -> s
                .get(() -> ctx.render("hello GET"))
                .post(() -> ctx.render("hello POST"))
              )
            )
        )
    );
```

Using .get()/.post() at the chain level doesn't do the same thing. At the chain level, they mean that “this path only responds to this method”. If you respond differently based on method you have to use `.byMethod()` in the handler.

This is because Ratpack uses a graph/pipeline of functions to handle requests instead of a routing table. It takes a little getting used to, and this particular case is a common trap.

We really should make it prominent in the docs.

**Comment by asaf** [comment]
Yap, After some digging into the code I see how the chain graph is produces,

Indeed, chaining requires more clarification in the docs (for example 'byMethod' is not even mentioned in there)

I'm keeping this issue for a reference to improve docs, but feel free to close it though,

Thanks!
Asaf.

**Comment by asaf** [comment]
Yap, After some digging into the code I see how the chain graph is produces,

Indeed, chaining requires more clarification in the docs (for example 'byMethod' is not even mentioned in there)

btw isn't it a major limitation?, rest CRUD usually have same URL with different method, using 'byMethod' is on the context level, forcing you to pass through a single handler for all operations?

I'm keeping this issue for a reference to improve docs, but feel free to close it though,

Thanks!
Asaf.

**Comment by alkemist** [comment]
> btw isn't it a major limitation?, rest CRUD usually have same URL with different method, using 'byMethod' is on the context level, forcing you to pass through a single handler for all operations?

I wouldn't say it's a limitation, just different to how tools like Sinatra express the same thing.

It would be pretty rare to want to express how to deal with the same endpoint but different methods in different parts of the codebase, so having it in one handler isn't really a problem. In some ways, it's more convenient because you can put common logic before the `byMethod` call.

```
RatpackServer.start(b -> b
        .serverConfig(ServerConfig.embedded()) //default config
        .registryOf(r -> r.add(String.class, "world"))
        .handlers(chain -> chain
            .handler("person/:id", ctx -> {
              PersonService service = ctx.get(PersonService.class);
              Person person = personService.get(ctx.getPathTokens().get("id"));

              ctx.byMethod(s -> s
                .get(() -> ctx.render("hello " + person.getName()))
                .post(() -> personService.save(person, ctx.parse(Jackson.fromJson(Person.class)))
              })
            )
        )
    );

**Comment by davidmc24** [comment]
Why would it be forced to be in a single handler?  The `ByMethodSpec` methods can take `Handler`s as arguments.  You can define a separate handler for each HTTP method if desired.

**Comment by asaf** [comment]
Thank you both, folks, we really need to document it, 
at the end, Ratpack's heart is the chain pipeline & handlers.

**Comment by alkemist** [comment]
You could do this:

```
.handlers(chain -> {
  chain.prefix("api", (api) -> api
    .handler("item/:id", MainHandler.class)
  )
)

...

MainHandler implements Handler {
   @Override
    public void handle(Context ctx) throws Exception {
        ctx.byMethod(r -> r
                        .post(ctx.get(AddHandler.class))
                        .delete(ctx.get(DeleteHandler.class))
        );
    }
}
```
