### ISSUE TITLE
Streams/Promise wiretap result terminology

### ISSUE THREAD

**Issue by danveloper** [ratpack/ratpack#589]
The terminology for describing failure and result data differs just slightly between `ratpack.exec.Result` and `ratpack.stream.StreamEvent`, and it makes it slightly confusing when integrating the two types.

Using promises:

```groovy
promise(object)
  .flatMap { ... }
  .map { ... }
  .wiretap { result ->
    if (result.failure) { // (1) -- "result.failure"
      log.error "There was an error", result.throwable
    } else {
      log.info "Captured result", result.value // (2) -- "result.value"
    }
  }
```

Using streams:

```groovy
Streams.constant(object)
  .flatMap { ... }
  .map { ... }
  .wiretap { result ->
    if (result.error) { // (1) -- "result.error"
      log.error "There was an error", result.throwable
    } else {
      log.info "Captured result", result.item // (2) -- "result.item"
    }
  }
```

If there's not a compelling reason for the differences, maybe it would be easier to standardize the terminology here?

**Comment by alkemist** [comment]
We should change `result.failure` to `result.error`. The RS spec uses the term `error` so we can't really change it on that side. The `Result` type is under our control though.
