### ISSUE TITLE
Update Handlebars to 2.0

### ISSUE THREAD

**Issue by skurfuerst** [ratpack/ratpack#590]
Hi,

Handlebars at https://github.com/jknack/handlebars.java is now available in version 2; it would be great if an update would be possible, as it allows quite some nice new features.

Thanks and greets,
Sebastian

**Comment by erdi** [comment]
Had to revert due to the latest antlr on whcih handlebars.java depends causing some compilation warnings and failing the build.

**Comment by davidmc24** [comment]
@skurfuerst The latest ratpack 0.9.16-SNAPSHOT should now use Handlebars 2.0.0.  Please try it out when you have a chance.
