### ISSUE TITLE
Groovy Extensions for RxJava and Reactive Streams

### ISSUE THREAD

**Issue by danveloper** [ratpack/ratpack#595]
[Groovy extensions](http://docs.groovy-lang.org/latest/html/documentation/#_extension_modules) provide the ability to add instance-level "helper" methods to different types. We can use this to make the translation from `Observable` and `Publisher` to `Promise` (and vice-versa) a more-seamless integration for Groovy-based applications.

**Comment by danveloper** [comment]
resolved via https://github.com/ratpack/ratpack/commit/fb9286e5c42e5c3cc5f5dbb2b0641a4aa57ef20d

**Comment by alkemist** [comment]
Where did we land on the version attribute?

**Comment by alkemist** [comment]
Also, needs a milestone set before closing.

**Comment by danveloper** [comment]
@melix informs that the `moduleVersion` field is simply used for reporting purposes. In our case, it seems rather unlikely that an application would pull in two of the same `ratpack-core/rx` jars, so I'm not convinced that we really need it at all. (It works fine without it defined.)

**Comment by davidmc24** [comment]
Really?  I thought it refused to use the module if the `moduleVersion` wasn't defined.

https://github.com/groovy/groovy-core/blob/0b2182bff2250150e69ccb988f367e709b4560de/src/main/org/codehaus/groovy/runtime/m12n/MetaInfExtensionModule.java#L62

**Comment by melix** [comment]
Yes, sorry @danveloper if it wasn't clear: the descriptor and version is required. Groovy will complain if it finds two versions of the same module on classpath.

**Comment by danveloper** [comment]
It does work without it, though: https://github.com/ratpack/ratpack/blob/master/ratpack-rx/src/test/groovy/ratpack/rx/RxAsPromiseSpec.groovy#L49

**Comment by davidmc24** [comment]
Ah, empty string vs. `null`.

**Comment by danveloper** [comment]
Good point -- I should have noted that the field is _present_, but not assigned. We can assign a dummy value if it makes it easier to understand. Thoughts?

**Comment by johnrengelman** [comment]
Might as well call it `1.0.0` since it's our first version. Then if we ever change it, we can up the number.

**Comment by alkemist** [comment]
I'm not as across the details as you guys, but just hardcoding 1.0.0 seems reasonable to me.
