### ISSUE TITLE
Gradle plugin portal not updated

### ISSUE THREAD

**Issue by ylemoigne** [ratpack/ratpack#598]
Hi,

The last available version of `io.ratpack.ratpack-java` available on gradle portal is `0.9.11`
See : https://plugins.gradle.org/plugin/io.ratpack.ratpack-java

**Comment by davidmc24** [comment]
Related: #574

**Comment by alkemist** [comment]
Any volunteers for this one? @danhyun ?

**Comment by danhyun** [comment]
Yep I can take this on.

**Comment by danhyun** [comment]
Should be all set: https://bintray.com/ratpack/gradle-plugins-meta

Just waiting for the plugin portal to pick up new changes.

**Comment by alkemist** [comment]
Thanks @danhyun

**Comment by danhyun** [comment]
Back in business:

![image](https://cloud.githubusercontent.com/assets/1033018/6526883/466d063a-c3e4-11e4-8088-28eb0501827e.png)
