### ISSUE TITLE
Filtering metrics

### ISSUE THREAD

**Issue by gschrader** [ratpack/ratpack#600]
As discussed in the [forum](http://forum.ratpack.io/Preventing-metrics-on-certain-handlers-td911.html). 

Currently metrics are being captured and reported for everything including sensitive handlers such as the pac4j.  There needs to be a way to filter these out.

**Comment by gschrader** [comment]
The reason I was thinking the builder was the way to go was I'd also like to change other properties, i.e. the domain in JmxReporter.  Potentially that could be added to CodaHaleMetricsModule#jmx method but that will quickly become rather unwieldy if people want other options from the reporters added.

**Comment by rhart** [comment]
I can see what you mean.  But it wouldn't take long to add all the extra config options for all reporters. They don't change so it wouldnt be something we'd have to keep on top of.  The benefit I think is that it would play nicer with external config.

I think if we allowed users to provide the reporter's builder instead then there isnt really much value in Ratpack trying to help configure the reporters.  You might as well just do it yourself and remove all the reporter config from the MetricsModule.  Which I'm not saying is a bad idea.

@alkemist do you have an opinion here??

**Comment by gschrader** [comment]
Ok it goes against the DRY principal but you're right they likely won't change much.  I hadn't considered external config, is there an example of modules being configured that way now?

**Comment by rhart** [comment]
https://github.com/ratpack/example-books/blob/master/src/ratpack/ratpack.groovy and the spec https://github.com/ratpack/ratpack/blob/master/ratpack-codahale-metrics/src/test/groovy/ratpack/codahale/metrics/MetricsExternalConfigSpec.groovy

**Comment by gschrader** [comment]
Thanks, my bad I wasn't looking at the latest code :blush:. I see how things are configured now.  Ok I know enough now to be dangerous I'll see if I can find some time this weekend to add the filtering config options and will submit a PR.

**Comment by rhart** [comment]
Great stuff

**Comment by gschrader** [comment]
PR is [here](https://github.com/ratpack/ratpack/pull/605)

**Comment by alkemist** [comment]
@rhart this is resolved by #605 right? If so, can you please close.
