### ISSUE TITLE
Request metrics timer name

### ISSUE THREAD

**Issue by rhart** [ratpack/ratpack#602]
Currently a GET request to `/author/1/books` would produce a timer name of 
`[author][1][books]~GET~Request`.  Do we want to change this before 1.0?  It currently also includes querystring parameters which I think we defo want to remove, as pointed out by @gschrader.

For me the questions are:

1. Is "Request" ok as a suffix or should it be a prefix?  Is request even right, should it be response?
1. Is separating paths with `[]` ok or does `.` make more sense e.g. `author.1.books.GET.Request`
1. Should we include the HttpMethod in the name?
1. Does it make sense to also include a counter of response statuses for requests e.g. `status.200.author.1.books=10`

@gschrader @kyleboon do you have any feedback regarding this?

**Comment by kyleboon** [comment]
This is what you get out of the box with dropwizard:

```
"timers" : {
    "com.example.helloworld.resources.HelloWorldResource.get-requests" : {
      "count" : 1,
      "max" : 0.005472,
      "mean" : 0.005472,
      "min" : 0.005472,
      "p50" : 0.005472,
      "p75" : 0.005472,
      "p95" : 0.005472,
      "p98" : 0.005472,
      "p99" : 0.005472,
      "p999" : 0.005472,
      "stddev" : 0.0,
      "m15_rate" : 0.001053991118789713,
      "m1_rate" : 0.007553668846787294,
      "m5_rate" : 0.0028452503068887463,
      "mean_rate" : 0.016464888091037,
      "duration_units" : "seconds",
      "rate_units" : "calls/second"
    },
```

You also have these for response codes application wide:

```
    "io.dropwizard.jetty.MutableServletContextHandler.1xx-responses" : {
      "count" : 0,
      "m15_rate" : 0.0,
      "m1_rate" : 0.0,
      "m5_rate" : 0.0,
      "mean_rate" : 0.0,
      "units" : "events/second"
    },
    "io.dropwizard.jetty.MutableServletContextHandler.2xx-responses" : {
      "count" : 3,
      "m15_rate" : 0.0031974338796972755,
      "m1_rate" : 0.027019268291840363,
      "m5_rate" : 0.008828340014576753,
      "mean_rate" : 0.04940245995597154,
      "units" : "events/second"
    },
    "io.dropwizard.jetty.MutableServletContextHandler.3xx-responses" : {
      "count" : 0,
      "m15_rate" : 0.0,
      "m1_rate" : 0.0,
      "m5_rate" : 0.0,
      "mean_rate" : 0.0,
      "units" : "events/second"
    },
    "io.dropwizard.jetty.MutableServletContextHandler.4xx-responses" : {
      "count" : 0,
      "m15_rate" : 0.0,
      "m1_rate" : 0.0,
      "m5_rate" : 0.0,
      "mean_rate" : 0.0,
      "units" : "events/second"
    },
    "io.dropwizard.jetty.MutableServletContextHandler.5xx-responses" : {
      "count" : 0,
      "m15_rate" : 0.0,
      "m1_rate" : 0.0,
      "m5_rate" : 0.0,
      "mean_rate" : 0.0,
      "units" : "events/second"
    },
    "io.dropwizard.jetty.MutableServletContextHandler.async-dispatches" : {
      "count" : 0,
      "m15_rate" : 0.0,
      "m1_rate" : 0.0,
      "m5_rate" : 0.0,
      "mean_rate" : 0.0,
      "units" : "events/second"
    },
    "io.dropwizard.jetty.MutableServletContextHandler.async-timeouts" : {
      "count" : 0,
      "m15_rate" : 0.0,
      "m1_rate" : 0.0,
      "m5_rate" : 0.0,
      "mean_rate" : 0.0,
      "units" : "events/second"
    }
```

I think the current naming convention is too fined grained. Perhaps rather than the URL, the handler that committed the response could be used instead?

**Comment by rhart** [comment]
The problem with using handler is 2 requests might be finally responded to by the same handler but one gone through 10 handlers previous and the other none. Are you interested in comparing those 2 requests in the same metric? That's why I thought url was better, it's more comparable. Although I guess they could equally  go through a different handler path

**Comment by kyleboon** [comment]
Each individual URL is hard to deal with... for cellarhq I want to know how the show beer page performs in general, and combining across thousands of individual urls is a pain.

I wonder if ratpack could somehow learn and name distinct paths through the system?


Most of the time I would think the handler that commits the response is the one that did most of the work, but i suppose not always. Maybe measuring each handler individually is the way to go?

**Comment by kyleboon** [comment]
Or what if you configured the module with a set of url patterns to collapse into.

/*
/beer/*
/brewery/*
/cellar/*

etc ?

**Comment by kyleboon** [comment]
Also I think have a count of the number of times each handler was called and the amount of time spent would be useful

**Comment by alkemist** [comment]
The core problem is that we can't know ahead of time what a meaningful identifier is for the “handling”. Other frameworks use the identity of the controller/controller-method. We don't have an analogue.

We can flip this around and have the user give the identifier. We'd put something in the request registry for this, something like…

```
interface HandlingPath {
  void mark(String name)
}
```

At any point in the pipeline the path can be “marked”…

```
chain.handler(ctx -> { ctx.getRequest().get(HandlingPath.class).mark("beer"); ctx.next() }).get(…);
```

We could sugar that in a bunch of ways…

```
chain.prefix("beer", beerChain -> beerChain.mark("beer").get(…).post(…)) 
```

There's a bunch of other ways we could sugar I think.

The obvious downside here is that it's not automatic. We could possibly make it more “automatic” by baking this concept in a little deeper. I'd probably go for something like “checkpoints”. Basically, during a request you'd be able to indicate that a checkpoint was hit in the handler chain. We'd add overloads to the chain DSL to associate handlers with checkpoints, as well as being able to programmatically “mark” checkpoints.

Rough sketch…

```
package ratpack.handling

interface Checkpoints {
  void mark(String checkpointName)
  List<MarkedCheckpoint> getMarked()
}

interface MarkedCheckpoint {
  String getName()
  long getNanos() // nanoseconds from receipt of request until mark
}

// on Context
Checkpoints getCheckpoints() {
  request.get(Checkpoints.class)
}
```

For the metrics integration, we'd add an `onClose` to all requests to copy their checkpoint data across to the timers.

**Comment by rhart** [comment]
Url patterns to collapse into is doable.  So if the current request matches a pattern it will get logged as that, otherwise the full path will be used.  and the format will be: 
`beer.get-requests`
`brewery.get-requests`
`admin.users.get-requests`

Where there is blocking the additional metric would be `beer.get-requests.blocking`

Application wide response code count can also be swepts up in this ticket.

I think I'll resurrect #171 for the handler stuff and add the CheckPoint details there.  Which I think is a great idea.

**Comment by gschrader** [comment]
Oops sorry I missed your request for feedback.  The important thing was dropping the query string.  I personally wouldn't care too much about status codes but I think the http method is important.  I think a `.` separator makes more sense. I recall playing around with the GraphiteReporter in another project and one of the dashboards I was using was able to group metrics nicely because of the `.` notation.

**Comment by rhart** [comment]
You can see how to collapse urls here https://github.com/ratpack/example-books/blob/latest/src/ratpack/application.properties#L8

Any feedback would be great @kyleboon @gschrader
