### ISSUE TITLE
First build of Ratpack on Windows requires using Bash and admin account

### ISSUE THREAD

**Issue by gillius** [ratpack/ratpack#607]
I did a clean clone of the project and tried gradlew openManual and I get:

```
:ratpack-manual:compassCompile
ERROR:  Loading command: install (LoadError)
        Could not load FFI Provider: (NotImplementedError) FFI not available: null
 See http://jira.codehaus.org/browse/JRUBY-4583
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

I did go to the JRUBY JIRA URL posted and it wasn't much help, it basically says compile FFI for other platforms, but I'm Windows x86-64, which is listed in that ticket as working (and the ticket is closed anyway).

**Comment by danhyun** [comment]
Hi, how are you running this task? Via cmd, powershell, git bash? I've ran into this as well with git bash but when I run as administrator it clears everything up.

**Comment by gillius** [comment]
I ran it via cmd as a user with admin privileges but UAC is active as normal on Windows so I wasn't admin at the time. I launched an admin command prompt and ran the same command and it went farther. It's pretty bad if a build requires admin/root though?

```
    java -jar C:/Users/Gillius/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/1.7.15/4d9cb332bad3633c9c23a720542f456dc0c58a81/jruby-compl
ete-1.7.15.jar extconf.rb
'java' is not recognized as an internal or external command,
operable program or batch file.
```

This is funny because java is on my Windows path and `java -version` returns 1.8.0_31, so it should be possible to run "java" directly.

I then tried running through git bash AND as administrator and it worked. That's not really cool... This would turn away some contributors I think.

Once the jruby gems installed, I'm able to run as a normal user and under cmd.

If this is really something that can't be resolved can we edit the ratpack-manual/README.md to say on Windows at least for the first build you must use bash and you must run that bash as admin?

**Comment by danhyun** [comment]
I haven't tracked this one down yet but it is a bit of a pain to get past this on Windows. There is an alternative solution to compiling SASS on the way via asset pipeline which may help us get past this.

I'll update the `README` to denote this.

**Comment by alkemist** [comment]
@danhyun what's the status here?

**Comment by danhyun** [comment]
This is still an issue. I'll update the guide to mention this.

**Comment by danhyun** [comment]
The `README` has been updated, I'm going to close this until we have an alternative solution or until the JRuby issue is resolved.
