### ISSUE TITLE
Dependency on SNAPSHOT versions of io.netty stuff fails

### ISSUE THREAD

**Issue by davidtinker** [ratpack/ratpack#609]
I created a Ratpack Groovy project (0.9.14, Gradle 2.3) following the instructions in the manual and did "gradle run":

   > Could not find io.netty:netty-handler:4.1.0.Beta4-SNAPSHOT.
     Searched in the following locations:
         https://jcenter.bintray.com/io/netty/netty-handler/4.1.0.Beta4-SNAPSHOT/maven-metadata.xml
         https://jcenter.bintray.com/io/netty/netty-handler/4.1.0.Beta4-SNAPSHOT/netty-handler-4.1.0.Beta4-SNAPSHOT.pom
         https://jcenter.bintray.com/io/netty/netty-handler/4.1.0.Beta4-SNAPSHOT/netty-handler-4.1.0.Beta4-SNAPSHOT.jar
     Required by:
         :mashtemp:unspecified > io.ratpack:ratpack-core:0.9.14

If I downgrade to Ratpack 0.9.11 the error goes away. 0.9.12 and 0.9.13 have the same issue.

**Comment by rhart** [comment]
Unfortunately those Ratpack versions depend on a Netty snapshot and you need to include the following maven repo `maven { url 'http://clinker.netty.io/nexus/content/repositories/snapshots' }`

The manual hasn't been updated with this instruction but the lazybones templates should work without any change. 

As of 0.9.15 you won't need to do this as there is now a 4.1.0 release for us to use.

**Comment by alkemist** [comment]
Fixed in next release.
