### ISSUE TITLE
Exception when launching from jar and using CodaHaleMetricsModule

### ISSUE THREAD

**Issue by danthegoodman** [ratpack/ratpack#610]
I am trying to start a server when `Ratpack.groovy` is inside a jar. Using the CodaHaleMetricsModule causes an `UnsupportedOperationException` to get thrown.

I forked the example gradle app and added shadow and the metrics to it. You can reproduce the stacktrace using `./gradlew runShadow`: https://github.com/danthegoodman/example-ratpack-gradle-groovy-app/tree/metrics_and_shadow

Ratpack Version: `0.9.14`
JVM: `1.8.0_31 (Oracle Corporation 25.31-b07)`
OS: `Mac OS X 10.10.2 x86_64`

According to the stacktrace, the error comes from the `CsvReporterProvider`:

```text
1) Error injecting constructor, java.lang.UnsupportedOperationException
  at ratpack.codahale.metrics.internal.CsvReporterProvider.<init>(CsvReporterProvider.java:37)
  while locating ratpack.codahale.metrics.internal.CsvReporterProvider
  at ratpack.codahale.metrics.CodaHaleMetricsModule.configure(CodaHaleMetricsModule.java:465) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> ratpack.codahale.metrics.CodaHaleMetricsModule)
  while locating com.codahale.metrics.CsvReporter

...

Caused by: java.lang.UnsupportedOperationException
  at com.sun.nio.zipfs.ZipPath.toFile(ZipPath.java:597)
  at ratpack.codahale.metrics.internal.CsvReporterProvider.<init>(CsvReporterProvider.java:40)
```

**Comment by johnrengelman** [comment]
Does it change if you add the following to `build.gradle`?
```
shadowJar {
  mergeServiceFiles()
}
```

**Comment by johnrengelman** [comment]
Hmmm, that probably doesn't make a difference. Sorry, thought I saw something right away.

Appears that the problem is that the `CsvReporterProvider` tries to cast the `baseDir` to a `File`. In the case of running from a shadowJar, this wouldn't be valid.

**Comment by danthegoodman** [comment]
Taking a look at the provider, it looks like the default report directory is only going to get used when a csv config hasn't been provided. 

If a CSV config isn't provided, would it be acceptable to throw an exception instead of assuming the user wants the csv reports in their base directory? Besides, won't the existing code fail when someone builds a ServerConfig with `noBaseDir()`?

```java
public CsvReporter get() {
  Csv csv = config.getCsv()
    .orElseThrow(()-> new IllegalStateException("CodaHaleMetricsModule must have a csv configuration to provide a CsvReporter"));
  return CsvReporter.forRegistry(metricRegistry).build(csv.getReportDirectory());
}
```

**Comment by davidmc24** [comment]
I think that @danthegoodman is on the right path.  Similar to `CsvReporter` by itself, we should require specifying the report dir if CSV reporting is to be used.  If we don't, the possible values we could use are either the file system binding (which may or may not be an actual directory, and may or may not be writeable), or the current directory (which may or may not be writeable).  I don't think that either of those defaults is a clear "right" choice.  If we require specifying the value, we can at least provide consistent behavior and clear messaging if it won't work.

**Comment by danthegoodman** [comment]
Until this is fixed, here is a workaround:

```
// in your bindings block
add new CodaHaleMetricsModule()
provider CsvReporterProvider, new Fix_CsvReporterProvider_Provider()

// elsewhere
private static class Fix_CsvReporterProvider_Provider implements Provider<CsvReporterProvider> {
  @Override
  CsvReporterProvider get() {
    def serverConfig = ServerConfig.baseDir(Paths.get('/tmp')).build();
    return new CsvReporterProvider(null, null, serverConfig){
      CsvReporter get() { 
        return null 
      }
    }
  }
}

**Comment by alkemist** [comment]
Thanks @danthegoodman
