### ISSUE TITLE
Add support for fragments in the Thymeleaf module

### ISSUE THREAD

**Issue by tomakehurst** [ratpack/ratpack#619]
I'd like to be able to return an HTML fragment from an XHR request.

Thymeleaf supports supplying an `IFragmentSpec` parameter when processing templates so it would seem to make sense to add this as an optional property on `Template`, possibly with a constructor overload to pass a String fragment spec.

If you think this is reasonable I'm happy to submit a PR.

**Comment by alkemist** [comment]
Change makes sense to me.  +1

**Comment by beckje01** [comment]
Closing this as the PR was merged already.
