### ISSUE TITLE
NettyHandlerAdapter.sendError doesn't actually send the error

### ISSUE THREAD

**Issue by willisblackburn** [ratpack/ratpack#620]
The method includes this code:

    // Close the connection as soon as the error message is sent.
    ctx.write(response).addListener(ChannelFutureListener.CLOSE);

However, it doesn't actually send the response.  If control reaches this line, Ratpack sends no response, and the client eventually times out.

I was able to reproduce this by using curl to send a request with a very large (>8K) header:

    $ BIG=(at least 8K of data--maybe `cat somefile.txt`)
    $ curl -b "BIG=$BIG" http://the.ratpack.server.com/anything

Netty generates an invalid request, which gets handled by NettyHandlerAdapter.channelRead0, which calls sendError.  I traced the call into ChunkedWriteHandler, which queues the response, however, the queue is never flushed.

Netty's own file server has code that is very similar to the code in sendError, however, Netty calls writeAndFlush instead of just write.  I suspect that's what's needed here.

https://github.com/netty/netty/blob/master/example/src/main/java/io/netty/example/http/file/HttpStaticFileServerHandler.java

**Comment by willisblackburn** [comment]
I changed the method to call writeAndFlush, and it fixed the issue.

By the way, if the problem was that the header was too large, maybe send 413 instead of 400?

**Comment by alkemist** [comment]
Thanks for the fix.

AFAICT, there's no easy way to be informed by Netty why decoding failed.

**Comment by willisblackburn** [comment]
We're using Ratpack 0.9.11 because due to another dependency we can't upgrade to Netty 4.1 yet.  Any chance you could publish a patch release for 0.9.11 (0.9.11.1 or whatever) that includes this fix?

**Comment by alkemist** [comment]
I'd really rather not if we can avoid it.

Could you publish a patched version internally?

**Comment by willisblackburn** [comment]
Ever work in big company IT?  :-)  It would take me a week to create a new project set up for the modified Ratpack and get it published to our internal repository.

I pulled the file into my own project, which works for development.  In our production environments we use a wildcard classpath ("lib/*") and so there's no guarantee that the classloader will find the modified class from my jar before finding the original version in the Ratpack jar.  But I can probably hack something up... maybe stick the modified class file into the "etc" directory, which always gets added to the start of the class path.

**Comment by alkemist** [comment]
I have. 

Ratpack works on volunteer time, and back porting bug fixes is a time sink. I'd rather invest the small amounts of time we have on going forward, so don't want to set the precedent of back porting fixes. 

Post 1.0 will probably be a different story.
