### ISSUE TITLE
Upgrade pac4j to 1.7.0

### ISSUE THREAD

**Issue by davidmc24** [ratpack/ratpack#628]

**Comment by leleuj** [comment]
Hi,

I'm finally back on Ratpack.
I was about to update the `ratpack-pac4j` module to the `pac4j` version 1.7 but I noticed it has already been done: https://github.com/ratpack/ratpack/commit/55f96aef5223f3d691ee8fba5b429ff4ae175352. Great!

I realized that things have changed a lot as I'm trying to update my demo: https://github.com/pac4j/ratpack-pac4j-demo.

Here is the current PR of the update: https://github.com/pac4j/ratpack-pac4j-demo/pull/2

I have the error: *Default production error handler used to render client error, please add a ratpack.error.ClientErrorHandler instance to your application (method: GET, uri: /)* even if it is defined here: https://github.com/pac4j/ratpack-pac4j-demo/pull/2/files#diff-902b01aee92ec6ea5ce6845b066c9e40R59
There isn't any mention of how to define the `ClientErrorHandler`, whether it is in the manual or in the API. Or I missed it.
Even at DEBUG level, I have nothing else. It's a bit tough. Any help will be appreciated.

As a suggestion on the `ratpack-pac4j` module, I think the `SessionConstants` could be removed by using the `Pac4jConstants` class.

The source code in the `ratpack-pac4j` module feels pretty complicated (especially the `Pac4jCallbackHandlerBuilder`) regarding the fact that the handler concept is really close to a simple J2E servlet and the `j2e-pac4j` library is more straight-forward (https://github.com/pac4j/j2e-pac4j). Generally, two filters / handers are enough: one to protect, one to finish the remote authentication process.
That being said, I like the `Authorizer` concept which can use the roles and permissions attached to the user profile.

In its latest version (1.7), `pac4j` aims to also handle direct authenticated calls (in addition to the stateful mechanism for CAS, OAuth, OpenID...) The idea would be to improve the `Pac4jAuthenticationHandler` to make it able to handle such scenario, like the `RequiresAuthenticationFilter` for J2E for example: https://github.com/pac4j/j2e-pac4j/blob/master/src/main/java/org/pac4j/j2e/filter/RequiresAuthenticationFilter.java.

Just let me know how do you feel about that.

Thanks.

Unfortunately, the great Javadoc of the Pac4j modules has disappeared...

**Comment by alkemist** [comment]
@davidmc24 as you've got a much better grip on pac4j than I, are you able to answer @leleuj 's questions?

**Comment by davidmc24** [comment]
I should be able to take a look at it this weekend.

**Comment by davidmc24** [comment]
@leleuj Thanks for the suggestion on using `Pac4jConstants`.  That change is live in the current snapshot.  I added new examples to the module javadocs; they were accidentally lost in a previous refactor.  I've sent you a pull request with some fixes to your demo work.  That might be enough to get you back to making progress; if not, please let me know.

https://github.com/leleuj/ratpack-pac4j-demo/pull/1

**Comment by leleuj** [comment]
@davidmc24 : thanks for your help. I finally made the demo work, but things are a bit tricky: I put the redirections computation in a blocking context, not easy to guess: https://github.com/pac4j/ratpack-pac4j-demo/blob/master/src/main/java/org/leleuj/IndexHandler.java#L57.

I don't see any logs on `ratpack-pac4j`: is it on purpose or do you need some help for that?

I'll open an issue on documentation as well.

**Comment by davidmc24** [comment]
I don't think I see a need for that section to be in a blocking context (though it's possible I'm missing something). What behavior were you seeing without it?

No particular reason for the current logging or lack thereof. It's possible that when I first worked on this, we hadn't yet standardized on a logging approach.

**Comment by leleuj** [comment]
If I don't have a blocking context, the demo seems to be blocked somewhere in the redirections computations, from time to time, stopping at on one of the `getRedirectionUrl` methods (not always the same).
I found out the solution by looking at: https://github.com/ratpack/ratpack/blob/master/ratpack-pac4j/src/main/java/ratpack/pac4j/internal/Pac4jAuthenticationHandler.java#L73...

**Comment by davidmc24** [comment]
@alkemist does that sound right to you?

**Comment by leleuj** [comment]
Any news on this?

**Comment by alkemist** [comment]
@leleuj can you try with the latest version?
