### ISSUE TITLE
Favor most-specific renderer implementation

### ISSUE THREAD

**Issue by danveloper** [ratpack/ratpack#642]
Presently, a call to do `context.render(obj)` will check all `Renderer` instances and do an assignability check against the renderer's `type` and the object to be rendered. It would be nice to have the most-specific renderer favored as the primary.

For example, given:

```java
public interface ModelObj {}
```

```java
public class ModelObjImpl implements ModelObj {}
```

```java
public class DefaultModelObjRenderer implements Renderer<ModelObj> {
 ...
}
```

```java
public class ModelObjImplRenderer implements Renderer<ModelObjImpl> {
  ...
}
```

It would be ideal to have `ModelObjImplRenderer` used over `DefaultModelObjRenderer` when the object is _actually_ a `ModelObjImpl`. Thoughts?

**Comment by alkemist** [comment]
Two problems with this:

1. It increases the cost of rendering as we have to do a type comparison against every renderer
2. We have to come up with some type-distance calculation algorithm

(2) is probably not so bad as there will be some around we can borrow. I'm not sure how we quantify (1).

I'm not strictly against doing this, but want to make sure we have a good reason first.

**Comment by danveloper** [comment]
I think if we change the `Renderer` "storage" mechanism to index by type, then we can get some good performance gains against the existing mechanism as well. What I'm thinking would be having something equivalent to a `RendererRegistry` or `RendererTable` within the `Registry` that provided a type => Renderer lookup mechanism. This would allow us, within the `RendererController` to traverse the object's class-hierarchy until the most-specific `Renderer` was found.

pseudo-code:
```
def getRenderer(Class klazz) {
  def lookupTable = registry.get(RendererTable)
  if (lookupTable.hasRendererFor(klazz)) {
    lookupTable.getRendererFor(klazz)
  } else {
    getRenderer(klazz.getSuperClass())
  }
}
```

**Comment by alkemist** [comment]
This is at a pretty high cost, as it introduces an orthogonal mechanism for renderer lookups and renderer registration.

It's also not likely to actually save that much, as we still effectively need to get all of the renderers and score their type against the target type and then use the “best” score.

What was your original use case? Could you not be more precise with the order in which you register the renderers?

**Comment by alkemist** [comment]
@danveloper where did we land on this?
