### ISSUE TITLE
Current way to specify an HTTP status with type safety uses an internal class

### ISSUE THREAD

**Issue by tomakehurst** [ratpack/ratpack#649]
The docs say:
``` java
Status status = new DefaultStatus(HttpResponseStatus.FOUND);
```
where ``DefaultStatus`` is an internal class.

Feels like having a static factory method and a bunch of constants for common values on ``Status`` would be better.

Thoughts?

**Comment by alkemist** [comment]
Which docs? This is definitely wrong. Under what circumstance do you need to create a `Status`?

**Comment by tomakehurst** [comment]
It's under the Forms section of the HTTP chapter.

We'd like to be able to set the status in a type-safe fashion, rather than just via an int.

**Comment by alkemist** [comment]
Yeah, this is all a bit weird.

I think we should keep the API as it is, but add a bunch of static methods to `Status`…

```
interface Status {
  // ...

  Status ok(); // 200
  Status ok(String message); // 200 with custom message

  Status notFound(); // 404
  Status notFound(String message); // 404 with custom message

  // arbitrary status factory
  Status of(int code, String message);
}
```

Up for a PR?

**Comment by tomakehurst** [comment]
Sure, will do.
