### ISSUE TITLE
HttpClient does not decompress responses

### ISSUE THREAD

**Issue by kewne** [ratpack/ratpack#650]
When submitting a request with ```Accept-Encoding``` HTTP headers and the response does come compressed, calling ```ReceivedResponse.getBody.getText()``` yields garbled (compressed) text.

I've worked around this by subclassing DefaultHttpClient and ContentAggregatingRequestAction in my project to add Netty's HttpContentDecompressor to the pipeline, but I think having support for this directly in Ratpack would the best behavior, since the current one is a bit unexpected (in my case, I was proxying requests and missed it because I wasn't setting the header explicitly).

I can make a pull request with my fix (a one-liner), although I'd probably need to work out some tests too.

**Comment by rhart** [comment]
A PR with some tests would be great!  

We also need to consider what we do with streaming as well.  And, if we are proxying and the client sends `Accept-Encoding` do we want to decompress just to compress again?

**Comment by kewne** [comment]
I missed that decompress to compress scenario...
How about treating it as two separate scenarios?

1. Requests that are used by the app itself.
These should always perform decompression if the response comes with a ```Content-Encoding``` header (at least I can't think of a reason not to).
This is essentially what is implemented and my patch would handle it.
2. Requests that are piped directly to the response sent to the original client, which might not need decompression.

I'm not sure every application will need option 2 though that's my use case.
What I'm trying to do is proxy two systems so I can "copy"  the request and response, like an aspect or interceptor.
The way I would go at this would be to create special proxying methods on ```HttpClient``` (or something like a ```ProxyingEnabledHttpClient```), what do you think?

**Comment by rhart** [comment]
There's another proxy use case.  Original client doesn't accept gzip, our app requests gzip (because we can deal with it) and has to decompress before sending back.

I wonder whether we can just add it as an option to `RequestSpec`.  By default we would decompress the response but we could do
```
      get { HttpClient httpClient ->
        httpClient.requestStream(otherAppUrl("foo2")) {
          it.decompress(false)
        } then { StreamedResponse responseStream ->
          responseStream.send(response)
        }
      }
```

What I'm not sure about is what happens when we try to send an already compressed response.  Whether we try to double compress.  Can't remember how that works exactly.

**Comment by kewne** [comment]
That would fall under my second scenario.
To make it clearer, I'm thinking of something like this:

    get { HttpClient httpClient ->
        httpClient.requestAndPipe(response, otherAppUrl("foo2")) {
            // change request headers as usual
        } then { StreamedResponse response ->
            // we can't allow response.send because it's already done
        }
    }

Anything else would require some massive overhaul of the internals in my opinion.

Getting proxies right is hard because the issue with content-encoding extends to a lot of things (media types, chunking, etc. ).
As a user, I wouldn't want to have to deal with this complexity and, if I'm not mistaken, Ratpack already negotiates media types so this would be a nice fit.

For now, how would you feel about always enabling decompression (and recompressing if necessary) to fix the current behavior and keep discussing this until we find a better a solution?

**Comment by rhart** [comment]
I don't think adding a new option to `RequestSpec` would mean a massive overhaul.  Just dynamically adding `HttpContentDecompressor` to the pipeline.  And any other complexities of proxying hidden in `StreamedResponse#send`.  What would `requestAndPipe` do?  just have `HttpContentDecompressor` already in the pipeline?   I guess it would be good to work something up.

Always enabling decompression for now seems reasonable to me though.  @alkemist do you have an opinion here?

**Comment by alkemist** [comment]
We should just always enable it. It's benign if the response isn't actually compressed. I don't see the benefit of making it optional.

**Comment by rhart** [comment]
The benefit of an optional decompress is in the case where we're proxying and don't need to inspect the response before sending it on.  Decompressing just to compress again on the way out is an unnecessary step and an increase in memory footprint.

But the benefit is probably very marginal, the use case an edge one, and we can just come back to this if/when the need arises.

**Comment by alkemist** [comment]
We should arrange things so we know up front if we are proxying, and not put the decompressor in in that case.

**Comment by rhart** [comment]
That's where I was going with adding it as an option on RequestSpec and removing the decompressor from the pipeline if we don't want it.  But there are probably better ways to achieve this and make the fact that we're proxying more explicit.

**Comment by kewne** [comment]
That's why I suggested ```requestAndPipe``` (although the idea is half-baked at this point), so the API user doesn't need to negotiate such things manually.
As it is now, by the time the user calls ```response.send(request)```, the decision to decompress or not has already been made.

A ```requestSpec.compress(true)``` might not be needed: if we can access the original request, the user can set the requestSpec however he wants and Ratpack negotiates the details underneath.
There's a lot to handle here but we can address it as it comes up, what do you think?

**Comment by rhart** [comment]
> As it is now, by the time the user calls response.send(request), the decision to decompress or not has already been made.

Yes, but you're able to make that decision on receiving the original request before sending the proxy request.

I think I see what you're saying more now though.  It's the difference between enabling users to write proxy apps vs taking care of the proxying for them

If that's the case then another option to consider is creating a handler for this rather than try to do it as part of http client.

Either way, sounds like a separate ticket to me.

**Comment by rhart** [comment]
This is closed by https://github.com/ratpack/ratpack/pull/651
