### ISSUE TITLE
Manual: Suggest reordering 2.1 and 2.2

### ISSUE THREAD

**Issue by saanvik** [ratpack/ratpack#653]
After completing section 2.1 (" Using the Gradle plugin(s)"), section 2.2 ("Using a Groovy script") feels out of place.  We've already created, in 2.1.2, a ratpack app with a Groovy script.  

The last line of 2.1.2 is "For further information on using Ratpack with Groovy, please the Groovy chapter" but that line is immediately followed by  section 2.2 "Using a Groovy script"; which is confusing.

**Comment by alkemist** [comment]
The idea of chapter 2 is that it gets you up and running in one of a few different ways. The point is to avoid details, but just get an app running and then link through to detail elsewhere.

If that was clearer, would that allay your concerns?

**Comment by saanvik** [comment]
The motivation is clear, that's not the problem.  It's more of a structural problem.  

There's three different ways to quickly get started.  One of them, section 2.1.2 suggests that you're done with groovy, but then it's immediately followed by groovy code.  Later, section 2.2, tells you how to get started "Using a Groovy script" but you've already used a groovy script, in conjunction with gradle.  

If you moved Section 2.2 in front of 2.1, then the text could remain the same and that structural collision wouldn't happen.  It'd be easier for the reader to grok.

**Comment by alkemist** [comment]
@saanvik seems like a good idea. Would you mind submitting a PR for this?

**Comment by saanvik** [comment]
Sorry it took a bit to get to this.  Pull request at https://github.com/ratpack/ratpack/pull/667
