### ISSUE TITLE
Should be able to override Pac4j callback

### ISSUE THREAD

**Issue by danveloper** [ratpack/ratpack#655]
If I need to discriminate a successful authentication based on some parameters of the user profile (domain, for example), then I'll need to override the `onSuccess` of the `Pac4jCallbackHandler`. Presently, there is no way to do this.

**Comment by davidmc24** [comment]
If you use `Pac4jCallbackHandlerBuilder`, you can specify the `onSuccess` behavior.

**Comment by danveloper** [comment]
Sort of...

the `Pac4jHandlerDecorator`, which applies the [`Pac4jCallbackHandler`](https://github.com/ratpack/ratpack/blob/f255fcf34ded2c636d28a1c216a245b213bf976a/ratpack-pac4j/src/main/java/ratpack/pac4j/internal/AbstractPac4jModule.java#L111) explicitly specifies a `new Pac4jCallbackHandlerBuilder().build()`, so no way to hook into the `onSuccess` behavior here...

Also, the `AbstractPac4jModule` provides a [`protected` method for overloading this, but specifies a `private` return type](https://github.com/ratpack/ratpack/blob/f255fcf34ded2c636d28a1c216a245b213bf976a/ratpack-pac4j/src/main/java/ratpack/pac4j/internal/AbstractPac4jModule.java#L90), making subclassing impossible.

**Comment by davidmc24** [comment]
What I meant is that if you use the `Pac4jCallbackHandlerBuilder ` directly (not via one of the pre-baked modules), you can specify this behavior.  In the intended refactor, we'd be moving more towards this sort of builder pattern, and possibly removing the modules.

**Comment by danveloper** [comment]
Awesome, sounds great, @davidmc24! Thanks

**Comment by alkemist** [comment]
Rolling this into #552
