### ISSUE TITLE
Streams does not canceled when sse connection is closed (prematurely).

### ISSUE THREAD

**Issue by niwibe** [ratpack/ratpack#659]
Hi! I have some trouble with SSE (and maybe with any stream based responses) handlers. Seems that when connection is closed (prematurely), the `cancel()` method of subscription is never executed.

Here a little project for reproduce it: https://github.com/niwibe/ratpack-sse-streams-not-cancels
Just run `gradle run` and then the server is up and running, just execute: `curl -i http://localhost:5050/events` wait an event and close it with "Ctrl+C". You can observe that "cancel" is not printed in the console when the server is running (I have experimented the same behavior using browser instead of curl).

The project is based on the "quick start" of the ratpack documentation with very basic (and surelly buggy) publisher and subscriber implementation that sends the current timestamp to the subscribed clients.

**Comment by rhart** [comment]
Thanks for the project, I was able to reproduce.  It's very difficult to write a test for but I think I know what the issue is.  Will try and get something for you to try tomorrow.

**Comment by niwibe** [comment]
Awesome! Thanks!

**Comment by rhart** [comment]
When the build has finished you can try with the latest snapshot.  And reopen if there's still a problem.

**Comment by niwibe** [comment]
Works perfectly! Thanks!

**Comment by rhart** [comment]
Thanks for confirming. Happy Ratpacking :)
