### ISSUE TITLE
Construct for async actions that don't produce values

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#660]
We have `Promise` for asynchronously produced single value, and `Publisher` for multi values. We are missing a construct for an async action that produces no values.

Options:

1. We go with Promise<Void>
2. ExecControl.nest(Block someAction, Block then)
3. Introduce AsyncAction, which is like Promise, but no operations

For 2, the caller of the action would have to no it was async and act accordingly (i.e. no type safety).

For 3, the implementor has to return the code, instead of just doing it. That’s a bit of a pain. In that respect, it’s no different to 1 though.

**Comment by niwibe** [comment]
In my opinion, the Promise<Void> should be used. Having different types for the same purpose but with different value (or absense of value) does not have benefits, but having only one type, has the benefit that the user should not think about different kind of types.

**Comment by alkemist** [comment]
The big downside to the `Promise<Void>` approach though is that you have `null` flying all over the place. It is looking like the most promising option though at this point.

**Comment by danhyun** [comment]
Is this not addressed via `Operation` now?

**Comment by alkemist** [comment]
It is, but the class needs some docs.

**Comment by danhyun** [comment]
Got it, I can tackle tonight.
