### ISSUE TITLE
Provide serialization options for ClienSideSessionModule

### ISSUE THREAD

**Issue by danhyun** [ratpack/ratpack#664]
As mentioned in #504, pac4j does not work if the value stored in the session is a String so we should provide different serialization options to the user based on the user's requirements.

We should provide a Java serialization option as well as a String serialization option. As a part of this effort we should write tests to ensure that the Java serialization will enable good integration with pac4j.

**Comment by danhyun** [comment]
We need to run some tests to determine how much bloat Java Serialization will add to the overall payload size.

**Comment by alkemist** [comment]
Java serialization is very heavy and risky. I think we need to come with a custom serialization strategy out of the gate. We should not be allowing arbitrary objects to be serialized, so it's perfectly ok if we constrain this by requiring that a custom serialization/deserialization strategy be provided for each type you want to serialize.

**Comment by davidmc24** [comment]
Maybe default to Jackson serialization?

**Comment by alkemist** [comment]
Superseded by #681.
