### ISSUE TITLE
Make LIFO retrieval part of the Registry contract

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#666]
Update Guice and Spring impls.
Update docs.
Add a TCK harness.

**Comment by alkemist** [comment]
This has been implemented, just needs to be documented on `Registry`.

**Comment by danhyun** [comment]
If this needs more doc I can pouch this up.

**Comment by alkemist** [comment]
That would be super cool. Just needs a section on the docs on `Registry` explaining how ordering works.

**Comment by danhyun** [comment]
^ let me know if we need any tweaks or more explanation

**Comment by danhyun** [comment]
^ should get to the point of LIFO registry contract. LMK if we need more examples.
