### ISSUE TITLE
Pac4j documentation

### ISSUE THREAD

**Issue by leleuj** [ratpack/ratpack#668]
Hi,

`ratpack-pac4j` is a module which handles authentication on various providers: it deserves a documentation.
Where do you want me to put the chapter on this topic? As chapter 18 or 36?
Thanks.
Best regards,
Jérôme

**Comment by leleuj** [comment]
I'm willing to write the documentation, just waiting for your input...

**Comment by alkemist** [comment]
Hi @leleuj 

This should go in the `30..59` range. Whatever is next available.

We aren't really satisfied with our pac4j support implementation. As you've commented elsewhere, it's too complex and not very usable. Do you have any proposals for how we go about fixing this? That is, looking at the code, do you have any proposals for a reimplementation?

**Comment by leleuj** [comment]
OK. I'll write the documentation after the reimplementation.

The idea of the https://github.com/ratpack/ratpack/blob/master/ratpack-pac4j/src/main/java/ratpack/pac4j/Authorizer.java is great: I like it, but it make things harder to use. I take the idea for `pac4j` v1.8: https://github.com/pac4j/pac4j/issues/153.
So it will remove it for now.

There are too many classes: I would get ride of all "module" stuffs to keep:
- one handler to protect an url by a specific client (`RequiresAuthenticationHandler`)
- one handler to receive callbacks (`CallbackHandler`)
- one Raptack-dedicated context (`RatpackWebContext`)
- some class to store the user profile, some `UserUtils` based on session or request or context. On this topic, I realized I went into two similar directions: the "UserUtils" way (https://github.com/pac4j/spark-pac4j/blob/master/src/main/java/org/pac4j/sparkjava/UserUtils.java, https://github.com/pac4j/j2e-pac4j/blob/master/src/main/java/org/pac4j/j2e/util/UserUtils.java...) or the "StorageHelper" way (https://github.com/pac4j/undertow-pac4j/blob/master/src/main/java/org/pac4j/undertow/utils/StorageHelper.java, https://github.com/pac4j/play-pac4j/blob/master/play-pac4j_java/src/main/java/org/pac4j/play/StorageHelper.java...) I need to do something about that for the next version of `pac4j`: https://github.com/pac4j/pac4j/issues/168.

So this is what I would do for the current version of `Ratpack` based on `pac4j` v1.7.

Then, based on the future version 1.8 of  `pac4j`, I would reintroduce the (pac4j) `Authorizer` concept and replace/update the `UserUtils` class.

It took me 4 hours to create the Sparkjava implementation: https://github.com/pac4j/spark-pac4j, things should be always straightforward.

Of course, I can help more on this.

**Comment by alkemist** [comment]
Changes are in.

https://github.com/ratpack/ratpack/tree/master/ratpack-pac4j/src/main/java/ratpack/pac4j

**Comment by leleuj** [comment]
Wooow, that was fast! Looks simple and straightforward to me. I will give it a try...

**Comment by alkemist** [comment]
I've realised what's there is not quite right. We need to bust up the auth handler into functions. It's feasible for any handler to want to authenticate the user.

We need to add something like this `RatpackPac4j`:

```
public static Promise<UserProfile> auth(Context ctx, Class<? extends Client<?, ?>> clientType)
```

If the user is not authenticated, the promise “never returns”, and the user is redirected. If the user is auth'd, the promise gets fulfilled.

This would be in a addition to what we have now.

**Comment by leleuj** [comment]
I'm not sure to understand how you would use this additional function, what I already saw seems good to me. Will update the demo to confirm...

**Comment by alkemist** [comment]
I'd use it programmatically in my own handlers to initiate authentication. Importantly, I could make programmatic choices about which client to authenticate with.

**Comment by leleuj** [comment]
Can you give me an example compared to the `RatpackPac4j.auth(GitHubClient.class)`?

Jumping into the great Javadoc of the `RatpackPac4j` class, I see:
`RatpackPac4j.callback(new GitHubClient("key", "secret"))`
and
`RatpackPac4j.auth(GitHubClient.class)`

These are pretty easy to use, but you don't use the "power" of gathering all callbacks on the same url through the `Clients` class (which is handle by the *client_name*  parameter).

So I would prefer something like:
```
Clients clients = new Clients(callback_url, client1, client2, ...);
`RatpackPac4j.callback(clients)`
````
and
`RatpackPac4j.auth(GitHubClient.class)` or `RatpackPac4j.auth("GitHubClient")`

What do you think?

**Comment by alkemist** [comment]
The callback handler clients param is a vararg…

https://github.com/ratpack/ratpack/blob/master/ratpack-pac4j/src/main/java/ratpack/pac4j/RatpackPac4j.java#L114

**Comment by alkemist** [comment]
I'm not very familiar with the usage patterns of pac4j, so it's hard for me to get a feel for the right API. I think what we have now is fine, but it's the minimum.

**Comment by leleuj** [comment]
In fact, you already use the `Clients` class internally: https://github.com/ratpack/ratpack/blob/master/ratpack-pac4j/src/main/java/ratpack/pac4j/internal/Pac4jCallbackHandler.java#L59

Generally, libraries let users create explicitely the `Clients` configuration.

The `Clients` are retrieved from the context (https://github.com/ratpack/ratpack/blob/master/ratpack-pac4j/src/main/java/ratpack/pac4j/internal/Pac4jAuthenticationHandler.java#L60, I'm not sure how they are stored in it), so in case of two callback endpoints (CAS proxies for example), I fear that it won't work because one `Clients` will erase the other `Clients`...

**Comment by alkemist** [comment]
So an app may have two different callback urls?

**Comment by leleuj** [comment]
You may have as many callback urls as you want: /callback_facebook, /callback_twitter... Theorically speaking. Though, it's a useless overhead in configuration. That's why the `Clients` class comes into play: to gather all callbacks on one url by adding a `client_name` parameter to distinguish between identity providers.
So you can put the CAS service url and the CAS proxy receptor url on the same callback url by definig both dedicated clients in the same `Clients` configuration, but in Spirng Security as well as in many other frameworks dealing with CAS (without using `pac4j`), you have two urls by definition for these two different endpoints, so the idea is to offer this capability through `ratpack-pac4j` as well.

**Comment by alkemist** [comment]
I don't understand why this wouldn't work now, given that we already use `Clients`. What wouldn't work is having two clients of the same class, but with different names. So we probably need to overload the auth handler factory.

On the other side, is the common practice to just require that for all URLs under a certain path users are authenticated? Is it not common to want to make programmatic decisions deeper in the processing about this?

**Comment by leleuj** [comment]
Yes, you can take programmatic decision at a method level for example, but the easiest way to define your security is to say: this url is protected and this one is not, so I tend to think that securing urls covers 90% of the needs (maybe more). I don't remember a question / request about securing just a method...

I will update the demo to make my ideas clearer.

**Comment by leleuj** [comment]
BTW, when rebulding `ratpack`, I get the following errors:

```
ratpack.groovy.handling.ChainSubclassParitySpec > groovy chain subclass overrides universally overrides return type FAILED
    java.lang.AssertionError: GroovyChain method public default ratpack.handling.Chain ratpack.handling.Chain.path(java.lang.Class) is not overridden in groovy subclass
        at ratpack.groovy.handling.ChainSubclassParitySpec._spock_feature_0_0_closure2(ChainSubclassParitySpec.groovy:43)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)
        at ratpack.groovy.handling.ChainSubclassParitySpec.groovy chain subclass overrides universally overrides return type(ChainSubclassParitySpec.groovy:38)

ratpack.groovy.handling.ChainSubclassParitySpec > groovy chain subclass has closure overloads for all handler methods FAILED
    java.lang.AssertionError: GroovyChain method public default ratpack.handling.Chain ratpack.handling.Chain.path(ratpack.handling.Handler) is not overridden in groovy subclass
        at ratpack.groovy.handling.ChainSubclassParitySpec._spock_feature_0_1_closure4(ChainSubclassParitySpec.groovy:63)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)
        at ratpack.groovy.handling.ChainSubclassParitySpec.groovy chain subclass has closure overloads for all handler methods(ChainSubclassParitySpec.groovy:55)
```

**Comment by leleuj** [comment]
Here is the latest update of the demo: https://github.com/pac4j/ratpack-pac4j-demo/pull/4

I have the following error:

```
RATPACK PAC4J DEMO 11:53:39.791 [ratpack-compute-1-3] ERROR r.handling.internal.DefaultContext - Throwable thrown by error handler org.leleuj.AppServerErrorHandler@2b470e8a while handling throwable
Original throwable: ratpack.registry.NotInRegistryException: No object for type 'org.pac4j.core.client.Clients' in registry
```

I'm certainly missing something. This is the way I would have defined pac4j elements to be consistent with other implementations: https://github.com/pac4j/ratpack-pac4j-demo/pull/4/files#diff-902b01aee92ec6ea5ce6845b066c9e40R57 (then, I tried: https://github.com/pac4j/ratpack-pac4j-demo/pull/4/files#diff-902b01aee92ec6ea5ce6845b066c9e40R46).

**Comment by alkemist** [comment]
Here's a working version:

https://github.com/alkemist/ratpack-pac4j-demo

After the recent changes, your app is still reaching into internals. We need to offer public API for 

1. Extracting the profile 
2. Remove the profile from the session (a.k.a. logout)

**Comment by leleuj** [comment]
Excellent!

I just created and merged a PR from your clone: https://github.com/pac4j/ratpack-pac4j-demo/pull/5. I just sent you an invitation to give your write access on `pac4j` repo and therefore on `ratpack-pac4j-demo`. It will be easy for you, when you make relevant changes on `ratpack`, to push a PR on the demo and merge it unless someone does it (a PR is proposed a few days waiting for a +1 before being merged, for a demo which is less critical, just merge after a few days even if you don't get a +1).

By the way, this file (https://github.com/ratpack/ratpack/blob/master/ratpack-pac4j/ratpack-pac4j.gradle#L17) should reference https://github.com/pac4j/pac4j and not https://github.com/leleuj/pac4j. And it's certainly worth adding the demo: https://github.com/pac4j/ratpack-pac4j-demo

About the public API to deal with the user profile, I'm working on unifying this in pac4j v1.8: https://github.com/pac4j/pac4j/pull/172. I wish you could create something very close to this new `ProfileManager` (the idea is to inherit from this abstract class and implement the necessary methods). Any feedback will be appreciated.

**Comment by alkemist** [comment]
@leleuj I've made some updates. 

https://github.com/ratpack/ratpack/blob/master/ratpack-pac4j/src/main/java/ratpack/pac4j/RatpackPac4j.java

Are you still planning on adding some manual content?

**Comment by leleuj** [comment]
Yes, I'm still willing to, but things have been pretty changing lately and I dont' want to write and rewrite too much. I was waiting somehow.

The Javadoc of the `RaptackPac4j` class is awesome!

I take a look at your changes. I think that you should always update the demo accordingly to see how it really fits and to ensure you don't miss anything (you now have write rights on pac4j projects).

It seems to cover all use cases, it "feels" more Ratpack than pac4j (I didn't see any ProfileManager implementation), but anyway, this is your kingdom ;-)

**Comment by leleuj** [comment]
Here is the PR: https://github.com/ratpack/ratpack/pull/704

I tried to keep it simple and fairly straight forward. My english may not be perfect though. I'm looking for your feedback.

**Comment by danhyun** [comment]
Thanks again @leleuj just waiting on results of ci
