### ISSUE TITLE
Provide notification of shutdown

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#67]
Provide some way for user code to be notified when the app is going down so that it can clean up.

**Comment by davidmc24** [comment]
This has been handled by way of introducing support for the concept of a "ratpack service" (see [Service](https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/main/java/ratpack/server/Service.java)).

**Comment by alkemist** [comment]
I'm not entirely sure we are done on this. The semantics of shutdown are a bit undefined, and it's not quite integrated into the “soft reload” mechanism (i.e. reloading config and not the server).

**Comment by davidmc24** [comment]
I had noticed that soft reloads didn't trigger `Service.onStop`, and found it a bit surprising, but had figured it was intentional, as the application isn't technically stopping.

**Comment by alkemist** [comment]
Depends on your definition… we are rebuilding the registry so are going to create new copies of all the services. There are many situations where on such a reload cleanup will be needed.

Let's leave this ticket as is and do improvements on a new one.

**Comment by aaronhagopian** [comment]
I did a simple server with ratpack and used curl and your library as a test.  Sorry if this is a bit sloppy, used this opportunity to try out ratpack since I have not used it before.

**server.groovy**
```groovy
@Grapes([
  @Grab('io.ratpack:ratpack-groovy:1.5.0-rc-2'),
  @Grab('org.slf4j:slf4j-simple:1.7.25'),
])
import static ratpack.groovy.Groovy.ratpack
import java.util.logging.Logger
Logger log = Logger.getLogger("")

ratpack {
    handlers {
        get {
			request.headers?.names?.each { name -> log.info "HEADER: ${name}, VALUES: ${request.headers?.getAll(name)}"} 
			if(request.headers?.names?.find{ it =~ /Authorization/ }) {
				render "found an attempt at authorization"
			} else {
				render "no attempt at authorization"
			}
        }

    }
}
```

**client.groovy**
```groovy
@Grab('io.github.http-builder-ng:http-builder-ng-apache:0.17.0')

def response = groovyx.net.http.HttpBuilder.configure {
    request.uri = 'http://localhost:5050'
}.get {
    request.auth.basic 'user', 'p4ss'
    request.uri.path = '/'}
	
println response

```
launch the server in a separate console:
```bash
$ groovy server
[main] INFO ratpack.server.RatpackServer - Starting server...
[main] INFO ratpack.server.RatpackServer - Building registry...
[main] INFO ratpack.server.RatpackServer - Ratpack started (development) for http://localhost:5050
...
```

With the server running, using curl on linux I get:
```bash
$ curl -u user:p4ss http://localhost:5050/ 
found an attempt at authorization
```

Using my groovy script client I get:
```groovy
$ groovy client
no attempt at authorization
```

And you can see on the server output that no header with "Authorization" comes when using the http-buildler-ng client.
