### ISSUE TITLE
Make location of ratpack.groovy configurable in Gradle plugin

### ISSUE THREAD

**Issue by cschlegelmilch** [ratpack/ratpack#675]
I'd like to be able to change the current assumed directory structure from this:

- build.gradle
- src
	- main
	- ratpack
	- test

To this:

- build.gradle
- rest-api
     - src
	- main
	- ratpack
	- test

…such that the ratpack tasks (e.g. run) can still work.  There appears to be an assumption/default that ratpack.groovy lives in ${project.projectDir}/src/ratpack/ratpack.groovy.  It would nice if we could adjust the location of the ratpack directory or ratpack.groovy via the gradle DSL.

**Comment by alkemist** [comment]
Anyone want to take this on? @johnrengelman ?

**Comment by johnrengelman** [comment]
@cschlegelmilch To satisfy my curiosity, how are you changing the location of the default source set in your build? (i.e. from `src/main` to `rest-api/src/main`)

**Comment by cschlegelmilch** [comment]
@johnrengelman I wasn't really.  I ended up using a parent gradle project at my project root then put a child gradle project beside the src directory.  Its a little more complicated than needed for this project, but its seems to be working OK.

**Comment by johnrengelman** [comment]
@alkemist I'm gonna bug you about this as soon as I see you again, but is the thought here to implement a true `sourceSet` instead of just adding a directory to the `sourceSet.main`?

**Comment by alkemist** [comment]
I was just thinking we'd introduce a ratpack extension and have a property for this.

**Comment by johnrengelman** [comment]
Yeah, I just came to that same conclusion after looking at the code. We already have an extension for the dependency sugar, so it's just some renaming.
