### ISSUE TITLE
MainClassApplicationUnderTest.createOverrides doesn't override anything

### ISSUE THREAD

**Issue by tomakehurst** [ratpack/ratpack#680]
Returning a ``Registry`` from ``MainClassApplicationUnderTest.createOverrides()`` containing an alternate implementation of an interface bound in the application via Guice doesn't have any effect - the production implementation used remains the one used.

**Comment by alkemist** [comment]
I replied to this a few days ago, but looks like it got lost… somehow.

This mechanism doesn't push into the Guice bindings. It only overlays. So, you can augment what gets presented as the service registry, but you can't augment how Guice binds internally.

If you need to change the bindings, you need to get into the server config stuff. We haven't yet hooked this up to the overrides mechanism.

**Comment by tomakehurst** [comment]
OK, makes perfect sense.
