### ISSUE TITLE
Include Rx to RS adapters, and wrap factories in RatpackRx

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#684]
Since we use `Publisher` in our APIs, we should make it convenient to use `Observable` as a `Publisher` when using RatpackRx.

**Comment by johnrengelman** [comment]
`public static Publisher<T> RxRatpack.publish(Oberservable<T>)`?

**Comment by johnrengelman** [comment]
Closed by https://github.com/ratpack/ratpack/compare/8e5b0baff079e86a5e30269a6970ac763fba3771...82183757880845c757118d32c171e1a9e285d885
