### ISSUE TITLE
Provide support to retry failed promises

### ISSUE THREAD

**Issue by tomdcc** [ratpack/ratpack#686]
@alkemist I've got a basic impl on DefaultPromise in this commit https://github.com/tomdcc/ratpack/commit/fd0001ddabd0911145b720ca2aa312ac4daba83b, but I want to flesh out the test and add some javadoc. I couldn't implement it as a default method on Promise itself due to the second method that it needs. In theory that could go into a utility class or become a static method on DefaultPromise, but at that point I figured it was just easier to leave it unimplemented by default. Thoughts?

**Comment by RobWin** [comment]
Hi, check out [Resilience4j](https://github.com/resilience4j/resilience4j).
We provide a Ratpack module which provides Transformers for Retry, CircutiBreaker and Ratelimiter:

http://resilience4j.github.io/resilience4j/#_retry_2

**Comment by rhart** [comment]
Retry was added in 1.5 https://github.com/ratpack/ratpack/issues/1122

Resilience4j looks great.  Just checking out the circuit breaker stuff as we speak :)

**Comment by RobWin** [comment]
Resilience4j-retry has some nice Monitoring features. You can monitor a Retry and `RetryTransfomer` with Dropwizard, Prometheus or RxJava Event stream.

**Comment by rhart** [comment]
Nice!  Would love to see a ratpack resilience talk.

**Comment by RobWin** [comment]
@drmaas would be the guy who should do the talk :) He's the contributor of the ratpack module.

**Comment by RobWin** [comment]
@rhart I would love to hear your's and @alkemist opinion about our ratpack-module.
Feel free to suggest improvements.

**Comment by RobWin** [comment]
Last comment: Resilience4j-retry allows different backoff strategies (like exponential backoff) to control back off between retry attempts.
