### ISSUE TITLE
Documentation Diagrams

### ISSUE THREAD

**Issue by aadamovich** [ratpack/ratpack#687]
For my presentation about ratpack, I have drawn a couple of diagrams (hopefully in ratpack style :), using the same color scheme). Those may be useful for insertion into documentation. I'm planning to draw some more for GR8Conf EU presentation. Any feedback is more than welcome. Original images are available as SVG.

Handler chain:

![ratpack_flow](https://cloud.githubusercontent.com/assets/2787794/7906901/be520480-083a-11e5-81a2-e2b671a88b3e.png)

Minimal library dependencies:

![ratpack_libraries](https://cloud.githubusercontent.com/assets/2787794/7906902/be56a2e2-083a-11e5-8da4-d3d85f9ee88f.png)

**Comment by alkemist** [comment]
Thanks for sharing this Andrey.  Much appreciated.

I hope the talk went well.
