### ISSUE TITLE
Support httpOnly and secure cookie for ratpack-session

### ISSUE THREAD

**Issue by asv** [ratpack/ratpack#690]
Hi,

I can't find a way to set the HttpOnly config flag for the creation of a secure session cookie for ClientSideSession / CookieBasedSessionId. Netty Cookie has support this capabilities and would be cool expose it.

Thanks for Ratpack!

**Comment by zedar** [comment]
@asv : good point! We definitely should add `HttpOnly` and `Secure` params to `ClientSideSessionConfig` as well as to `SessionIdCookieConfig`.

**Comment by asv** [comment]
Also about session... Why is session generated (and stored) on server (*JSESSIONID*) when ClientSideSession is active (and *ratpack_session_ID* is sent)?

**Comment by alkemist** [comment]
Not sure what you mean by stored here.

We still generate the session id so that it's available to log if the app wishes, for correlation.

**Comment by zedar** [comment]
Changes addressed in 0.9.18-SNAPSHOT. Can we close this issue?

**Comment by alkemist** [comment]
Yes, please close.
