### ISSUE TITLE
decorate() called twice on bound HandlerDecorator 

### ISSUE THREAD

**Issue by djjorjinho** [ratpack/ratpack#693]
ratpack v.0.9.17

I used the ratpack groovy dsl to multibind() a handler decorator and placed a breakpoint on it's decorate() method. Running the app in debug mode I noticed It gets called twice.

Noticed on the decorator Iterable in ratpack.server.internal.DefaultRatpackServer#decorateHandler that I have two instances of the decorator.

Could someone look into this?

**Comment by alkemist** [comment]
Could you provide a test case?

You could add it here: https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/test/groovy/ratpack/handling/HandlerDecorationSpec.groovy#L21-21

**Comment by djjorjinho** [comment]
I comitted the test here:
https://github.com/djjorjinho/ratpack/commit/3786e4879475836a207a5bf6bdea490bdc585b04

seems that ratpack.guice.internal.GuiceUtil#allProvidersOfType is returning two providers for the test handler decorator type.

**Comment by alkemist** [comment]
Fixed. The workaround is to not use a multibinding here. You only need to use a multibinding if you bind it to Guice via the `HandlerDecorator` type, because others might try and also use this type.
