### ISSUE TITLE
Session should wrap SessionData methods with Promise/Operation variants.

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#695]
This would make it more convenient to do certain kinds of simple operations.

e.g.

```
interface Session {
  …
  default <T> Promise<Optional<T>> get(SessionKey<T> key) {
    return getData().map(d -> d.get(key));
  }
  …
}
```

**Comment by danhyun** [comment]
I'll grab this

**Comment by danhyun** [comment]
Should we offer a variant that unwraps the `Optional<T>`?

**Comment by alkemist** [comment]
Implementation is bugged. See: https://github.com/ratpack/ratpack/commit/3f0c868ef71f484099052507f7933bb19ef25780#commitcomment-11805385

**Comment by danhyun** [comment]
^ fixes the impl
