### ISSUE TITLE
GroovyConsole Error

### ISSUE THREAD

**Issue by danveloper** [ratpack/ratpack#697]
When trying to run a Ratpack script from the Groovy console, the following error:

```
java.lang.IllegalStateException: Could not find script file for closure: ConsoleScript0$_run_closure1@16f8660a
```

**Comment by johnrengelman** [comment]
So, what's the correct way to tackle this? Do we need a different `Backing` implementation that deals with being in the console? Or should there be a logic check in `StandaloneScriptBacking` to handle this?
