### ISSUE TITLE
Consolidate methods for creating and building registries under `Registry`

### ISSUE THREAD

**Issue by danhyun** [ratpack/ratpack#710]
`ratpack.registry.Registries` currently contains the methods that users would use to create registries. These methods should be refactored to exist under `ratpack.registry.Registry`.

> It’s a relic from pre java 8, and pre static methods on interfaces.
> so, the methods should move to `Registry` and `Registries` should die

**Comment by danhyun** [comment]
@alkemist am I missing anything here?

**Comment by alkemist** [comment]
Added some comments about method renames, otherwise LGTM.
