### ISSUE TITLE
Relative paths passed to ServerConfig.Builder's json() and yaml() methods should be resolved relatively to base dir

### ISSUE THREAD

**Issue by erdi** [ratpack/ratpack#725]
Currently they are used [as is](https://github.com/ratpack/ratpack/blob/902c4fd37db0e2405c451065c9dbf4193fe5dfcc/ratpack-core/src/main/java/ratpack/config/internal/DefaultConfigDataSpec.java#L122) and test coverage is only for [passing absolute paths in](https://github.com/ratpack/ratpack/blob/902c4fd37db0e2405c451065c9dbf4193fe5dfcc/ratpack-core/src/test/groovy/ratpack/config/JsonConfigSpec.groovy#L27).

**Comment by alkemist** [comment]
@ratpack/committers this will be reasonably straight forward. Any volunteers?

**Comment by danhyun** [comment]
I'll grab this.

**Comment by danhyun** [comment]
After some discussion here's the current strategy:

Don't allow config source to set baseDir
Have config sources lazily resolve against builder's baseDir

Later:
Enhance BaseDir.find() to accept sys env variable to set baseDir
