### ISSUE TITLE
post() handler chain internally calls patch() chain handler

### ISSUE THREAD

**Issue by djjorjinho** [ratpack/ratpack#726]
I was trying yo make use of the post() groovy chain handler (the one that accepts a handler class as argument) but I noticed that it's implementation called a patch() method.

I have commit ready if you want (48d0482890a7cd3f8eb401073c0771784b7014cb).

**Comment by rhart** [comment]
Good spot! If you can send a PR that would be great.

**Comment by djjorjinho** [comment]
Done.
