### ISSUE TITLE
Ratpack takes a while to exit in IntelliJ IDEA

### ISSUE THREAD

**Issue by Vadi** [ratpack/ratpack#736]
Not sure this happens to everyone or is there any IntelliJ way to solve this. 

I am running Ratpack webserver from IntelliJ in Debug mode. When I press restart the program terminates but looks like some daemon thread runs and takes a while to exit. Due to this, the program restarts and tries to bound to the HTTP port without knowing previous one still not terminated properly.

````
2015-07-25 12:34:17 [ratpack-compute-1-13] DEBUG r.c.i.ConfigDataReloadInformant - No difference in configuration data
Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.4-all.zip'.
12:34:18 PM: External task execution finished 'run'.
````

In case if I stop and wait for few seconds and then start the debugger again, all works fine. I suspect `ConfigDataReloadInformant` runs a thread that is marked as daemon or takes a while to exit.

**Comment by timyates** [comment]
I don't see this on osx Java 8_51, which os/jdk are you running? And which version of intellij?

**Comment by Vadi** [comment]
**Java 8** 1.8.0_31

**IntelliJ**
![IntelliJ screenshot](https://dl.dropboxusercontent.com/s/6ptcuu7187xo07l/idea_version.jpg)

**Comment by timyates** [comment]
Can you try with one of the later jdks?

**Comment by Vadi** [comment]
Tried with latest ones but with no success. I suspect this is something to do with thread not terminating in `ConfigDataReloadInformant`. Not sure how can I disable auto-loading configuration file facility.

![image](https://cloud.githubusercontent.com/assets/218148/8889559/bb38312e-32fc-11e5-8f04-d14c4c5e2a85.png)

**Comment by danhyun** [comment]
Can you show your run configuration?

Like this

![image](https://cloud.githubusercontent.com/assets/1033018/8890089/9ac802f6-32c1-11e5-989c-8ea878391b90.png)

**Comment by Vadi** [comment]
There is no VM options though. The configuration is Gradle configuration.

![image](https://cloud.githubusercontent.com/assets/218148/8890163/b81f20da-3313-11e5-89e6-26944b07a92a.png)

**Comment by danhyun** [comment]
How are you starting your application?

There could be a few things going on

Ratpack has awesome IntelliJ and Gradle support, to utilize this you should run
`./gradlew cleanIdea idea`
to generate the files that the IDE cares about. After that you can open the `.ipr` file and have everything good to go including the run configuration for your main class.

This command will also generate the VM options you need to get up and running so from that point you can just select that run configuration to both run and debug your app.

If you're running via `./gradlew run` which is what you seem to suggest, then IntelliJ is not being told to first stop the application before starting again which would make sense. If you can still ping your sever after it fails to restart this is probably why.

**Comment by Vadi** [comment]
So are you suggesting I should not run with `run` task in IntelliJ?

**Comment by danhyun** [comment]
I'm not sure what you mean by the 
> `run` task in IntelliJ

IntelliJ by default has no concept of a run task, I'm guessing you're talking about the IntelliJ Gradle plugin which exposes all Gradle tasks available to the project.

Instead I recommend running `./gradlew cleanIdea idea` from the root directory of your project

![image](https://cloud.githubusercontent.com/assets/1033018/8890251/f48002da-32c6-11e5-9244-56b8b7a6b233.png)

After this, when you open the project via the `.ipr` file, you will see this Run configuration called `Ratpack Run (:)`

![image](https://cloud.githubusercontent.com/assets/1033018/8890254/184e865a-32c7-11e5-9097-cc3428fa2537.png)

This is what you can use to run your application.

**Comment by timyates** [comment]
I just import it as a gradle project, and set a run configuration to run my
main Java class.

But then I use ratpack in a purely Java way, so my setup probably differs

**Comment by Vadi** [comment]
`./gradlew cleanIdea Idea` perfectly produced `.ipr` files. Also ensured I deleted `.idea` folder. After opening `.ipr` file I don't see `Run Ratpack` configuration.

Also tried adding one through `Edit Configuration`. I don't see any such.

![image](https://cloud.githubusercontent.com/assets/218148/8890272/395c74d2-3318-11e5-8862-2a8b1ddf77fd.png)

**Comment by Vadi** [comment]
In my configuration there is one twist though - I don't have `build.gradle` however I have followed similar approach how Ratpack itself keeps build gradle files with a project name (The reason being I will have too many submodules in future and I would ended up having tons of `build.gradle` file).

My `settings.gradle` file has entries like this &mdash;

````groovy
def setBuildFile(project) {
    project.buildFileName = "${project.name}.gradle"

    project.children.each {
        setBuildFile(it)
    }
}

setBuildFile(rootProject)

rootProject.children.each {
    setBuildFile(it)
}
````

**Comment by danhyun** [comment]
That explains a lot.

This is quickly becoming more of a Gradle question rather than a Ratpack issue.

If you use the Ratpack Gradle plugin - which requires that you have at least a root `build.gradle` file, then you should see this after running `./gradlew cleanIdea idea`

![run config](https://cloud.githubusercontent.com/assets/1033018/8890311/ee49f8cc-32ca-11e5-8aa5-482625ae8983.gif)

Here's an example of a root `build.gradle` file that utilizes Ratpack's Gradle plugin

https://github.com/ratpack/example-ratpack-gradle-groovy-app/blob/master/build.gradle#L13

Once you have applied this plugin (`apply plugin: "io.ratpack.ratpack-groovy"` ,or `apply plugin: "io.ratpack.ratpack-java"`, the `idea` task will take care of the rest.

**Comment by Vadi** [comment]
Now I see that .. thanks for all the help. The project is not a straight forward Ratpack project due to some legacy dependencies it has.

Much appreciated, I am closing the issue for now.

**Comment by danhyun** [comment]
Anytime @Vadi feel free to reach out in case you run into additional issues.

We also have a community slack channel for discussing this kinds of things. You can sign up at http://slack-signup.ratpack.io/ hope to see you there!
