### ISSUE TITLE
Add config option for changing delimiters in ratpack-handlebars

### ISSUE THREAD

**Issue by lundvall** [ratpack/ratpack#738]
This is useful when using ratpack-handlebars (Handlebars.java) to render templates that contains client side templates with mustache style delimiters.

template.hbs.html

```html

<%name%>

<!-- client side template -->
<script type="text/template">
    {{name}}
</script>
```

Configure HandlebarsModule

```java
.module(HandlebarsModule.class, c -> c
    .startDelimiter("<%")
    .endDelimiter("%>"))
```

Changes to HandlebarsModule

```java
public class HandlebarsModule extends ConfigurableModule<HandlebarsModule.Config> {
  public static class Config {
    public Config startDelimiter(String startDelimiter) {
      this.startDelimiter = startDelimiter;
      return this;
    }

    public Config endDelimiter(String endDelimiter) {
      this.endDelimiter = endDelimiter;
      return this;
    }
    ...
  }

   Handlebars provideHandlebars(Config config, Injector injector, TemplateLoader templateLoader, TemplateCache templateCache) {
    final Handlebars handlebars = new Handlebars()
      .with(templateLoader)
      .with(templateCache)
      .startDelimiter(config.startDelimiter)
      .endDelimiter(config.endDelimiter);
    ...
    return handlebars;
  }
}
```

**Comment by lundvall** [comment]
I'm happy to submit a PR.

**Comment by rhart** [comment]
Makes sense to expose this as an optional config option, with the default behaviour being what we have now.

If you'd like to submit a PR with the changes, tests and updates to any documentation then that would be awesome!

**Comment by lundvall** [comment]
I would also like to add the option to configure both delimiters at the same time.

```java
.module(HandlebarsModule.class, c -> c.delimiters("<%", "%>"))
```
What do you think?

**Comment by rhart** [comment]
I prefer that to the separate methods.  Is there a use case to have different start and end delimiters?  I suppose there's no point in restricing users from doing that though if Handlebars allows it

**Comment by lundvall** [comment]
I think that it should replace the separate methods, it looks nicer and might be easier to understand even though you only want to change one delimiter.

**Comment by rhart** [comment]
Agree.  Let's go with that then

**Comment by rhart** [comment]
Closed by https://github.com/ratpack/ratpack/pull/739
