### ISSUE TITLE
MainClassApplicationUnderTest should allow adding extra config

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#743]
This would be similar to the existing createOverrides() method. Something like:

```
protected addConfig(ConfigDataBuilder builder) {

}
```

This would receive the `ServerConfigBuilder` and users would be expected to _add_ config that overrides the config defined in the main method. The primary use case would be changing things like database handles/credentials etc. to suitable test values.

**Comment by tomdcc** [comment]
I came here looking for an issue to pass args to an app run with MainClassApplicationUnderTest, but it was really just for this use-case. Necessary not just for credentials but testing different behaviour based on different config.
