### ISSUE TITLE
Add support for yaml application profiles

### ISSUE THREAD

**Issue by drmaas** [ratpack/ratpack#754]
It would be useful to allow for application profiles to be set in yaml files, similar to what spring boot supports. For example:

```
ratpack:
  profiles: dev
...
---
ratpack:
  profiles: ci
...
```

**Comment by alkemist** [comment]
Can you please provide more information about what these profiles would be, or be used for.

**Comment by drmaas** [comment]
One way I'd like to use them is for setting different profiles for local development, dev and qa environments, and for integration tests by passing in different profile values via a system property on the command line.

**Comment by alkemist** [comment]
I'm pretty reluctant to add a general solution for this, because I've always had problems trying to compose this stuff within a framework.

You can do this today by selectively loading up config sources, based on whatever stimulus you want. For example…

```
RatpackServer.start(s -> s
  .serverConfig(c -> c
    .json(Boolean.getBoolean("test") ? "conf-test.json" : "conf.json")
  )
  …
}
```

There are many ways you could approach that.

**Comment by drmaas** [comment]
If you change your mind, I don't think it would be too difficult to add, as the underlying snakeyaml parser supports multiple documents/file separated by ```---```. We'd just be telling it which document to load from the file.

**Comment by alkemist** [comment]
I'm going to leave this open for a while to see if anyone else has opinions to share on the matter.
