### ISSUE TITLE
Automate detection of breaking API changes

### ISSUE THREAD

**Issue by ldaley** [ratpack/ratpack#760]
We can use http://clirr.sourceforge.net/clirr-core/anttask.html for this.

**Comment by johnrengelman** [comment]
This looks like a possibility: https://github.com/aalmiray/clirr-gradle-plugin

However, it appears that you can only blacklist packages from the analysis (using only a trailer wildcard). This might make it difficult to use.

**Comment by alkemist** [comment]
Worth a try.
