### ISSUE TITLE
Joining to context registry from handler doesn't work when Context#insert is used

### ISSUE THREAD

**Issue by danveloper** [ratpack/ratpack#762]
The visibility of registries joined to the Context to downstream handlers differs based on whether the Handler was explicitly part of the chain or was dynamically added via `ctx.insert(Handler)`.

Simple (working) example:

```groovy
@Grab('io.ratpack:ratpack-groovy:0.9.19')

import static ratpack.groovy.Groovy.ratpack
import static ratpack.registry.Registry.single
import ratpack.handling.Handler
import ratpack.handling.Context

class FooService {}

class DansHandler implements Handler {
  void handle(Context ctx) {
    ctx.next(single(new FooService()))
  }
}

ratpack {
  handlers {
    // THIS ONE WORKS
    all(new DansHandler())

    all { FooService foo -> 
      render "Foo $foo"
    }
  }
}
```

This works as expected. If we use `ctx.insert(DansHandler)`, we get an exception trying to inject the `FooService` into the downstream handler:

```groovy
  // ... snip ...
  handlers {
    // THIS ONE FAILS
    all { insert(new DansHandler()) }

    all { FooService foo -> 
      render "Foo $foo"
    }
  }
```

**Comment by alkemist** [comment]
This is how it's intended to work. Whether that's a good thing is a separate question.

If you think of the handlers as being a tree it's easier to understand. When handlers add a registry to the context, that registry is only visible to siblings (when using `next()`) or children (when using `insert()`).

In your second example, `DansHandler` is not a sibling of  the handler that renders the foo. In the first it is.

It's like this so that you can scope things…

```
handlers {
  prefix("foo") {
    register { it.add(new FooService()) }
    // handlers that can see the foo
  } 
  // handlers that cannot see the foo
}
```

**Comment by danveloper** [comment]
I wonder if `insert` _should_ build a new `ChainIndex` or if it should add to the existing one... I guess the question there would be whether the inserted handler is a request flow handler or a terminal handler. In the case of the latter, I'd expect visibility.

**Comment by alkemist** [comment]
Why is that?

**Comment by danveloper** [comment]
Just a conceptual differentiation. I'm _inserting_ a handler to next in line, as oppose to I'm _creating_ a new chain...

Either way, the behavior is ok, but this is a caveat that we should make apparent in docs. I'm gonna note it in the book.
