### ISSUE TITLE
looks like 2.1 of the manual with grab dependency is not working

### ISSUE THREAD

**Issue by javazquez** [ratpack/ratpack#768]
looks like the following is not working correctly

@Grab('io.ratpack:ratpack-groovy:1.0.0-rc-1-SNAPSHOT')

http://ratpack.io/manual/current/quick-start.html#using_a_groovy_script

It appears that this would work if the @GrabResolver(...) was used. Creating this issue to investigate.

**Comment by alkemist** [comment]
Fixed, thanks.
