### ISSUE TITLE
Add default http://localhost:5050/ to manual

### ISSUE THREAD

**Issue by javazquez** [ratpack/ratpack#771]
Had to help someone use the default http://localhost:5050/ to see their running app.  I couldn't find a reference to URL  in the manual. Can it  be added? Thinking maybe in both the Quick Start and Launching sections? I usually run the gradle version and see it, but when I ran the groovy script, I didn't see it. might be good to call out in the docs.. if its not there already

Happy to add it myself if needed 

Thanks
-Juan

**Comment by alkemist** [comment]
We'll add this to manual, but FYI we now handle the case when there is no logger better. This is #777.

**Comment by javazquez** [comment]
Great! I'll check out 777

Thanks 
-Juan
