### ISSUE TITLE
ByMethodSpec and ByContentSpec should have `Handler` accepting overloads of `Block` methods.

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#773]
See: http://forum.ratpack.io/multiple-request-method-on-one-path-tp1257p1264.html

Blocked on this Groovy issue: https://issues.apache.org/jira/browse/GROOVY-7582

**Comment by rhart** [comment]
Closed by https://github.com/ratpack/ratpack/commit/c35c5554cd9bd4b22f111dbbdaf91e6677ccd57b and https://github.com/ratpack/ratpack/commit/8b96cf490550966a0d2348a5d2c814dc668486f2
