### ISSUE TITLE
ServerEnvironment.isDevelopment throws NPE if property "sun.java.command" does not exist

### ISSUE THREAD

**Issue by bitpew** [ratpack/ratpack#774]
The title says it all. `ServerEnvironment.isDevelopment` throws an NPE when `System.getProperty("sun.java.command")` returns null.

This happens for example if I attempt to start a java application as a service via Apache Jsvc.

changing 
```java
String command = System.getProperty("sun.java.command");
return command.startsWith(INTELLIJ_MAIN) && !command.contains(INTELLIJ_JUNIT) ? "true" : null;
````
to
```java
String command = System.getProperty("sun.java.command");
return command != null && command.startsWith(INTELLIJ_MAIN) && !command.contains(INTELLIJ_JUNIT) ? "true" : null;
````

should fix the problem.

This bug is easily reproducible by executing

```java
Properties props = System.getProperties();
props.remove("sun.java.command");
System.setProperties(props);
```
before calling `ServerConfig.builder()`

If anyone needs a workaround, passing the missing property to jsvc bypasses the problem: `/usr/bin/jsvc -Dsun.java.command=my.made.up.command ...`

**Comment by danveloper** [comment]
What JVM are you using?

**Comment by bitpew** [comment]
Oracle jdk on debian jessie:

```
> java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

> uname -a
Linux debian-jessie 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```

The problem only occurs when I start the app via [jsvc](http://commons.apache.org/proper/commons-daemon/jsvc.html). It runs just fine when I start it on the same machine directly via `java` instead of `jsvc`.

This is really just a minor issue since a easy workaround exists, but I guess fixing it in 1.0 would still be nice :)

**Comment by alkemist** [comment]
Thanks for the report. We'll get this fixed and issue _another_ RC :)
