### ISSUE TITLE
No output is present when there is no logger binding

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#777]
Currently, we don't make it clear enough that a minimum requirement is an slf4j binding. For example, the Groovy quickstart examples don't depend on `slf4j-simple`. We either need to fix this, or provide a better experience when there is no binding.

**Comment by davidmc24** [comment]
Updating the groovy QuickStart examples to use slf4j-simple makes sense to me, and making it clearer in the manual that we maintain the default slf4j behavior when there is no binding: no-op.

**Comment by erdi** [comment]
+1

**Comment by alkemist** [comment]
To finish this off, we need to:

1. Add a page to the manual that talks about logging, and update the no binding warning to point to it.
2. Make sure all of our examples contain a logging binding.

Any takers?

**Comment by danthegoodman** [comment]
@alkemist There was already a logging page, so I just added a link to that in the message. I'm not sure if that section is what you are looking for, but it's a starting point at least.

The Gradle part of the Getting Started section already had a dependency upon slf4j-simple, so I added a `@Grab` statement to the groovy script example.
