### ISSUE TITLE
Add Promise.flatMapError()

### ISSUE THREAD

**Issue by erdi** [ratpack/ratpack#790]
The behaviour would be like for `Promise.mapError()` but it would take a function returning a `Promise` instead of a value.

**Comment by alkemist** [comment]
What happens when the function throws vs. returns a failed promise?

**Comment by erdi** [comment]
Sorry, I'm not sure if I understand the question... If the function (assuming you're talking about the function passed to `flatMapError()`) throws then we can do the same as we do for `mapError()`:

> If the function throws an exception, that exception will now represent the promise failure.

I don't see why anything special would need to be done when the function returns a failed promise - the failure of that returned failed promise would become the failure of the mapped promise.

**Comment by alkemist** [comment]
With mapError, the only option we have for replacing the error is throwing. With flatMapError, we can throw or return a failed promise. The question is, what is the difference between the two?

I'm inclined to say “nothing”. The user has the opportunity to wrap (or suppress) the incoming exception and is probably in a better situation to make this call than us.

**Comment by erdi** [comment]
Oh, now I see what you mean. What do we do when the function passed to flatMap throws? I would be inclined to do exactly the same for flatMapError to be consistent.

**Comment by ewxy** [comment]
As a workaround you can transform your promise into an `rx.Observable`, use [`onErrorResumeNext()`](http://reactivex.io/RxJava/javadoc/rx/Observable.html#onErrorResumeNext(rx.functions.Func1)) and then transform it back to a promise using `promiseSingle()`.

**Comment by erdi** [comment]
As a workaround you can transform your promise into an `rx.Observable`, use [`onErrorResumeNext()`](http://reactivex.io/RxJava/javadoc/rx/Observable.html#onErrorResumeNext(rx.functions.Func1)) and then transform it back to a promise using `promiseSingle()`.

**Comment by ewxy** [comment]
Thanks for adding this!

**Comment by erdi** [comment]
Thanks for adding this!
