### ISSUE TITLE
Provide support for configuring a connection timeout for HttpClient.

### ISSUE THREAD

**Issue by brucenunk** [ratpack/ratpack#791]
We could do with support for specifying a connection timeout with the HttpClient as currently if the remote host is unavailable the request just hangs. 

I've managed to get it working locally by copying the DefaultHttpClient (and supporting classes) and adding `bootstrap.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, timeout)` to RequestActionSupport. The connect Future then fails and seems to propogate the exception back up throw Ratpack correctly but I'm quite new to Ratpack so not sure if that is so?

Ideally I think somethink like adding `RequestSpec connectTimeout(Duration duration)` to RequestSpec would be nice?

Forum request: http://forum.ratpack.io/No-connection-timeout-available-on-HttpClient-td1290.html

**Comment by alkemist** [comment]
Thanks for the report @brucenunk . We'll get this fixed for 1.1.

Would you be willing to send a pull request with the work you've done so far? If it's not fully complete, still send it as we can finish it off.

**Comment by brucenunk** [comment]
Hi Luke.

I'd love to commit something to the project but I'm not very wise in the ways of github, I'm an SVN guy :( 

If you could give me a few pointers in terms of what to branch from I'm be more than happy to contribute.

**Comment by alkemist** [comment]
Great :)

GitHub have some good tutorials on creating pull requests, it should walk you through the process. Example: https://help.github.com/articles/using-pull-requests/

You'd base the pull request on our `master` branch. Yell out if we can help. Don't worry too much about trying to get the PR right the first time, it's non destructive and can be changed after.

**Comment by brucenunk** [comment]
OK will give it a whirl.

Thanks :)
