### ISSUE TITLE
Jackson JSON parser should attempt to parse content where mime type ends in `+json`

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#793]
See https://en.wikipedia.org/wiki/Media_type#Suffix

**Comment by alkemist** [comment]
@ratpack/committers I'm trying to decide whether to update http://ratpack.io/manual/current/api/ratpack/http/MediaType.html#isJson-- to return true for content types that end in `+json`. An alternative would be to add a new method (e.g. `isJsonLike()`) that returns true for `application/json` and `+json`.

WDYT?

Then we just have to change https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/main/java/ratpack/jackson/internal/JsonParser.java#L40-40 (or not).

**Comment by rhart** [comment]
I think I would stick with changing `isJson`.  From what I understand, `+json` is telling you that the format of the custom mime type _is_ json. So unless we need to distinguish between the standard mime type and custom json ones I'm not sure I'd bother adding `isJsonLike()`

I guess we also need to do this for `isXml` too
