### ISSUE TITLE
DefaultResponse#expireCookie does not set path

### ISSUE THREAD

**Issue by donaldquixote** [ratpack/ratpack#796]
Browsers will not overwrite/delete a cookie unless both the name and path match. Furthermore, if two cookies have same name but different paths, the more specific path wins. The expireCookie method does not set a path, so cookies with a path set will not be deleted by the browser.

**Comment by alkemist** [comment]
Thanks for the report @donaldquixote. 

Seems the fix would be for us to look at the actual cookies and use the path value for any that were there  when setting the expire. 

Is this something you'd be interested in contributing?

**Comment by donaldquixote** [comment]
I'd love to, but I'm on a pretty tight deadline as is and wouldn't want to contribute without taking some time to really dig into the code. After brief investigation, it seems reasonable to pass a reference to the request when constructing DefaultResponse, which can then be checked for sent cookies, but I don't know if forming that dependency would be safe or reasonable in the context of your code base.

**Comment by alkemist** [comment]
@donaldquixote I decided to leave the code how it is. See https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/test/groovy/ratpack/http/CookiesSpec.groovy#L91-91 for how to expire cookies with a path.

**Comment by donaldquixote** [comment]
Makes sense. It feels incomplete, but certainly better than my earlier suggestion. Thanks.
