### ISSUE TITLE
WebSocketHandler onClose method is not called when connection is abruptly closed.

### ISSUE THREAD

**Issue by niwinz** [ratpack/ratpack#801]
Hello.

I noticed that when a websocket connection is closed before a close frame is received, the onClose method of websocket handler is not called.

I have experimented with it in catacumba version of `WebSocketEngine.java` and I found that the solution may be like this:

```java
final DirectChannelAccess directChannelAccess = context.getDirectChannelAccess();
final Channel channel = directChannelAccess.getChannel();
channel.closeFuture().addListener(fu -> {
      try {
        handler.onClose();
      } catch (Exception e) {
        throw uncheck(e);
      }
    });
```

At this line https://github.com/ratpack/ratpack/blob/master/ratpack-core/src/main/java/ratpack/websocket/internal/WebSocketEngine.java#L104

**Comment by alkemist** [comment]
Great, thanks. 

Any chance of a pull request with a test? :)

**Comment by niwinz** [comment]
I'm gladly make a PR, but I'm not pretty convinced to know how reproduce the abruptly closed connection. Any suggestion?

**Comment by alkemist** [comment]
The websocket lib we use for testing exposes the underlying byte channel it is using. I think closing that will simulate this.

**Comment by niwinz** [comment]
Oh, nice to know, I'll research about it and I try to make a PR ready soon.

**Comment by niwinz** [comment]
Can you point me to some documentation that explains how I can use spock? I mean executing spock tests with gradle. I have readed a lot of the doc but I found absolutelly nothin. And I really want to do a very simple thing: execute one unique test case. 

(I have tryed the `-Dtest.single=...`  and it not works saying that no test found having provided an exact name of existing test case class, and `@IgnoreRest` that simple does not works, it is simply ignored)
It not the first time that I found me in this situation because spock is completelly undocumented on how I can use it from command line...

Thanks

**Comment by niwinz** [comment]
I have found a solution for the previous question.
