### ISSUE TITLE
General error during conversion: Error grabbing Grapes -- [download failed: com.fasterxml.jackson.core#jackson-annotations;2.5.0!jackson-annotations.jar(bundle)]

### ISSUE THREAD

**Issue by aadamovich** [ratpack/ratpack#807]
The simplest *Ratpack* *1.0.0* *Groovy* script, which I can think of, throws an exception during `@Grab`-ing:

    @Grab("io.ratpack:ratpack-groovy:1.0.0")
    import static ratpack.groovy.Groovy.ratpack
    
    ratpack {
      handlers {
        get {
          response.send "Time is " + new Date().toString() 
        }
      }
    }

The exception is:

    General error during conversion: Error grabbing Grapes -- [download failed: com.fasterxml.jackson.core#jackson-annotations;2.5.0!jackson-annotations.jar(bundle)]
    
    java.lang.RuntimeException: Error grabbing Grapes -- [download failed: com.fasterxml.jackson.core#jackson-annotations;2.5.0!jackson-annotations.jar(bundle)]

Of course, it's easily fixable by adding another `@Grab` like:

         @Grab("com.fasterxml.jackson.core:jackson-annotations:2.6.2")

But it would be cool to have more purity here :). 

The problem actually is in Maven Central repository metadata that for some reason defines `jackson-annotation` v2.5.0 with packaging type "bundle", which confuses Grapes.

**Comment by alkemist** [comment]
Depended on by #809
