### ISSUE TITLE
Test examples in manual not working as tests

### ISSUE THREAD

**Issue by stianl** [ratpack/ratpack#816]
As it is stands the ```SiteSmoketest``` sample from the testing chapter compiles, but if you include it in a project it is not executed (e.g. ```gradle test``` will build with no tests run). It think it should be written as a Spock specification or JUnit test case. I made an attempt at changing this so it will be run as a Spock test (see pull request #811 ). However, since the code is compiled with ```@CompileStatic``` and this is not supported by Spock framework it turns out that these changes doesn't work that well. 

I think it would be beneficial if the test samples from the manual would run as tests "as is", but (afaict) they must be compiled without ```@CompileStatic```. What do you think?

**Comment by alkemist** [comment]
Sorry this took so long to respond to. Yeah, we should fix this so it's complete.

We can just add a new kind of fixture for this test at https://github.com/ratpack/ratpack/blob/master/ratpack-manual/src/test/groovy/ratpack/manual/ManualCodeSnippetTests.groovy. 

Warning in advance: these test fixtures aren't the most polished part of our codebase.

It should be reasonably straight forward to set this up based on what's there. Is this something you would be interested in doing?

**Comment by stianl** [comment]
Yes, I'll take a stab at that!

**Comment by stianl** [comment]
Perhaps something simple as bf982f6800de9c64632c1e1845caad673eb9fedf is sufficent? It passes on Snap [without the most recent changes to master](https://snap-ci.com/ratpack/ratpack/pull/811/logs/defaultPipeline/4/Test?back_to=build_history). But when attempting to integrate with master there seems to be some [issue with the ```compassCompile``` task](https://snap-ci.com/ratpack/ratpack/pull/811/logs/defaultPipeline/3/Build?back_to=build_history) (perhaps memory related?):

    :ratpack-manual:compassCompile FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':ratpack-manual:compassCompile'.
    > Process 'command '/opt/local/java/1.8/bin/java'' finished with non-zero exit value 137
