### ISSUE TITLE
Upgrade to pac4j v1.8

### ISSUE THREAD

**Issue by leleuj** [ratpack/ratpack#819]
We just released pac4j v1.8 and as Ratpack uses it for authentication, it should be upgraded.

pac4j v1.8 is a major version as it is now a full security engine and not only an authentication one for Facebook, Twitter...: it now supports REST/web services as well as authorizations. Which allows implementations (like ratpack-pac4j) to become full security libraries.
Configuration can now be handled at the pac4j level (-> https://github.com/pac4j/pac4j/tree/master/pac4j-core/src/main/java/org/pac4j/core/config) as well as profile storage (-> https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/profile/ProfileManager.java).

The idea with pac4j v1.8 is not only to have implementations which are close, but to provide guidelines on how to implement pac4j and have the **same algorithm** implemented for all frameworks/tools, making evolutions and adoption easier.

If you read: https://github.com/pac4j/pac4j,

There are now two kinds of clients (= authentication mechanims):
- **indirect / stateful clients** are for UI when the user authenticates once at an external provider (like Facebook, a CAS server...) or via a local form (or basic auth popup)
- **direct / stateless clients** are for web services when credentials (like basic auth, tokens...) are passed for each HTTP request.

To define your security configuration, gather all your authentication mechanisms = [**clients**](https://github.com/pac4j/pac4j/wiki/Clients) via the `Clients` class (to share the same callback url). Also define your [**authorizers**](https://github.com/pac4j/pac4j/wiki/Authorizers) to check authorizations and aggregate both (clients and authorizers) on the `Config`.
Notice you may also use the `ConfigSingleton` object to keep one instance of your configuration and share it among the different components (if you don't have any dependency injection capability). You can also use the `ConfigFactory` to build you configuration if no other mean is available.

To secure your Java web application, **the reference implementation is to create two "filters"**: **one to protect urls**, **the other one to receive callbacks** for stateful authentication processes (indirect clients):
1) **For your protection "filter", it must be based on two String parameters: `clientName`** (list of clients used for authentication) **and `authorizerName`** (list of authorizers to check authorizations) and **use the following logic: loop on direct clients for authentication then check the user profile and authorizations**
2) **For your callback "filter", get the credentials and the user profile on the callback url**.

We moved things really far as you can see that both implementations between J2E and Play for example are very very close: https://github.com/pac4j/j2e-pac4j/blob/master/src/main/java/org/pac4j/j2e/filter/RequiresAuthenticationFilter.java#L91 vs https://github.com/pac4j/play-pac4j/blob/master/play-pac4j-java/src/main/java/org/pac4j/play/java/RequiresAuthenticationAction.java#L95.

Even the README are organized the same way with the same texts for common parts. The associated demos have been upgraded and that should be done for: https://github.com/pac4j/ratpack-pac4j-demo as well. The README of the demo can be copy/pasted from the one for J2E and updated.
There is even a specific logo for the ratpack-pac4j implementation: https://pac4j.github.io/pac4j/img/logo-ratpack.png which should appear at the top of the README demo and of the implementation documentation: http://ratpack.io/manual/current/pac4j.html#pac4j

If you have any question or need any help, don't hesitate.

**Comment by alkemist** [comment]
Thanks for the detailed information @leleuj . We are about to finalise 1.1, so will include the Pac4j upgrade in 1.2.

**Comment by leleuj** [comment]
Great! Keep me posted.

**Comment by leleuj** [comment]
Happy new year! Any feedback on this? Need any help?

**Comment by alkemist** [comment]
Hi @leleuj, Happy new year.

We slowed down a bit at the end of last year and haven't made any progress on this. It's still on the todo list. If you want to have a go at updating to 1.8, that would be great.

I haven't looked in detail into what's new in 1.8 to assess what it means for our integration API.

**Comment by leleuj** [comment]
In two words: authorization and REST support (direct authentication with credentials passed for each request). I'll see how I can propose some upgrade pull request.

**Comment by leleuj** [comment]
I will do the job in a few steps to make things easier for me. If you don't mind.

Here is the first pull request: https://github.com/ratpack/ratpack/pull/880 -> upgrade to pac4j v1.8.4. It works as previsouly, but the REST support and authorizations are not handled yet.

The CI build fails, but I don't think it comes from my changes. Help will be appreciated on this.

I have updated the demo accordingly: https://github.com/pac4j/ratpack-pac4j-demo/commit/fa0251b5c7328c46c51f9d2f442cd8bbd3385e52

The demo is not fully working as the endpoint created by Ratpack is /authenticator while I generally have configurations for /callback: is it something we can change?

**Comment by alkemist** [comment]
@leleuj I'd rather not use `/callback` as this URL makes far less sense (i.e. callback to what?), but if you have very strong feelings about this then we could change it.

**Comment by alkemist** [comment]
PR merged, thanks @leleuj 

I think we should close this, and have separate tickets for adding new stuff to take advantage of the new stuff in pac4j.

**Comment by leleuj** [comment]
In fact, it's not "callback to", but "callback from". You try to access a protected resource, you are redirected to an identity provider to login, then after a successful authentication, you are redirected back to the application on the callback url. The callback url receives callbacks from the identity providers.

My only concern about renaming this callback url is the backward compatibility which will be broken. I guess we can live with it if we document it properly.

OK. Let's close this pull request. I'll open new ones for REST support and authorizations.
