### ISSUE TITLE
Streams.periodically fails to emit items

### ISSUE THREAD

**Issue by donaldquixote** [ratpack/ratpack#822]
I have the following implementation of Service#onStart:
```
public void onStart(StartEvent event) throws Exception 
        { 
            Streams.periodically(event.getRegistry(), Duration.ofMinutes(1), unused -> {
                ...
                return someNonNullValue
            }).subscribe(new Subscriber<Integer>() { ... });
        }
```

I have verified that the service is registered and onStart is invoked. However, the periodic event is never triggered. Not on subscription, and not on configured period. Am I doing something wrong here?

**Comment by alkemist** [comment]
Does your subscriber issue any requests?

**Comment by donaldquixote** [comment]
Apologies for the noise. This was due to err on my part. Subscriber was not requesting anything.

**Comment by alkemist** [comment]
No problems @donaldquixote. Glad to know you are experimenting with it.
