### ISSUE TITLE
Is http2 support is planned to be included in ratpack?

### ISSUE THREAD

**Issue by niwinz** [ratpack/ratpack#824]
Hi!

Is http2 support is planned to be included in ratpack?

I have plans to add support for http2 support in catacumba, but I think that ratpack also could benefit of it, so, I have plans to implement it in the ratpack side. And I want to know if this kind of feature can be accepted into the ratpack core (for make the effort to implement it inside ratpack basically...).

What do you think about?

**Comment by alkemist** [comment]
Hi @niwinz ,

It's not something that we've actively scheduled or evaluated. My uneducated stance is that its still quite boutique so people would be using it out of interest more than any real need.

I'd be more than happy to start supporting it, as long as it doesn't impinge on the http1 support.

**Comment by niwinz** [comment]
Hi @alkemist 

The http2 is start to be adopted quickly.  Many services like google, twitter, reddit, among others aready using it. So start the development for support it seems a good direction, I think.

Obviously, it should be not intrusive for the user and completelly optional, maintaining http1 as the default. 

In any case, I'm not very fluent in java so do not know how long time it take to do it.

**Comment by alkemist** [comment]
Closing this in favour of #1002.
