### ISSUE TITLE
Provide method for AUT's to augment/override Guice bindings

### ISSUE THREAD

**Issue by johnrengelman** [ratpack/ratpack#828]
Related to https://github.com/ratpack/ratpack/issues/680

Need something similar to `MainClassApplicationUnderTest.createOverrides(Registry)` to override/augment Guice bindings in tests.

**Comment by tednaleid** [comment]
+1

Playing with ratpack and creating tests and this was one of the first issues I hit.  Tried using `createOverrides` but guice has already wired everything up so it's too late to inject any mocks that I've created

**Comment by alkemist** [comment]
See https://ratpack.io/manual/1.2.0/api/ratpack/guice/BindingsImposition.html
