### ISSUE TITLE
Provide a way to convert a collection of promises to a list of their fulfilled results

### ISSUE THREAD

**Issue by danveloper** [ratpack/ratpack#829]
As a Ratpack programmer, 
  I would like a way to convert `Iterable<Promise<T>>` to `Promise<List<T>>`
So that
  I may be able to easily asynchronously transform a collection of objects and act upon the collected results of the transformations.

**Comment by tednaleid** [comment]
This would be nice, sounds equivalent to what the [JS `Q` library provides with it's `Q.all()` function](https://strongloop.com/strongblog/how-to-compose-node-js-promises-with-q/).  Not seeing a clean way to do this with the current promise library which can hurt composability of promises.  RxJava currently seems like the cleaner way of doing this using it's `flatMap` fuction.

**Comment by danveloper** [comment]
@tednaleid in the meanwhile, you can use Ratpack's reactive streams support to do this:

```
List<Promise<Thing>> promises = [...]

Streams.publish(promises).flatMap { it }.toList().then { List<Thing> things ->
  // ...
}
```

**Comment by tednaleid** [comment]
Ah interesting Dan! Thanks, didn't know about the streams support for promises.  That's great in the interim.

**Comment by johnrengelman** [comment]
This is handled by the new `Batch` API from https://github.com/ratpack/ratpack/pull/977
