### ISSUE TITLE
Crash ratpack if using default configuration from start.spring.io. How to use resource from jar?

### ISSUE THREAD

**Issue by lavcraft** [ratpack/ratpack#848]
Reproduce
---------------

```bash
curl https://start.spring.io/starter.tgz -d dependencies=ratpack -d type=gradle-project -d baseDir=my-dir | tar -xzvf - && cd my-dir
vi src/main/java/com/example/DemoApplication.java
```

Then edit DemoApplication.java
```java
import ratpack.spring.config.EnableRatpack;

@EnableRatpack
public class DemoApplication {
...
```

Build project and run
```bash
gradle wrapper && ./gradlew build -x test
java -jar build/libs/demo-0.0.1-SNAPSHOT.jar
```

java -jar.. output:
```
Caused by: java.lang.IllegalArgumentException: Filesystem binding must be absolute
        at ratpack.file.internal.DefaultFileSystemBinding.<init>(DefaultFileSystemBinding.java:32)
        at ratpack.file.FileSystemBinding.of(FileSystemBinding.java:52)
        at ratpack.server.internal.DefaultServerConfigBuilder.baseDir(DefaultServerConfigBuilder.java:66)
        at ratpack.spring.config.RatpackConfiguration$ServerConfigConfiguration.ratpackServerConfig(RatpackConfiguration.java:72)
        at ratpack.spring.config.RatpackConfiguration$ServerConfigConfiguration$$EnhancerBySpringCGLIB$$9448c0b4.CGLIB$ratpackServerConfig$0(<generated>)
        at ratpack.spring.config.RatpackConfiguration$ServerConfigConfiguration$$EnhancerBySpringCGLIB$$9448c0b4$$FastClassBySpringCGLIB$$2e50e497.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:318)
        at ratpack.spring.config.RatpackConfiguration$ServerConfigConfiguration$$EnhancerBySpringCGLIB$$9448c0b4.ratpackServerConfig(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
        ... 37 more
```

About problem
-------------------

Throw exception from [DefaultSystemBinding.java:29](https://github.com/ratpack/ratpack/blob/6b5db756a271700d9ec9e7d56e467b95195eb7c4/ratpack-core/src/main/java/ratpack/file/internal/DefaultSystemBinding.java#L29)

Field baseDir configure in that class [RatpackProperties.java:204](https://github.com/ratpack/ratpack/blob/6bc02e0bbd5a7571636afc5faa112727f598d593/ratpack-spring-boot/src/main/java/ratpack/spring/config/RatpackProperties.java#L204)

Workaround
-----------------

How to use runnable jar with web resources inside jar? Default base dir is not absolute, and if i try to set properties.baseDir = ClassPathResource.. , app has been crashed in [DefaultSystemBinding.java:29](https://github.com/ratpack/ratpack/blob/6b5db756a271700d9ec9e7d56e467b95195eb7c4/ratpack-core/src/main/java/ratpack/file/internal/DefaultSystemBinding.java#L29)

Temporary fix it:

```java
@Configuration
class RatpackAdvancedConfiguration {

  Logger log = LoggerFactory.getLogger(RatpackAdvancedConfiguration.class);

  @Autowired
  RatpackProperties properties;

  //TODO temporary fix for ratpack error. Ratpack application could not be executed from jar
  @PostConstruct
  void fixBaseDir() {
    properties.setBasedir(new FileSystemResource("src/main/resources"));
    // default value : properties.setBasedir(new ClassPathResource(""));
  }
}
```

Can i read resources from jar? I tried unpack jar in production env and run java -cp, its work, but really hard to use and no beautiful solution. What is better solution? :(

**Comment by lavcraft** [comment]
In my opinion, this behaviour is a bug

**Comment by johnrengelman** [comment]
@lavcraft I'm trying to replicate this report, but I'm not having any luck. 
When I follow the commands above the following happens for me:
1) `./gradlew build` fails because the `DemoApplicationTests` unit test fails with an error
2) If I bypass this `build` and just create the JAR with `./gradlew jar` and then run the `java -jar` command I get the following:
```
$ java -jar build/libs/demo-0.0.1-SNAPSHOT.jar
no main manifest attribute, in build/libs/demo-0.0.1-SNAPSHOT.jar
```

Can you verify this for me? I'm thinking this perhaps an issue with the SpringBoot Start implementation for Ratpack in which case we may need to get them involved. I know there was just a PR to add a new submodule to Ratpack for Spring Boot Start (https://github.com/ratpack/ratpack/blob/master/ratpack-spring-boot-starter/ratpack-spring-boot-starter.gradle), which will be available in the 1.2.0 release when it happens.

**Comment by lavcraft** [comment]
@johnrengelman sorry, use `./gradlew build -x test` instead of `./gradlew build`
Test fail, yes. If resolve problem, then test pass :)

**Comment by dsyer** [comment]
I think it's technically a bug in `ratpack-spring-boot` (`ratpack.spring.config.RatpackProperties.resourceToPath(URL)`) since it makes an assumption that the default `FileSystemBinding` can handle resources in jars, whereas actually it cannot. IMO it would be a useful addition to Ratpack for it to have a `FileSystemBinding` that can be used with jar resources (or anything on the classpath really). I'm pretty sure it used to work, back in 0.x, but I can't prove it easily.

**Comment by alkemist** [comment]
@dsyer we use `java.nio.file.Path` which _should_ be sufficient abstraction. If it used to work, it should still work as nothing has changed here in quite a long time. 

Do you have any more specifics on what doesn't work?

**Comment by dsyer** [comment]
You are right: `Path` is a good enough abstraction. I think older versions of Ratpack must have had more complicated file/asset resolution, but it would have been 0.x when I first wrote this code so it's a long time ago and much could have changed. See #882 for a fix. I'm not sure if there is something else to do for other types of Ratpack app (it seems kind of generic, but I don't know how much other Ratpack users like to put static assets in jars). Anyway this will work for the normal Spring Boot packaging (so "java -jar ..." with assets in /static or /public).

**Comment by alkemist** [comment]
Fixed by the man @dsyer himself.
