### ISSUE TITLE
Update lettuce dep in 'ratpack-session-redis' module to 4.0.Final

### ISSUE THREAD

**Issue by joshdurbin** [ratpack/ratpack#854]
Update lettuce dep in 'ratpack-session-redis' module to 4.0.Final

**Comment by danhyun** [comment]
With regards to Lettuce, I think we want to hold off until 4.1.Final is released in Jan 2016 so we can share EventLoopGroups.

**Comment by joshdurbin** [comment]
Ah yes, perfect!
