### ISSUE TITLE
Typo in guide

### ISSUE THREAD

**Issue by anshbansal** [ratpack/ratpack#872]
In the [guide about launching](https://ratpack.io/manual/current/launching.html#launching) it says

>There may be many different registries within an application, but all applications are backed a “server registry”. 

It should be 

>There may be many different registries within an application, but all applications are backed **by** a “server registry”.

**Comment by anshbansal** [comment]
In the [guide about context](https://ratpack.io/manual/current/context.html#context) it says

>Access the HTTP Request and Response

It should be

>Access **to** HTTP Request and Response

**Comment by alkemist** [comment]
Resolved in 426685431694f41071d33d9c0930756396d05d3d.
