### ISSUE TITLE
Loading and reloading of groovy scripts backing the app leaks non-heap memory.

### ISSUE THREAD

**Issue by erdi** [ratpack/ratpack#877]
Loading (in `ratpack.groovy.Groovy`) and reloading (in `FileBackedReloadInformant` and `ReloadableFileBackedFactory`) groovy scripts backing the application is done using `ratpack.util.internal.IoUtils.read()` but the `BytBuf`s returned are never released.

There are two possible solutions:
- go through all usages of `IoUtils.read()` and ensure that the buffers returned are eventually released
- given that there doesn't seem to be any advantage to using `ByteBuf`s for loading and reloading of the contents of the app script replace these calls with `Files.readAllBytes()` and deal with `String`s instead, which will be put on heap and therefore GCed when no longer used.

Note that loading of the script happens only once per application run and reloading of the app happens in development mode only and thus production apps are not affected by this issue.

**Comment by alkemist** [comment]
Let's remove IoUtils and not use byte bufs here.
