### ISSUE TITLE
Consider using last modified timestamp instead of comparing the whole app script for each request when detecting changes

### ISSUE THREAD

**Issue by erdi** [ratpack/ratpack#878]
`ReloadableFileBackedFactory` is already using this strategy, consider using it in `FileBackedReloadInformant` which currently unnecessarily reads script contents for each request.

**Comment by alkemist** [comment]
This would be fine. A spurious reload is not that costly.

**Comment by alkemist** [comment]
Was done in 1db829897e9ceca94d1e651df89707a0efb610c8.
