### ISSUE TITLE
Allow specifying order of service setup/teardown

### ISSUE THREAD

**Issue by donaldquixote** [ratpack/ratpack#883]
Ratpack services (referring to the specific interface that provides start/stop lifetime hooks) provide no way for the developer to specify order of invocation. According to documentation, the order of service invocation is dependent on the registry implementation to which the services are registered.

Is there a technical limitation preventing implementation of this capability, or has this just not been requested enough?

Thanks.

**Comment by alkemist** [comment]
The only limitation is in coming up with a decent way to do this. It's an insidious problem, as evidenced by Spring's `Ordered` and the looseness it causes.

In short, if there is need to order the services and and if we can come up with a decent way of expressing desired order… there's no reason it can't be added.

**Comment by alkemist** [comment]
Here's a plan for this:

1. Introduce `@ServiceDependencies` …

```language-java
package ratpack.server;

@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@Inherited
public @interface ServiceDependencies {
  Class<? extends Service?>[] value();
}
```

`Service` types can use this annotation to statically declare their dependencies.

2. Introduce `ServiceDependencySpec` …

```language-java
package ratpack.server;

interface ServiceDependencySpec {
  // all service that match the dependents filter, will be marked as being dependent on all services that match the dependencies filter 
  ServiceDependencySpec dependsOn(Predicate<? super Service> dependents, Predicate<? super Service> dependencies)
}
```

On startup, all instances of `Action<ServiceDependencySpec>` (or some sugar wrapper) will be obtained from the user registry and executed to specify service dependencies. There will be no functional difference between dependencies declared this way and by `@ServiceDependencies`. 

This more verbose case is an escape hatch for when dependencies either need to be declared in a more general fashion (e.g. all services of these type depend on all services of this type), or for when the user is not in control of the service type and wishes to impose a dependency.

3. Have Ratpack honour these dependencies by ensuring that dependent services start after and stop before their dependencies.

The general strategy can be described as describing the relationships between services in a directed acyclic graph. Given this information, we can honour any require ordering and also safely start/stop services in parallel that are not dependent which makes startup and shutdown faster.

**Comment by donaldquixote** [comment]
Seems reasonable. It would be very important to explicitly verify the dependency graph is indeed acyclic for the sake of the developer. Also, a sugar spec builder might be nice, something like:

`ServiceDependencySpecBuilder dependents(Class<? extends Service>... dependent);

ServiceDependencySpecBuilder dependencies(Class<? extends Service>... dependency);`

It seems to me that majority of cases will involve predicates that simply reflect the object type against a target set of types.
