### ISSUE TITLE
Documentation on using maven

### ISSUE THREAD

**Issue by binkley** [ratpack/ratpack#893]
I recognize from the docs you are _opinionated_ about gradle.  Even so, it would be quite helpful, and aid in adoption, to provide maven instructions and/or examples.

**Comment by alkemist** [comment]
Hi @binkley ,

You're right, we do prefer Gradle. However, there's no coupling between the build time and the run time. As such you can just use the Ratpack libraries like any other library. You simply write a main class as the entry point.

Here's an example of a Maven based Ratpack project: https://github.com/pac4j/ratpack-pac4j-demo

We do not provide a hot reloading mechanism for Maven though, as we rely on Gradle's continuous build for this.

**Comment by nileflowers** [comment]
Great work team on this project!

Are there plans to publish 1.5.0 to Maven Central?

**Comment by ldaley** [comment]
It's there now. Sorry for the delay. I didn't realise that the sync had failed initially.

**Comment by binkley** [comment]
Thank you!
