### ISSUE TITLE
Support web services authentication (pac4j direct clients)

### ISSUE THREAD

**Issue by leleuj** [ratpack/ratpack#896]
As ratpack v1.2.0 is now based on pac4j v1.8.5, it can support web services authentication via direct clients.

**Comment by leleuj** [comment]
Great! Next week, I will update the demo and submit a pull request to update the documentation.

**Comment by leleuj** [comment]
@alkemist : and your implementation is good, though, you must notice that the pac4j security model is meant to have a "security filter" dealing with several direct clients by looping through them trying to login with one of them (while the "callback handler" only applies to one indirect client). Here is the reference implementation in J2E: https://github.com/pac4j/j2e-pac4j/blob/master/src/main/java/org/pac4j/j2e/filter/RequiresAuthenticationFilter.java#L118

This is certainly something worth being implemented in a future version of Ratpack. What do you think?

**Comment by alkemist** [comment]
@leleuj I'll have to dig in a bit deeper and fully understand the usage patterns. Things seem functional at the moment, but not quite composable or clear enough.

**Comment by leleuj** [comment]
Here is a summary of the pac4j guidelines to implement pac4j for a new framework: https://github.com/pac4j/pac4j/wiki/Implement-pac4j-for-a-new-framework---tool
It partially recalls what I already said

**Comment by leleuj** [comment]
I just updated the demo: https://github.com/pac4j/ratpack-pac4j-demo/commit/c475ad9edcc1047c712529eaf41f8acf17485ed0 Everything works with the direct clients ;-)

**Comment by leleuj** [comment]
@alkemist : about the documentation, I just submitted a pull request: https://github.com/ratpack/ratpack/pull/905

I'm not sure you took my previous documentation "as is" (I admit my English is far from perfect) so feel free to consider this new pull request as a proposal to help you update the Ratpack pac4j documenation.
