### ISSUE TITLE
ServerConfig.maxContentLength should be a long

### ISSUE THREAD

**Issue by ldaley** [ratpack/ratpack#906]

**Comment by johnrengelman** [comment]
This poses some issues where we integrate with Netty classes (i.e. `HttpObjectAggregator`, `WebSocketServerHandshakerFactory`).

**Comment by johnrengelman** [comment]
I think we'll need to submit an issue to github.com/netty/netty to have this change made upstream. I don't see how we could do it without losing precision on the down sampling from `long` -> `int`

**Comment by ldaley** [comment]
I'm going to close as won't fix. 2GB seems like a reasonable _default_ max length for request bodies. This can be overridden per request with a long value.
