### ISSUE TITLE
Concurrency issue with Context.getRequest().getBody() since ratpack 1.1.0

### ISSUE THREAD

**Issue by sebbonnet** [ratpack/ratpack#909]
We have found an issue where it seems that the above getBody() promise is never fulfilled during concurrent requests.  This means that the client making the request will never receive a response.

This issue does not happen in 1.0.0, but from 1.1.0 onwards.

Please see the code base here: https://github.com/sebbonnet/ratpack-concurrency-bug for an example of the issue and a simple load test.

**Comment by danhyun** [comment]
Thanks for the report, this seems to be a duplicate of https://github.com/ratpack/ratpack/issues/850 which is addressed in 1.2.0.

If you want to continue working with 1.1.0 you could disable development mode. If you produce a jar file or the install shadow app you won't see this problem.

I've tried the following with your repo as is just to demonstrate that production execution is not affected:

`Dockerfile`
```dockerfile
FROM anapsix/alpine-java

WORKDIR /app

ADD build/installShadow/ratpack-concurrency-bug .

CMD ["/app/bin/ratpack-concurrency-bug"]
```

```bash
$ ./gradlew clean installShadow
$ docker build -t ratpack-bug .
$ docker run --rm -it --name ratpack-bug ratpack-bug
```

Dockerfile for wrk2 (after cloning from https://github.com/giltene/wrk2)
```dockerfile
FROM ubuntu:14.04

RUN apt-get update && apt-get install -y build-essential libssl-dev

RUN mkdir /wrk2
ADD . /wrk2

WORKDIR /wrk2

RUN make

CMD ["bash"]
```

Build wrk2 and run load test against running ratpack app container
```bash
$ docker build -t wrk2 .
$ docker run --rm -it --link ratpack-bug:ratpack wrk2
```

From within wrk2 container
```
$ cat /wrk2/postbody.lua // add this file with the following content
wrk.method = "POST"
wrk.body   = "Hello World"
wrk.headers["Content-Type"] = "application/x-www-form-urlencoded"

$ ./wrk -c 10 -t 5 -R 1000 -d 30s -s postbody.lua http://ratpack:5050/foo
```

Sample output:

```
root@4f98512c9ad2:/wrk2# ./wrk -c 10 -t 5 -R 1000 -d 30s -s postbody.lua http://ratpack:5050/foo
Running 30s test @ http://ratpack:5050/foo
  5 threads and 10 connections
  Thread calibration: mean lat.: 1.115ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 1.010ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 0.989ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 1.150ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 0.961ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.91ms  503.14us  12.38ms   74.93%
    Req/Sec   211.11     33.73   400.00     89.53%
  29998 requests in 30.00s, 1.77MB read
Requests/sec:    999.89
Transfer/sec:     60.54KB
```

1.2.0-rc-2 is available so if you want to try against this RC you can use `./gradlew run` with your ab load test

**Comment by alkemist** [comment]
As @danhyun, this has been fixed. It's worth noting that this only affected development mode, and not production.

**Comment by sebbonnet** [comment]
Hi @danhyun, @alkemist,

Thanks for the quick response!

We've isolated the problem to launching ratpack in IntelliJ IDEA (15.0.2) via the built-in Application launcher, which means it is not related to development mode and defect #850.

We've updated our example to show this. Have a look into run-app-using-idea-launcher.sh.

This is less of an issue for us as we can work around it.

**Comment by alkemist** [comment]
Hi @sebbonnet,

when you start from IDEA, you are running in development mode. We detect this here: https://github.com/ratpack/ratpack/blob/04847e0c92d397a648a26a4be6f7af7ced85e13e/ratpack-core/src/main/java/ratpack/server/internal/ServerEnvironment.java#L88-L88
