### ISSUE TITLE
HealthCheckHandler should respond with status code 503 when unhealthy

### ISSUE THREAD

**Issue by mchlstckl** [ratpack/ratpack#912]
I noticed that the `HealthCheckHandler` always responds with status code 200 even when a health-check fails. Both Dropwizard and Spring Boot respond with a 5xx code on failure.

Just wondering if this is intentional or not. If not, I think returning status code 503 would be the preferred status code for when a health-check fails.

**Comment by mchlstckl** [comment]
I've implemented this as a *renderer*.

```
import ratpack.handling.Context;
import ratpack.health.HealthCheckResults;
import ratpack.health.internal.HealthCheckResultsRenderer;
import ratpack.render.RendererSupport;

public class StrictHealthCheckResultsRenderer extends RendererSupport<HealthCheckResults> {
    @Override
    public void render(Context ctx, HealthCheckResults healthCheckResults) throws Exception {
        boolean isUnhealthy = healthCheckResults
                .getResults()
                .values()
                .stream()
                .anyMatch(result -> !result.isHealthy());

        ctx.getResponse().status(isUnhealthy ? 503 : 200);
        ctx.get(HealthCheckResultsRenderer.class).render(ctx, healthCheckResults);
    }
}
```

**Comment by danhyun** [comment]
The idea that the HTTP response status code should indicate health of the system is a contentious one.

HTTP response codes are meant to convey information about the request itself, not about interpreting the contents of the body or . It would be difficult to determine whether the state of the application is unhealthy or merely that the application had a problem processing the request for the health check endpoint.

Having said that, health check implementations, like Amazon's ELB is very simplistic and relies strictly on HTTP response code to determine health of a system. Ratpack should provide the ability to configure aspects about the health check HTTP response such as response code or additional response headers.

**Comment by alkemist** [comment]
I hate the idea, but if Dropwizard and Spring Boot issue a 503 then that's strong precedent and we should do it.
