### ISSUE TITLE
Advertise a logical location in the request handling control flow via path binding description

### ISSUE THREAD

**Issue by alkemist** [ratpack/ratpack#914]
## Background

We've had a long standing deficiency in that there's no convenient way to identify “what” handled a request. A large contributor to this is that our handling is composed of functions (that have a weak notion of identity), where other MVC type frameworks use classes/methods (that have a strong notion of identity). This affects diagnotics, including error messages, New Relic integration, metric integration and more.

## Proposed solution

We can use the string representation of the cumulative path binding to indicate location.

Given:

```
handlers {
  prefix("foo/:b") {
    get("baz") { 
      render "ok"
    }
  }
}
```

A request to `/foo/bar/baz` would be handled by the “location” `foo/:b/baz`.
A request to `/foo/foo/baz` would be handled by the “location” `foo/:b/baz`.

## Implementation

We already make the given `PathBinding` at any point in time available via the execution internally (see `PathHandler`). We just need to have `PathBinding` give a string representation of itself, based on the originating `PathBinder`.

We could take roughly the following steps:

1. Have TokenPathBinder accept an extra string with is effectively its source path spec (e.g. `foo/:b`)
2. Make the string form the canonical form of a path binder

For 2, this would involve:

1. Having DefaultPathBinderBuilder build a path string
2. Have DefaultPathBinderBuilder.parse() turn the path string into the executable form

This is in contrast to the way things work now where the executable form is canonical, and DefaultPathBinderBuilder.parse() uses DefaultPathBinderBuilder.build().

**Comment by tylerbenson** [comment]
This is great!  I would also suggest providing some information as to the HTTP Method if relevant, since the same path could go to different handlers depending on GET/POST/etc.

**Comment by brandonwirick** [comment]
In addition to a "canonical" form, which I imagine would be valuable for collision detection and handler naming, I think a "searchable" form would be valuable. If I just see `foo/:b/baz`, I don't know that `foo/:b` is the prefix, which is a string literal I could search for in code. A "searchable" form might just be the "canonical" form with whitespace added, like `foo/:b / baz`.

**Comment by alkemist** [comment]
@brandonwirick I'm not sure here. That's a pretty heavy cognitive price to pay.

What do you have in mind where this would be so important?

**Comment by brandonwirick** [comment]
I've encountered this problem with projects that use Spring MVC to direct web requests. There is no quick way to find the "controller method" associated with a URL, because I have to search for many token combinations. Ratpack doesn't have it nearly as bad because the handlers all touch one chain instead of appearing in random annotated methods. Still, having some sense of the path it takes through the chain would be nice.
