### ISSUE TITLE
question: how to add a mock module for demo purposes which is in another sourceSet

### ISSUE THREAD

**Issue by childnode** [ratpack/ratpack#921]
if I have a mock module in a different sourceSet like
https://gist.github.com/childnode/0ba89ddeedeb321e7977

Can I dynamically attach a Module into the WebApp if it's available in the compilation?
s.th. like:

                .registry(Guice
                        .registry(bind -> bind
                            .module(MainModule.class)
                            .module(SomeProductiveStuffModule.class)
                            .moduleOfType(InterfaceOfModules.class)))

This would also improve no module has to be given to the registry manually when adding one

                .registry(Guice
                        .registry(bind -> bind.moduleOfType(InterfaceOfModules.class)))

backlinks:
* https://ratpack.io/manual/current/api/ratpack/guice/Guice.html

**Comment by danveloper** [comment]
Hi @childnode! It might help if you told us what the scenario is for what you're trying to accomplish? Is this for testing purposes? (Ratpack has integration test fixtures to help with modifying the bindings.) Is this for dynamically binding your implementation at runtime based on classpath presence? Or...?

**Comment by childnode** [comment]
Hi, yes dynamic binding is one case as I mentioned with the second example but my origin use case would be a demonstration deployment where certain services are 'mocked', not only for testing where I can indeed simply set up my test server configuration. So in the end I would like to add modules per configuration. Hope this clarified by purpose. ~marcel

**Comment by danhyun** [comment]
It almost sounds like you want spring like component scanning? If it's on the classpath load it kind of functionality, is that right?

**Comment by childnode** [comment]
Jep, that would be the optimal one.

**Comment by childnode** [comment]
ok, found a way, thought about a second, both not that elegant as expected:

1. define Module bindings by using `Modules` class and override methods, e.g. 
https://gist.github.com/childnode/3af9787dc865156c46eb
**BUT: this has a drawback** if a module needs to be a `ConfigurableModule<T>`

2. use guice's `@ImplementedBy` annotation, rebind only in the second case, no example here yet
this leads me to the discussion about the good and bad of http://stackoverflow.com/questions/6197178
and also it's not clear to me what to write at the ratpack registry section

            .registry(Guice.registry(b ->
                    b.bind(…)))

any input / feedback / known bugs || feature-requests are welcome ;)

**Comment by alkemist** [comment]
In Ratpack, modules are always override modules. That is, any module can override bindings of a previous module.

Beyond that, I'm still not quite sure what you are trying to achieve in terms of how the code is structured and when/why the dynamic loading is needed.

**Comment by danveloper** [comment]
@childnode do you have any more thoughts/feedback on this issue? or we're ok to close it? Thanks!

**Comment by childnode** [comment]
@alkemist about how code ist structures, have a look at the [gist](https://gist.github.com/childnode/0ba89ddeedeb321e7977)
The main thing I'm on is: if you have modules not in the main sourceSet of the ratpack application, you can't refer to them as common in `bind -> bind.module(OptionalModule.class)` since it's not clear, if the sourceSet with the OptionalModule is entitled in the package after build.

But I see ... it's a guicy thing ... so: 

https://github.com/ratpack/ratpack/issues/921#issuecomment-193331950
^ where comment 1 is off-topic because I the scope myself on evaluating certain approaches 

=> guice doesn't support dynamic binding out of the box

=> I bet this has to be discussed as a guice issue not a ratpack one

=> please #close

**Comment by SlyDen** [comment]
@childnode One option: 
you can put some ENV var as an indicator to "mock some service" and pass it to ConfigurableModule<T> ... and where you can use  [Binding Annotations] (https://github.com/google/guice/wiki/BindingAnnotations)
