### ISSUE TITLE
ByteBufBackedTypedData doesn't reset read index after calling getBytes()

### ISSUE THREAD

**Issue by tylerbenson** [ratpack/ratpack#922]
This causes subsequent calls to getBuffer() to result in an "empty buffer".

The use case around this is I need to read the body in two different handlers.  I worked around this by saving off the body's `TypedData` the first time I read it into the request registry.  The first handler essentially calls `getBytes()` and the second calling `getBuffer()` which returns a "read only" buffer with the read index already set to the end of the buffer.

I've worked around this by calling `resetReaderIndex()` right after calling `getBuffer()` but this seems like the wrong behavior.

**Comment by alkemist** [comment]
This is just the way ByteBuf works. The framework isn't in a position here to second guess what the user intends (e.g. reset the read index implicitly), but the user is.

**Comment by johannespetzold** [comment]
It does not seem intuitive that `getBuffer` returns the same buffer each time, but `getBytes` effectively "consumes" the bytes the first time it's called. Maybe Javadoc could be added to clarify? Which could also point to `resetReaderIndex` if one does want to read the buffer again after calling `getBytes`.

**Comment by johannespetzold** [comment]
Although why not just have `getBuffer` call `resetReaderIndex` internally? The contract of `getBuffer` would then be "give me the whole thing, independent of other readers that came before or after me". Given that `getBuffer` already does not affect subsequent readers, it might as well not be affected by previous readers either to be consistent.

**Comment by alkemist** [comment]
Let's go with just documenting this on the getBuffer() method.
