### ISSUE TITLE
GroovyEmbeddedApp should implement ratpack.groovy.Groovy.Ratpack

### ISSUE THREAD

**Issue by erdi** [ratpack/ratpack#925]
I don't see any reason why it couldn't do so and if it did then you could use the familiar dsl available in Ratpack Groovy scripts when defining embedded applications.

**Comment by alkemist** [comment]
That's a pretty good idea.

**Comment by johnrengelman** [comment]
Do we actually mean this class? https://github.com/ratpack/ratpack/blob/master/ratpack-groovy/src/main/java/ratpack/groovy/server/GroovyRatpackServerSpec.java

`GroovyEmbeddedApp` seems to just be the entry point with the `of` method.

**Comment by johnrengelman** [comment]
If so this doesn't appear to be possible as:
https://github.com/ratpack/ratpack/blob/master/ratpack-groovy/src/main/java/ratpack/groovy/Groovy.java#L135

and

https://github.com/ratpack/ratpack/blob/master/ratpack-groovy/src/main/java/ratpack/groovy/server/GroovyRatpackServerSpec.java#L41

clash.

**Comment by erdi** [comment]
The idea is to be able to use the exact same dsl when defining a groovy
embedded app as the one used in ratpack.groovy.

Why don't we just add another a static method that will take a closure that
delegates to ratpack.groovy.Groovy.Ratpack?

**Comment by johnrengelman** [comment]
@erdi - https://github.com/ratpack/ratpack/pull/992
