### ISSUE TITLE
How to test code involving promises

### ISSUE THREAD

**Issue by LeanderK** [ratpack/ratpack#929]
i have code where i wrap an asynchronous library call (returns completableFuture) into an promise to use with ratpack. When i test the code via:
`Blocking.on(func.apply(commands, context));`
(func returns Promise<T>) it throws an UnmanagedThreadException with atpack.exec.UnmanagedThreadException: Operation attempted on non Ratpack managed thread 'main'. How can i test my code?

**Comment by danhyun** [comment]
You'll want to make use of [`ExecHarness`](https://ratpack.io/manual/current/api/ratpack/test/exec/ExecHarness.html) in your test from `ratpack-test` module.

Something like this:

build.gradle
```
plugins {
  id 'io.ratpack.ratpack-java' version '1.2.0'
}

dependencies {
  testCompile ratpack.dependency('test')
}
```

Test.java
```java
@AutoCleanup
ExecHarness execHarness = ExecHarness.harness();

@Test
public void myJunitTest() {
  ExecResult myExpectedValue = execHarness.yield(e -> Blocking.on(func.apply(commands, context)); //1

  assertNotNull(myExpectedValue.getValue());
}
```

<1> Note you can replace call to `Blocking.on(..)` with your Promise if you have this in some kind of service class.

**Comment by LeanderK** [comment]
thank you, problem solved!

**Comment by danhyun** [comment]
Feel free to join our [community Slack channel](http://slack-signup.ratpack.io/) we are quite active in answering quick questions like these.
