### ISSUE TITLE
Cookies set by a Handler should be accessible from a RequestFixture result

### ISSUE THREAD

**Issue by tylerbenson** [ratpack/ratpack#938]
Something like this would be really nice.

```
def result = GroovyRequestFixture.handle(new MyHandler())
result.cookies.get("SomeCookie") != null
```

Currently it's non-trivial to verify an cookies are set if a response is not rendered by the handler.

**Comment by danhyun** [comment]
This stems from having a Handler that doesn't directly send a response:

```groovy
    class MyHandler extends GroovyHandler {
        protected void handle(GroovyContext ctx) {
            ctx.response.cookie('foo', 'bar')
            ctx.next()
        }
    }
```

**Comment by alkemist** [comment]
Implementation should be simple; just expose the return of `getCookies()` from the response on the result objet.

**Comment by alkemist** [comment]
Reopening due to some documentation issues (see linked commits)
