### ISSUE TITLE
Feature: Declarative handlers

### ISSUE THREAD

**Issue by mzachar** [ratpack/ratpack#950]
Hi,

I would like to propose feature which would allow you to write ratpack handlers in declarative way (similar to spring controller)

e.g.:
```java
@Handler
@Prefix("chain/person/:id")
public class ChainHandler {

	@Order(1)
	@Path
	public Registry all(@PathToken("id") String id) {
		Person person = new PersonImpl(id, "example-status", "example-age");
		return Registry.single(Person.class, person);
	}

	@Path("status")
	public String status(Person person) {
		return "person " + person.getId() + " status: " + person.getStatus();
	}

	@Path("age")
	public String age(Person person) {
		return "person " + person.getId() + " age: " + person.getAge();
	}

}
```

As a demo I already implemented really simple version just to better showcase the idea. You can take a look at working examples here [https://github.com/mzachar/ratpack-declarative-handling](https://github.com/mzachar/ratpack-declarative-handling)

What do you think? is this something worth persuading further?

**Comment by alkemist** [comment]
Hi @mzachar,

Sorry, this one got lost in the shuffle.

I'm going to close this as won't fix. We don't want to take Ratpack in this direction, at least out of the box. Such annotations and indirection don't align with our philosophy. 

If you'd like to publish such work in an external module, we'll happily promote it though.

Sorry again about the delay in response.
