### ISSUE TITLE
Support Guice Providers that return null

### ISSUE THREAD

**Issue by rhart** [ratpack/ratpack#965]
Despite the javadoc of `com.google.inject.Provider` saying you must never return null, it appears that Guice does actually support this.

This is the issue for allowing null injection by using any `@Nullable` annotation https://github.com/google/guice/issues/112 and the documentation for it https://github.com/google/guice/wiki/UseNullable.  We should change the retention policy of Ratpack's @Nullable to runtime to make use of this

There is also `com.google.inject.multibindings.OptionalBinder<T>` (https://google.github.io/guice/api-docs/4.0/javadoc/com/google/inject/multibindings/OptionalBinder.html) where a Provider may return null.  I propose that `Registry#maybeGet` should support this.

**Comment by drmaas** [comment]
+1

This will help with a lot of use cases we have for optionally injecting data.
