### ISSUE TITLE
Errors raised in DefaultPromise.then are routed to the promise error handler

### ISSUE THREAD

**Issue by mkavanagh** [ratpack/ratpack#973]
We're using code in our handlers like:
```java
promise.onError(throwable -> // do stuff)
    .then(foo -> ctx.next(Registry.single(Foo.class, foo))
```

When a handler further down the chain throws an exception this is wrapped by DefaultContext into a HandlerException (which is an Error).

Since the implementation of Downstream.success in DefaultPromise.then only catches subtypes of Exception, these errors (and any other Error thrown by the action given to Promise.then) will propagate back upstream and end up being routed to the promise's own error handler. This is different from the handling given to Exception/RuntimeException, which are routed to the execution's error handler.

Currently we're working around this with:

```java
promise.onError(throwable -> // do stuff)
    .next(foo -> ctx.next(Registry.single(Foo.class, foo))
    .then(Action.noop())
```

which gives the behaviour we want, but I propose that the error handling behaviour of Promise.then actions should be made consistent with respect to Error, Exception and RuntimeException (by routing them all to the execution).

**Comment by alkemist** [comment]
Agreed. Thanks for the fix.
